set CrossFire::cardDataBase {
    Artifacts
    {AR    1 +9 2 7 0 {Wand of Orcus} {This Wand can be attached to any undead monster champion. When the Wand is used in battle against an opposing champion of level 8 or less, the opponent is instantly slain (discarded). Limit one per deck.} R {} {32 33} {} 1}
    {AR    2 +3 2 7 0 {Axe of the Dwarvish Lords} {The Axe can be attached to any champion. In addition to the listed bonus, the Axe also gives the attached champion a +8 ally in combat.} C {} {32 33} {} 1}
    {AR    3 {} 2 2 0 {Iron Flask of Tuerny the Merciless} {The Flask gives the attached champion a +6 tanar'ri ally that can earthwalk and cast wizard spells. If the artifact is discarded, the attached champion is also discarded.} UC {} {13 32 33} {d19 o19} 1}
    {AR    4 {} 2 2 0 {Jacinth of Inestimable Beauty} {In combat, one enemy ally (chosen by this player) is forced to switch sides. The level of all friendly allies are doubled.} UC {} {32 33} {} 1}
    {AR    5 +8 2 2 0 {Machine of Lum the Mad} {The attached champion can cast any spell, but only in defense; it can never attack. The champion uses the last digit of his card number as his level.} R {} {32 33} {d4 o4 d19 o19} 1}
    {AR    6 {} 2 2 0 {Queen Ehlissa's Marvelous Nightingale} {When the attached champion enters combat, the player can choose to prevent the opposing champion from playing allies or spells.} C {} {32 33} {} 1}
    {AR    7 +8 2 2 0 {Sword of Kas} {The base level of an opposing champion is halved (round up). This artifact does not function when used against a champion with the Eye and Hand of Vecna.} UC Sword. {38 44 32 33} {} 1}
    {AR    8 {} 2 2 0 {Talisman of Al'Akbar} {This artifact can be attached to a champion with the Cup of Al'Akbar. The attached champion can dispel one spell while involved in a round of battle. Monsters cannot use this Talisman.} C {} {32 33} {} 1}
    {AR    9 {} 2 2 0 {Teeth of Dalhvar-Nar} {The attached champion is a flyer and is immune to offensive spells. If the champion wins a round of battle, an opposing holding is immediately discarded.} UC {} {32 33} {} 1}
    {AR   10 {} 2 1 0 {All-Knowing Eye of Yasmin Sira} {The attached champion is immune to offensive spells and once per battle can cast a +5 spell (Def/4). Once per turn, the player can examine one opponent's hand.} R {} {6 32 33} {} 1}
    {AR   11 {} 2 1 0 {Coin of Jisan the Bountiful} {The champion can negate either the power or level (but not both) of each magical item and artifact used against him in combat.} C {} {32 33} {} 1}
    {AR   12 +3 2 3 0 {Seal of Lost Arak} {Once per turn, the player can flip the top card of any other player's draw deck. He can use it only if it is a spell or ally that is legal for that step. The card is reshuffled into the player's draw deck.} R {} {32 33} {} 1}
    {AR   13 +2 2 3 0 {Crystal of the Ebon Flame} {Attached champion becomes undead. The opposing champion's base level is considered to be a zero, unless it is a cleric or undead. Opposing undead allies switch sides.} C {} {32 33} {d102 o102} 1}
    {AR   14 +6 2 4 0 {Obsidian Man of Urik} {If the attached champion is discarded, the artifact returns to the player's pool as a monster. Instead of attaching this artifact to a champion, the player can play the Obsidian Man as a monster.} R {} {32 33} {} 1}
    {AR   15 +2 2 4 0 {Rod of Teeth} {An opposing wizard cannot cast spells. Before battle, the player can discard the attached champion and examine all other players' hands, discarding any spell cards.} UC {} {32 33} {} 1}
    {AR   16 +2 9 0 0 {Midnight's Mask of Disguise} {A champion can be played into the player's pool with this magical item, even if the champion is already in play somewhere. The champion's powers are unchanged. (Def)} C {} {6 32 33} {} 1}
    {AR   17 +7 9 0 0 {Girdle of Storm Giant Strength} (Off) C {} {27 32 33} {} 1}
    {AR   18 +5 9 0 0 {Hammer of Thunderbolts} {Can only be attached to a champion who carries gauntlets of ogre power or a girdle of storm giant strength. The first ally used against the attached champion is discarded. (Off)} R Weapon. {27 44 32 33} {} 1}
    {AR   19 +6 9 0 0 {Gauntlets of Ogre Power} {Champion breaks down walls, allowing him to ignore all such cards. Can be played on a champion even after combat is ended by a wall spell. Combat must continue. (Off)} R {} {27 32 33} {} 1}
    {AR   20 +2 9 0 0 {Winged Boots} {The attached champion becomes a flyer. If he is defeated in battle against a non-flying champion, he can retreat from combat back to his pool. (Def)} C {} {6 32 33} {} 1}
    {AR   21 +1 9 0 0 {Rod of 7 Parts, Part 1} {Champion is a swimmer. If combined with any other parts of the rod, the rod counts as an artifact and gains an additional +1 for each part. (Off)} UC {} {27 32 33} {} 1}
    {AR   22 +2 9 0 0 {Rod of 7 Parts, Part 2} {Champion is immune to events. If combined with any other parts of the rod, the rod counts as an artifact and gains an additional +1 for each part. (Off)} R {} {27 32 33} {} 1}
    {AR   23 +3 9 0 0 {Rod of 7 Parts, Part 3} {Champion is immune to offensive magical items. If combined with any other parts of the rod, the rod counts as an artifact and gains an additional +1 for each part. (Off)} UC {} {27 32 33} {} 1}
    {AR   24 +4 9 0 0 {Rod of 7 Parts, Part 4} {Flyers cannot be played against the attached champion. If combined with any other parts of the rod, the rod counts as an artifact and gains an additional +1 for each part. (Off)} R {} {27 32 33} {} 1}
    {AR   25 +5 9 0 0 {Rod of 7 Parts, Part 5} {At the beginning of his turn, this item's owner can examine an opponent's hand. If combined with any other parts of the rod, the rod counts as an artifact and gains an additional +1 for each part. (Off)} UC {} {27 32 33} {} 1}
    {AR   26 +6 9 0 0 {Rod of 7 Parts, Part 6} {The attached champion becomes an earthwalker. If combined with any other parts of the rod, the rod counts as an artifact and gains an additional +1 for each part. (Off)} R {} {27 32 33} {} 1}
    {AR   27 +7 9 0 0 {Rod of 7 Parts, Part 7} {The champion can ignore one card played against him in combat. If combined with any other parts of the rod, the rod counts as an artifact and gains an additional +1 per part. (Off)} UC {} {27 32 33} {} 1}
    {AR   28 +1 9 0 0 {Bag of Holding} {Once per turn the player may discard one card from his pool or his hand, and then draw one card from his draw pile. (Def)} C {} {6 32 33} {} 1}
    {AR   29 +5 9 0 0 {Daern's Instant Fortress} {The Fortress can be played as a magical item or as a holding. The realm or champion is immune to events and offensive spells during other player's turns. (Def)} R {} {6 32 33} {} 1}
    {AR   30 {} 9 0 0 Spellbook {The spellcaster with this item can retain up to two spells after winning a round of combat to use in another battle. Only step 4 spells can be saved. (Def)} R {} {6 32 33} {} 1}
    {AR   31 {} 15 4 0 {Plentiful Psionics} {Played at the beginning of the player's turn, this card is not discarded. It affects all players and remains in effect until any other rule card is played. All champions are able to read minds and predict the future. Each player's hand is divided: all Dark Sun cards are concealed, but all other cards are revealed by placing them face-up on the table. The face-up cards are still part of the hand until played.} R {} 29 {} 1}
    {AR   32 {} 15 4 0 Sorcerer-Kings {Played at the beginning of the player's turn, this card is not discarded. It affects all players and remains in effect until any other rule card is played. Each Dark Sun realm can be defended once per battle by a sorcerer-king who is a monster that can cast any spell. The sorcerer-king's level is equal to the number of Dark Sun realms and holdings the defender has in play. If the realm already has a defender (on the card), add that defender's level to the sorcerer-king's. If the sorcerer-king is defeated, the realm is razed.} C {} 29 {1 2 d4 o4 d9 o9 d19 o19} 1}
    {AR   33 {} 15 3 0 {Dark Lords} {Played at the beginning of the player's turn, this card is not discarded. It affects all players and remains in effect until any other rule card is played. If any Ravenloft champion or undead champion of any world is defeated in battle, that champion returns to the player's pool at the end of that player's next turn.} C {} 29 {} 1}
    {AR   34 {} 15 3 0 {The Walking Dead} {Played at the beginning of the player's turn, this card is not discarded. It affects all players and remains in effect until any other rule card is played. Undead champions and Ravenloft monsters can attack razed realms. Allies need not be undead. If a razed realm is defeated, it is discarded and the attacker again draws spoils of victory.} UC {} 29 {} 1}
    {AR   35 {} 15 2 0 {Artifact Vault} {Played at the beginning of the player's turn, this card is not discarded. It affects all players and remains in effect until any other rule card is played. The player can choose to place any Greyhawk Artifacts face-down in a pile called the Artifact Vault. In step 3 of the turn, when cards are played into the pool, the player can distribute the Greyhawk artifacts among his Greyhawk champions in the pool. At the end of his turn, the player returns all Greyhawk artifacts to the Artifact Vault. Cards in the vault are in play, but are not active and cannot be used. Greyhawk artifacts cannot be discarded by any means so long as this rule card is in play; if a champion is discarded, or if any card calls for a Greyhawk artifact to be discarded, it returns to the player's Artifact Vault.} R {} 29 {} 1}
    {AR   36 {} 15 2 0 {Artifact Champions} {Played at the beginning of the player's turn, this card is not discarded. It affects all players and remains in effect until any other rule card is played. Greyhawk Artifacts with numerical bonuses can be played as champions. Artifact-champions are not considered monsters, wizards, clerics, or heroes. Any ability normally given by the artifact to a champion is possessed by the artifact-champion.} UC {} 29 {} 1}
    {AR   37 {} 15 4 0 {Isolated Worlds} {Played at the beginning of the player's turn, this card is not discarded. It affects all players and remains in effect until any other rule card is played. Dark Sun cards (champions, artifacts, realms) are immune to the Rule of the Cosmos. If this rule card is discarded, the owner of the card chooses which cards are discarded to enforce the Rule of the Cosmos again.} C {} 29 {} 1}
    {AR   38 {} 15 7 0 {No Funny Business} {Played at the beginning of the player's turn, this card is not discarded. It affects all players and remains in effect until any other rule card is played. No events can be played. All events currently in play are immediately discarded when this rule card is played. In addition, no more than one magical item can be attached to any champion. Extras are discarded when this rule card is played (player's choice). In battle, no more than one of each type of card (ally, magical item, artifact, wizard spell, and clerical spell) can be attached to each champion.} R {} 29 {} 1}
    {AR   39 {} 15 3 0 {Forbidden Lore} {Played at the beginning of the player's turn, this card is not discarded. It affects all players and remains in effect until any other rule card is played. Only Ravenloft champions may cast offensive wizard spells.} C {} 29 {} 1}
    {AR   40 {} 15 7 0 {Cosmic Justice} {Played at the beginning of the player's turn, this card is not discarded. It affects all players and remains in effect until any other rule card is played. All realms that have no special powers can borrow the powers of one realm in play, but only when attacked. All champions that have no special powers can steal the power of the opposing champion in combat. The opponent loses his power. All allies that have no special powers are unaffected by the special powers of champions and allies.} R {} 29 {} 1}
    {AR   41 +8 1 0 0 Roc {Flyer. Flying allies cannot be played against the roc. The opponent must discard any already in play.} C {} {16 33} {} 1}
    {AR   42 +4 1 0 0 {Kinsle the Druid} {Flyer. In battle, Kinsle can cast cleric spells to aid the attached champion.} C {} {16 33} {d4 o4} 1}
    {AR   43 +2 4 0 0 Dragonbane {Any dragon champion is automatically defeated, but returns unharmed to the player's pool. Dragon and draconian allies are discarded. (Off/4)} C {} {27 33} {} 1}
    {AR   44 +4 19 0 0 {The Ship of the Sky} {Remains with the champion until dispelled. Champion and allies become flyers and swimmers. (Def/3/4)} R {} {6 32 33} {} 1}
    {AR   45 +3 1 0 0 Pegasus Flyer. C {} {16 33} {} 1}
    {AR   46 +6 1 0 0 Windrider Flyer. C {} {16 33} {} 1}
    {AR   47 +7 1 0 0 {Erica of the Dark Watch} Flyer. C {} {16 33} {} 1}
    {AR   48 +3 1 0 0 {Dimock the Sprite} {Flyer. Dimock fights invisibly and cannot be discarded or switch sides during battle for any reason.} C {} {16 33} {} 1}
    {AR   49 +3 9 0 0 {Flying Carpet} {The champion can choose to be a flyer or non-flyer at the beginning of combat. (Def)} C {} {6 32 33} {} 1}
    {AR   50 +5 1 0 0 {Ariel Anjelique} {Flyer. Ariel flies psionically and is immune to spells, allies, and events that harm other flyers.} C {} {16 33} {} 1}
    {AR   51 {} 6 0 0 {Dragon Slayer} {All dragons in combat or in pools are immediately discarded.} UC (Harmful) {22 29 30 31 32 33 34} {} 1}
    {AR   52 +7 1 0 0 {Marilith, Tanar'ri} {The opposing player cannot play any events for the rest of this round of battle, including Calm.} C {} 33 {} 1}
    {AR   53 {} 6 0 0 {Temporal Stasis} {In a multi-player game, this card can be played to prevent one player's turn. In a two-player game, this event can prevent an extra turn gained from another card, such as the Caravan.} UC (Harmful) {22 29 30 31 32 33 34} {} 1}
    {AR   54 {} 6 0 0 Deflection {When someone plays an event that affects only you, this card can deflect the effects of that event onto another player, chosen by you.} R (Helpful) {23 29 30 31 32 33 34} {} 1}
    {AR   55 {} 6 0 0 Help! {Choose another player to defend your realm. You choose which champions are used. If he loses a round, his champion is discarded; he draws a card for each round he wins.} R (Harmful) {22 29 30 31 32 33 34} {} 1}
    {AR   56 {} 19 0 0 {Reverse Gravity} {All Flyers become non-flyers and vice versa until the beginning of this player's next turn. Swimmers and earthwalkers are unaffected by this card. (Off/3/4)} UC {} {27 32 33} {} 1}
    {AR   57 {} 4 0 0 {Shift Earth} {The player can freely rearrange his realms and holdings, but must fill from the top down. (Def/3)} C {} {6 32} {} 1}
    {AR   58 {} 19 0 0 {Mirror Image} {This spell doubles the caster's level. (Def/4)} UC {} {6 33} {} 1}
    {AR   59 {} 4 0 0 Ethereality {The champion can immediately elude an opposing cleric or hero, ending the round of battle. Both champions go back to their pools. (Def/4)} C {} {6 33} {} 1}
    {AR   60 +7 19 0 0 {Prismatic Spray} {Opposing allies of level 4 or less are immediately discarded. (Off/4)} C {} {27 33} {} 1}
    {AR   61 {} 8 7 0 {Treasure Vault} {This holding can be attached to any realm. Any artifact of any world can be attached to this holding. Any champion defending the attached realm can use the artifact.} R {} 31 {} 1}
    {AR   62 {} 8 7 0 Tupillil {This holding can be attached to any realm. When this holding is first played, all champions with the name 'Gib' are discarded.} C {} 31 {} 1}
    {AR   63 {} 8 7 0 {Kestrel's Keep} {This holding can be attached to any realm. Each of this player's champions and allies gain +1 when defending any realm. This holding stays attached and in play even if the attached realm is razed.} UC {} 31 {} 1}
    {AR   64 {} 8 7 0 {Keep of the Dead} {This holding can be attached to any realm. If something forces the attached realm to be discarded, this holding is discarded in place of the realm, and the realm stays in play.} C {} 31 {} 1}
    {AR   65 {} 8 7 0 {Spellfire Citadel} {This holding can be attached to any realm. This player can, at the end of each turn, rearrange his holdings. Holdings must still be attached to realms legally.} UC {} 31 {} 1}
    {AR   66 +2 4 0 0 {Fire Glyph} {Hide under the lead realm; expose when the realm is attacked. Only one glyph can be placed under a realm; it is discarded after one use. The attacking champion cannot play allies in this round of battle. (Def/3)} R {} {6 32} {} 1}
    {AR   67 +1 4 0 0 {Weakness Glyph} {Hide under the lead realm; expose when the realm is attacked. Only one glyph can be placed under a realm; it is discarded after one use. The attacking champion's base level is a 1 for this round of battle. (Def/3)} UC {} {6 32} {} 1}
    {AR   68 +4 4 0 0 {Lightning Glyph} {Hide under the lead realm; expose when the realm is attacked. Only one glyph can be placed under a realm; it is discarded after one use. The attacking champion must discard all attached magical items. (Def/3)} R {} {6 32} {} 1}
    {AR   69 +3 4 0 0 {Curse Glyph} {Hide under the lead realm; expose when the realm is attacked. Only one glyph can be placed under a realm; it is discarded after one use. An attacking champion with an attached magical item is defeated. (Def/3)} UC {} {6 32} {} 1}
    {AR   70 +2 4 0 0 {Death Glyph} {Hide under the lead realm; expose when the realm is attacked. Only one glyph can be placed under a realm; it is discarded after one use. An attacking champion without an attached artifact or magical item is defeated. (Def/3)} C {} {6 32} {} 1}
    {AR   71 6 10 5 0 {Dragon Turtle} {Swimmer; can attack any realm that shows coastline on the card.} C {} {8 37 32 33} {1 2 d9 o9 o101 d101} 1}
    {AR   72 7 10 5 0 {Deathstream, Black Dragon} {Flyer, swimmer; can attack any realm that shows coastline on the card. One opponent's magical item is discarded. Deathstream can cast wizard spells.} C {} {8 16 37 32 33} {1 2 d101 o101 d9 o9 d19 o19} 1}
    {AR   73 9 10 2 0 {Zielesch, Ancient Green Dragon} {Swimmer; can attack any realm that shows coastline on the card. When Zielesch enters battle, the player can draw a card. If the card is usable, it can be played; otherwise, the card goes in to the player's hand.} UC Flyer. {8 16 32 33 37} {1 2 d9 o9 o101 d101} 1}
    {AR   74 10 10 4 0 {Dregoth, Undead Dragon-King} {Undead flyer. Can cast any spell. Immune to psionics and offensive spells. If Dregoth attacks, his level drops to 6.} R {} {8 16 40 32 33} {1 2 d4 o4 d101 o101 d9 o9 d102 o102 d19 o19} 1}
    {AR   75 8 10 4 0 {Korgunard the Avangion} {Flyer. Can cast wizard spells. Immune to psionic attack. Can be discarded to rebuild a razed realm.} C {} {16 32 33} {1 2 d9 o9 d19 o19} 1}
    {AR   76 7 20 2 0 Drawmij {Swimmer; can attack any realm that shows coastline on the card. In battle, he can borrow any magical item in play, returning it when the round ends. Drawmij can imitate the power of any other wizard in play.} UC {} {37 32 33} {1 2 d9 o9 d19 o19} 1}
    {AR   77 7 5 4 0 Klik-Ka'cha {When he enters battle as a defender, Klik can destroy one magical item in play anywhere.} C {} {32 33} {1 2 d9 o9 d4 o4} 1}
    {AR   78 10 10 7 0 {Mykell, Amethyst Great Wyrm} {Dragon; flyer, swimmer; can attack any realm that shows coastline on the card. Can cast wizard spells. Mykell psionically destroys any one ally played against him in a round of battle.} C {} {8 16 37 32 33} {1 2 d101 o101 d9 o9 d19 o19} 1}
    {AR   79 6 20 2 0 {Hornung the Anarch} {Each spell cast by Hornung has a level equal to the card number's last digit. Hornung never need ask permission to cast a spell.} C {} {32 33} {1 2 d9 o9 d19 o19} 1}
    {AR   80 4 10 3 0 {Invisible Stalker} {The invisible stalker can also be played as a +4 ally to any champion able to cast spells. If the invisible stalker is on the losing side of a battle, it returns to the player's pool at the end of his next turn.} UC {} {32 33} {1 2 d9 o9} 1}
    {AR   81 7 5 2 0 {Erital Kaan-Ipzirel} {This cleric of St. Cuthbert is immune to offensive spells and magical items. When in battle, she can choose to use a dimension door to return to her pool, ending the round of combat; if she does, all attached cards are discarded} C {} {32 33} {1 2 d9 o9 d4 o4} 1}
    {AR   82 8 5 3 0 {Yagno Petrovna} {When used in combat, this player can place any two cards from his opponent's discard on top of his draw pile.} C {} {32 33} {1 2 d9 o9 d4 o4} 1}
    {AR   83 9 5 5 0 Goldmoon {Once per turn, in any step, she may cast any cleric spell from an opponent's discard pile, and then place it on the top or bottom of his draw pile.} C {} {32 33} {1 2 d9 o9 d4 o4} 1}
    {AR   84 5 7 1 0 {Princess Amber} {Heroes cannot resist helping the princess. When entering battle, Amber can use any hero in play as an ally; after battle, win or lose, the hero returns to its owner's pool.} R Elf. {14 32 33} {1 2 d9 o9 d18 o18} 1}
    {AR   85 7 20 1 0 {Darsson Spellmaker} {When attacking or defending, Darsson can play any card as a defensive spell card, using the last digit of the card number as the spell's level.} C {} {32 33} {1 2 d9 o9 d19 o19} 1}
    {AR   86 9 13 1 0 {Council Aerie} {Dragon champions may defend this realm twice per turn. Opponent's dragons may not attack. Any holding may be attached to Council Aerie.} UC Coast. {5 31} {1 d18 o18} 1}
    {AR   87 {} 13 5 0 {Shining Lands} {The Shining Lands can be attacked only by flyers or earthwalkers. The realm and its defending champions are immune to offensive spells. Any holding can be attached to the Shining Lands.} C {} 31 {} 1}
    {AR   88 6 13 3 0 {Bluet Spur} {Cannot be attacked by flyers and can defend itself as a level 6 monster that can cast wizard spells. Any holding can be attached to Bluet Spur.} UC Coast. {5 31} {1 d19 o19} 1}
    {AR   89 {} 13 2 0 {Hell Furnaces} {The level of any dragon defending the Hell Furnaces is doubled. Any holding can be attached to this realm.} C {} 31 {} 1}
    {AR   90 {} 13 4 0 Euripis {Only champions able to cast spells can attack this realm. Any holding can be attached to Euripis.} C {} 31 {} 1}
    {AR   91 {} 13 4 0 {New Giustenal} {Cannot be attacked by flyers, except Dregoth. If razed, this realm can be rebuilt by discarding only 1 card.} C Coast. {5 31} {} 1}
    {AR   92 {} 13 4 0 {Ancient Kalidnay} {This realm is also considered a Ravenloft realm. This realm can be voluntarily razed by the player at the end of his turn, allowing the player to take another turn immediately.} C {Ancient Kalidinay's power may be used once per game per player.} 31 {} 1}
    {AR   93 {} 13 4 0 {Ur Draxa} {This player's champions are immune to psionic attacks. Champions with attached artifacts or magical items cannot attack this realm, although they can be added during battle.} C {} 31 {} 1}
    {AR   94 6 13 4 0 Shault {Shault can be attacked only by monsters or flyers. The city can defend itself as any type of level 6 champion, chosen by the player when attacked.} C {} 31 {1 d3 o3 d4 o4 d11 o11 d17 o17 d18 o18 d19 o19} 1}
    {AR   95 {} 13 4 0 {The Forest Ridge} {If the Forest Ridge is razed by an attacking champion, feral halflings eat the winning champion, causing the card (and any possessions) to be discarded.} C {} 31 {} 1}
    {AR   96 {} 13 4 0 Celik {Any champion attacking Celik, must discard all attached magical items or artifacts, and cannot add more during battle.} R {} 31 {} 1}
    {AR   97 5 13 4 0 {Lake Island} {Can be attacked only by flyers or earthwalkers. Lake Island defends itself as a level 5 monster.} C {} 31 1 1}
    {AR   98 {} 6 0 0 {Year of Plenty} {No events can be played, including Calm, until the end of this player's next turn.} C (Harmful) {22 29 30 31 32 33 34} {} 1}
    {AR   99 -2 1 0 0 {Thought Eater} {Prevents all special powers and spell casting ability of the opponent's champion, allies, spells, and magical items.} C {Does not affect icon abilities.} 33 {} 1}
    {AR  100 {} 4 0 0 {Deja Vu} {Take any three cards from an opponent's discard pile and place them on top of his draw pile. (Off/3)} UC {} {27 32} {} 1}
    {AR  101 +5 2 2 0 {Mace of Cuthbert} {The level bonus (if any) of each opponent's spell is reduced by 2. Undead cannot be used against the attached champion. The Mace is discarded when the attached champion enters battle against luz.} VR {} {44 32 33} {} 1}
    {AR  102 {} 2 3 0 {Death Rock} {When a champion of this player dies in battle, a champion with this artifact can keep the dead champion as an undead +2 ally without special powers. These allies return to the pool with a winning champion.} VR {} {32 33} {} 1}
    {AR  103 {} 2 4 0 {Psychometron of Nerad} {The attached champion is immune to psionics. When the attached champion is discarded, the Psychometron psionically destroys one other champion.} VR {} {32 33} {} 1}
    {AR  104 +6 2 4 0 {Silencer of Bodach} {If the attached champion is defeated in battle, all of one other player's holdings are discarded. If one of this player's realms is attacked, the attached champion must be used first in defense.} VR {} {38 44 32 33} {} 1}
    {AR  105 +3 2 7 0 {Barab's Goblet of Dissolution} {This artifact can be attached to any champion. When the champion with this item is defeated, the winning champion is sent to the Abyss, permanently removed from play.} VR {} {32 33} {} 1}
    {AR  106 7 20 2 0 {Onad the Weasel} {Onad can imitate the effects of any event by being discarded just after that event is played. The use of Onad in this manner is secondary to the use of the actual event.} VR {} {32 33} {1 2 d9 o9 d19 o19} 1}
    {AR  107 8 7 1 0 {Lord Blacktree} {At the beginning of a battle, Lord Blacktree can imitate the powers of any single realm or holding in play. Only powers usable during a round of battle can be imitated.} VR {} {32 33} {1 2 d9 o9 d18 o18} 1}
    {AR  108 7 7 7 0 {Young Strahd} {Can cast wizard spells. While in play, all Ravenloft champions except Strahd Von Zarovich are turned face down and cannot act. Must defend if Strahd Von Zarovich attacks.} VR {} {32 33} {1 2 d9 o9 d18 o18 d19 o19} 1}
    {AR  109 8 20 7 0 Killian {Immune to offensive spells. This swashbuckler is the captain of a ship; he and his allies are considered swimmers and can attack any coastal realm.} VR {} {32 33 37} {1 2 d9 o9 d19 o19} 1}
    {AR  110 8 10 3 0 {Ghostly Piper} {Undead. This spectral bagpiper can cast wizard spells. He and any attached cards are immune to the special powers of allies.} VR {} {40 32 33} {1 2 d9 o9 d102 o102 d19 o19} 1}
    {AR  111 {} 4 0 0 Forbiddance {No attack can be made against any of this player's realms until after this player's next turn. (Def/5)} VR {} {6 34} {} 1}
    {AR  112 {} 19 0 0 {Bigby's Clenched Fist} {This spell summons a magical fist as a +4 ally. The fist can cause one enemy ally to be discarded. (Off/4)} VR {} {27 33} {} 1}
    {AR  113 {} 19 0 0 {Fire Charm} {The special power of an opposing champion or ally is neutralized until the end of the current battle. (Off/4)} VR {} {27 33} {} 1}
    {AR  114 +4 19 0 0 {Thunder Staff} {When this spell is played, all the opponent's allies are discarded. (Off/4)} VR {} {27 33} {} 1}
    {AR  115 +4 19 0 0 {Spectral Hand} {This spell can be cast by a champion in the pool to aid a champion in battle. After casting it, the champion in the pool can cast other spells into the same round of battle. (Off/4)} VR {} {27 33} {} 1}
    {AR  116 +5 9 0 0 {Ariel's Feather Charm} {The attached champion becomes an agile flyer. The champion is not affected by cards that normally cause harm specifically to flyers. (Def)} VR {} {6 32 33} {} 1}
    {AR  117 +5 9 0 0 {Amulet of Spell Protection} {The attached champion is immune to offensive spells. If this item is in the pool when a spell is cast, the amulet can be discarded to prevent the effects of the spell. (Def)} VR {} {6 32 33} {} 1}
    {AR  118 {} 9 0 0 {Amelior's Restraint} {Before battle, choose one opponent's champion; that champion's special abilities are negated until the end of your turn. (Off)} VR {} {27 32 33} {} 1}
    {AR  119 +5 9 0 0 {Smoke Powder Pistol} {When this card is used in battle, flip one card from the opponent's draw pile. The last digit of that card's number is an additional bonus for the attached champion. (Off)} VR Weapon. {27 44 32 33} {} 1}
    {AR  120 {} 9 0 0 {Dragon Font} {Draw one less card than usual when beginning your turn. In addition, look at the bottom 5 cards in your draw pile. Place one in your hand and return the others to the bottom of the draw pile. (Def)} VR {} {6 32 33} {} 1}
}
