set CrossFire::cardDataBase {
    Birthright
    {BR    1 5 13 6 0 Roesone {Can defend itself as a level 5 hero who can use blood abilities.} C {} 31 {1 d3 o3 d18 o18} 1}
    {BR    2 4 13 6 0 Ilien {Can defend itself as a level 4 wizard. Any champion can cast wizard spells when defending Ilien.} C Coast. {5 31} {1 d19 o19} 1}
    {BR    3 {} 13 6 0 {The Spiderfell} {Before a defender is chosen, the attacking champion must draw and discard a card, noting the last digit of the card number. If it's higher than or equal to his base level, he has been poisoned and is discarded. Combat ends with no spoils.} UC {} 31 {} 1}
    {BR    4 {} 13 6 0 {The Gorgon's Crown} {Defending monsters are doubled in base level and can use blood abilities. This realm is immune to offensive spells and harmful events.} R {} 31 {d3 o3} 1}
    {BR    5 {} 13 6 0 Avanil {f unrazed, may be discarded from the player's formation at any time to draw five cards.} UC {Coast. Discard to the Abyss to draw 5 cards.} {5 20 31} {} 1}
    {BR    6 {} 13 6 0 Ghoere {Any ally may be played in defense of Ghoere as a hero. If successfully defended, the ally remains, acting as a hero champion for future attacks against the realm.} R {} 31 {} 1}
    {BR    7 {} 13 6 0 Tuarhievel {Double the base level of any defending elves (champions and allies). Any champion defending Tuarhievel can cast wizard spells and use blood abilities.} C {} 31 {d3 o3 d19 o19} 1}
    {BR    8 {} 13 6 0 Mur-Kilad {Cannot be attacked by flyers or swimmers. Defending earthwalkers gain 2 levels.} C {} 31 {} 1}
    {BR    9 {} 13 6 0 Baruk-Azhik {Cannot be attacked by flyers. Baruk-Azhik prevents this player's realms from being attacked via the Underdark realms.} R {} 31 {} 1}
    {BR   10 {} 13 6 0 {Impregnable Heart of Haelyn} {Defending champions can cast cleric spells and use blood abilities. Defending clerics are immune to offensive blood abilities.} C Coast. {5 31} {d3 o3 d4 o4} 1}
    {BR   11 {} 13 6 0 {Tower of the Sword Mage} {Cannot be attacked by awnsheghlien. Defending champions can cast wizard spells.} C {} 31 {d19 o19} 1}
    {BR   12 {} 8 6 0 {Imperial City of Anuire} {Draw a card whenever an opposing player plays an event card.} UC {} 31 {} 1}
    {BR   13 {} 8 6 0 {The Heartland Outfitters} {This player's Birthright champions can fly, swim, or earthwalk as needed.} C {} 31 {} 1}
    {BR   14 {} 8 6 0 Proudglaive {The base level of a hero defending the attached realm is doubled or the base level of a defending champion is tripled if he doesn't use allies.} UC {} 31 {} 1}
    {BR   15 {} 8 6 0 Kal-Saitharak {The base level of a defending monster is doubled. Monsters in this player's pool are immune to psionic power cards.} R {} 31 {} 1}
    {BR   16 {} 8 6 0 {Magical Source} {Phase 4 spells cast by champions of this player gain a +4 level bonus.} C {} 31 {} 1}
    {BR   17 {} 8 6 0 {The Maze of Maalvar the Minotaur} {Only flyers or earthwalkers can attack the attached realm.} C {} 31 {} 1}
    {BR   18 {} 6 0 0 Espionage! {Examine another player's draw pile and place four cards of your choice on the top. (Harmful)} C {} {22 29 30 31 32 33 34} {} 1}
    {BR   19 {} 6 0 0 Chaos! {All players (starting with the event player) take turns playing event cards until all event cards in all hands have been played. Events which state they can only be played at certain times (Caravan, Weasel Attack, etc) are played with no effect. (Harmful)} R {} {22 29 30 31 32 33 34} {} 1}
    {BR   20 {} 6 0 0 {Investiture Ceremony} {Play on one champion to allow him to use blood abilities. Lasts until negated or champion is discarded. (Helpful)} C {} {23 29 30 31 32 33 34} {d3 o3} 1}
    {BR   21 {} 6 0 0 {Forge Ley Line} {Negates for this player any champion's immunity to offensive spells until the end of this player's next turn. (Harmful)} R {} {22 29 30 31 32 33 34} {} 1}
    {BR   22 {} 6 0 0 {Biding Your Time} {Player can skip his turn and use it later in the game between any two players' turns. This event remains in play until used or canceled. (Helpful)} UC {} {23 29 30 31 32 33 34} {} 1}
    {BR   23 {} 6 0 0 {In Search of Adventure} {Send one of your champions to Limbo until the beginning of your next turn. When he returns, draw a card from the draw pile and add the last digit of the card number to the champion's base level as a permanent increase. (Helpful)} UC {} {23 29 30 31 32 33 34} {} 1}
    {BR   24 {} 6 0 0 Revolution! {Until the end of this player's next turn, no realm champions may be used to defend. (Harmful)} C {} {22 29 30 31 32 33 34} {} 1}
    {BR   25 {} 6 0 0 {The Kraken Attacks!} {Razes two realms in one player's formation that have coastlines. The kraken can be satisfied (negated) by discarding champions totaling 8 levels or more from hand or pool. (Harmful)} R {} {22 29 30 31 32 33 34} {} 1}
    {BR   26 {} 9 0 0 {Crown of Regency} {When the attached champion is used in defense, the crown copies the powers of any holding in play for the defending realm. (Def)} C {} {6 32 33} {} 1}
    {BR   27 +4 9 0 0 {Armor of the High King} {During phase 3, the attached champion can retrieve one blood ability card from his discard pile to his hand. (Def)} C {} {6 32 33} {} 1}
    {BR   28 +? 9 0 0 {Dragon's Teeth} {Draw and discard a card each time the Teeth are used in battle, noting the last digit of the card's number. For that round, the attached champion gains an undead ally equal to that digit. (Def)} C {} {6 32 33} {} 1}
    {BR   29 {} 9 0 0 {Bracers of Brachiation} {Allows the attached champion and his allies to attack any realm showing trees, regardless of position or special powers. (Def)} C {} {6 32 33} {} 1}
    {BR   30 {} 9 0 0 {Ring of Human Influence} {Heroes cannot defend against the attached champion. (Off)} UC {} {27 32 33} {} 1}
    {BR   31 {} 9 0 0 {Ring of Spell Storing} {Up to three spells playable in phase 4 may be stored in this item, remaining until used or dispelled. These spells may be cast during any battle, including combat where this champion is not involved. New spells may be attached during phase 3 only. (Def)} R {} {6 32 33} {} 1}
    {BR   32 +4 9 0 0 {Rod of Lordly Might} {Can only be attached to heroes. This champion and attached allies are considered flyers. Allies of level 5 and lower cannot be used against this hero. (Off)} C {} {27 32 33} {} 1}
    {BR   33 {} 9 0 0 {Amulet of Plane Walking} {The attached champion and its allies may attack any realm, regardless of position or special powers, ignoring the effect of an attached holding. (Def)} C {} {6 32 33} {} 1}
    {BR   34 +3 9 0 0 {Cloak of Displacement} {The attached champion can attack twice if he wins on his first round, but doesn't raze a realm. He uses new allies. (Def)} UC {} {6 32 33} {} 1}
    {BR   35 +2 3 6 0 Alertness {Blood ability. This champion can use his special power first when defending. Alertness lasts until the end of this player's next turn and can be dispelled. (Def/3/4)} UC {} {6 32 33} {} 1}
    {BR   36 {} 3 6 0 {Animal Affinity} {Blood ability. Creates a +4 ally which remains with the user until he is defeated. This ally cannot be forced to switch sides for any reason. (Def/3/4)} C {} {6 32 33} {} 1}
    {BR   37 {} 3 6 0 Battlewise {Blood ability. Double the affected champion's current total level until the end of this player's next turn. Can be dispelled. (Off/3/4)} R (Def) {6 32 33} {} 1}
    {BR   38 {} 3 0 0 Courage {Blood ability. Allies of this champion cannot be discarded during battle or made to switch sides. (Off/3/4)} C (Def) {6 32 33} {} 1}
    {BR   39 +6 3 6 0 {Divine Wrath} {Blood ability. All opposing allies are instantly discarded. No new allies can be played against this champion. Lasts until the end of this player's next turn. (Off/4)} C {} {27 33} {} 1}
    {BR   40 {} 3 6 0 Regeneration {Blood ability. The attached champion is not discarded when defeated in battle; instead it goes to Limbo until the end of this player's next turn, when it returns to its pool. (Def/4)} UC {} {6 33} {} 1}
    {BR   41 {} 3 6 0 {Touch of Decay} {Blood ability. Examine an opponent's hand and pool. Discard one magical item or artifact from either one. (Off/3/4)} UC {} {27 32 33} {} 1}
    {BR   42 {} 3 6 0 {Unreadable Thoughts} {Blood ability. This champion is immune to the effects of offensive psionic power cards and the special powers of psionicists. Play anytime to negate the effects of any just played psionic power card. (Off/3/4)} C (Def) {6 32 33} {} 1}
    {BR   43 +5 3 6 0 {Death Touch} {Blood ability. Opposing champion must draw a card from his draw pile and note the last digit of the card number. If it is equal to or greater than his base level, he is instantly discarded. Can be dispelled. (Off/4)} R {} {27 33} {} 1}
    {BR   44 {} 3 6 0 {Detect Life} {Blood ability. An opponent must display his hand for this round of combat. (Def/4)} C {} {6 33} {} 1}
    {BR   45 {} 3 6 0 Invulnerability {Blood ability. This champion ignores the special powers of offensive magical items of less than +4 enchantment or cancels one offensive blood ability card. (Def/4)} UC {} {6 33} {} 1}
    {BR   46 +4 2 7 0 {Tighmaevril Sword} {The attached champion can use blood abilities and instantly defeats regent.} R {} {38 44 32 33} {d3 o3} 1}
    {BR   47 +3 2 6 0 Wintering {The attached champion is immune to either the special power of a champion or the special powers of his allies. The choice must be made at the start of the player's turn and remains the same until his next turn.} R {} {32 33} {} 1}
    {BR   48 +5 2 6 0 {Emperor's Crown of Anuire} {No Birthright champions can attack this player's realms or cast offensive spells against those realms.} R {} {32 33} {} 1}
    {BR   49 +5 2 6 0 Kingstopper {Protects the attached champion and all monsters in this player's pool from harmful events.} R {} {32 33} {} 1}
    {BR   50 {} 4 0 0 {Bless Land} {All realm champions are doubled in level and are immune to the special powers of allies until the end of this player's turn. (Def/3/4)} UC {} {6 32 33} {} 1}
    {BR   51 {} 4 0 0 Blight {All realms, artifacts, and holdings that grant extra cards are negated while this spell is in play, which lasts until dispelled. (Off/3)} C {} {27 32} {} 1}
    {BR   52 {} 4 0 0 Investiture {Cast at any time. Discard a regent champion from your pool to transfer the power to use blood abilities to another champion. (Def)} C {} {6 29 30 31 32 33 34} {d3 o3} 1}
    {BR   53 {} 4 0 0 {Control Weather} {No flyers or swimmers can be involved in combat until the end of this player's next turn without this player's permission. (Off/3/4/5)} UC {} {27 32 33 34} {} 1}
    {BR   54 {} 4 0 0 {Transmute Metal to Wood} {Destroy one magical item or artifact in any player's pool. (Off/3)} C {} {27 32} {} 1}
    {BR   55 {} 4 0 0 {Part Water} {This player's champions and allies can attack any realm showing a coastline until the end of this turn. (Def/3)} C {} {6 32} {} 1}
    {BR   56 {} 4 0 0 {Speak with Monsters} {Instantly ends a battle with a monster. Both champions return to their pools. No spoils of victory are drawn. (Off/4)} C {} {27 33} {} 1}
    {BR   57 {} 4 0 0 {Summon Insects} {Creates a +7 ally for the caster that devours (discards) one opposing ally. (Off/4)} C {} {27 33} {} 1}
    {BR   58 +? 19 0 0 {Legion of Dead} {Creates an undead monster equal to the adjusted level of the casting champion. The spell acts as a champion and may attack or defend, lasting until the end of this player's next turn. Attachments may be added normally, though are discarded when the spell ends. (Off/3)} UC {} {27 32} {} 1}
    {BR   59 {} 19 0 0 Raze {This spell razes an opponent's realm that has no attached holding, chosen by this player. The caster is immediately discarded. (Off/3/4)} R {} {27 32 33} {} 1}
    {BR   60 {} 19 0 0 {Blood Drain} {The affected champion can no longer use blood abilities. Lasts until dispelled. (Off/3/4)} C {} {27 32 33} {} 1}
    {BR   61 {} 19 0 0 {Otto's Irresistible Dance} {Cast on any enemy champion in a pool; he cannot attack or defend until the Dance is dispelled. (Off/3)} C {} {27 32} {} 1}
    {BR   62 {} 19 0 0 Clone {Cast at any time to allow this player to bring a champion currently in play elsewhere into this player's pool. The champion's powers are unchanged. (Def)} R {} {6 29 30 31 32 33 34} {} 1}
    {BR   63 {} 19 0 0 {Drawmij's Instant Summons} {Take any ally, magical item, or artifact from your draw pile and play it immediately. Reshuffle the draw pile. (Def/3/4)} UC {} {6 32 33} {} 1}
    {BR   64 10 10 6 0 {The Gorgon} {Awnshegh. Can use blood abilities and wizard spells. This creature is so horrible that no allies can be played against him. Immune to harmful events.} R {} {2 32 33} {1 2 d3 o3 d9 o9 d19 o19} 1}
    {BR   65 8 10 6 0 {The Spider} {Awnshegh. Can use blood abilities. Immune to offensive cleric spells. The Spider can attack a razed realm. If victorious, the realm is discarded.} UC {Realm is discarded whether defended or not.} {2 32 33} {1 2 d3 o3 d9 o9} 1}
    {BR   66 5 10 6 0 Banshegh {Awnshegh. Between 6 PM and 6 AM the Banshegh is a level 10 monster that can use blood abilities. Between 6 AM and 6 PM the Banshegh is a level 5 wizard capable of also casting cleric spells. In either form the Banshegh is immune to offensive spells.} R {} {2 32 33} {1 2 d3 o3 d4 o4 d9 o9 d19 o19} 1}
    {BR   67 5 10 6 0 {The Lamia} {Awnshegh. Immune to psionics. Can use blood abilities. Wizards and clerics are at half their base level (rounded down) against the Lamia.} R {} {2 32 33} {1 2 d3 o3 d9 o9} 1}
    {BR   68 9 10 6 0 {The Siren} {Swimmer. Awnshegh. Can use blood abilities. Can be sent to Limbo to force another player to attack this player's formation. The Siren is returned at the end of this player's next turn.} R {} {2 37 32 33} {1 2 d3 o3 d9 o9} 1}
    {BR   69 7 10 6 0 {The White Witch} {Awnshegh. Immune to offensive spells and harmful events except those that have the word "fire," "flame," or "flaming" in the title.} C {} {2 32 33} {1 2 d9 o9} 1}
    {BR   70 4 10 6 0 {The Hag} {Awnshegh. Can cast wizard spells. Immune to psionics. If defeated in combat the Hag can "curse" an opposing player, forcing him to discard a holding in play.} UC {} {2 32 33} {1 2 d9 o9 d19 o19} 1}
    {BR   71 10 10 6 0 {Cerilian Dragon} {Flyer. Can cast cleric spells. When attacking, the Cerilian Dragon may use its breath weapon to destroy any holding in the defender's formation.} UC {} {8 16 32 33} {1 2 d4 o4 d101 o101 d9 o9} 1}
    {BR   72 {} 15 6 0 {The Shadow World} {Played at the beginning of the player's turn, this card is not discarded. It affects all players and remains in effect until any other rule card is played. If defeated in combat, all halfling champions and allies can dimension door away, returning to their player's hand instead of being discarded.} C {} 29 {} 1}
    {BR   73 {} 15 6 0 {Divine Right} {Played at the beginning of the player's turn, this card is not discarded. It affects all players and remains in effect until any other rule card is played. All heroes in play may use blood ability cards.} C {} 29 {d3 o3} 1}
    {BR   74 +2 1 0 0 Orogs {Orogs are +4 when attacking and/or +6 if attached to an awnshegh.} C Orc. {28 33} {} 1}
    {BR   75 +4 1 0 0 {Green Slime} {The Green Slime destroys the first magical item or ally played after it enters battle.} R {} 33 {} 1}
    {BR   76 +4 1 0 0 Nightmare {Flyer. The Nightmare becomes +8 vs. clerics or wizards.} C {} {16 33} {} 1}
    {BR   77 +6 1 0 0 Unicorn {The attached champion can cast wizard or cleric spells.} C {} 33 {d4 o4 d19 o19} 1}
    {BR   78 +4 1 0 0 Wraith {Flyer. Undead. Reduces an opposing champion's base level by 2. If the reduced base level is 0 or less, the champion is discarded.} UC {} {16 40 33} {o102 d102} 1}
    {BR   79 +? 1 0 0 {Stirge Swarm} {Flyer. Draw and discard a card from any opponent's draw pile when the Stirge Swarm is played, noting the last digit of the card number, which is the bonus for this ally.} R {} {16 33} {} 1}
    {BR   80 +7 1 0 0 Ankheg {Earthwalker. Destroys one opposing nonflying ally.} C Flyer. {13 16 33} {} 1}
    {BR   81 +3 1 0 0 {Wood Nymph} {The Wood Nymph becomes +6 if defending a realm showing trees.} C {} 33 {} 1}
    {BR   82 +8 1 0 0 {Giant Squid} {Swimmer. Instantly destroys (discards) any opposing Brine Dragons, ignoring their special power.} UC {} {37 33} {} 1}
    {BR   83 9 14 6 0 {Lord Cronal} {Can use blood abilities and hero unarmed combat cards. Inspires confidence in all allies played with him, who each gain 2 levels.} C {} {32 33} {1 2 d3 o3 d9 o9 d18 o18} 1}
    {BR   84 6 14 6 0 {Grimm Graybeard} {Dwarf. Earthwalker. Can use blood abilities and can cast cleric spells. Immune to offensive magical items of less than +2 enchantment.} C {} {12 13 32 33} {1 2 d3 o3 d4 o4 d9 o9} 1}
    {BR   85 7 14 6 0 {Teodor Profiev} {Can use blood abilities. Gains 5 levels against monsters.} C {} {32 33} {1 2 d9 o9 d3 o3} 1}
    {BR   86 8 14 6 0 {Darien Avan} {Can use blood abilities and hero unarmed combat cards. Can attack twice; if he wins his first round and doesn't raze a realm, he can attack again, retaining one of his allies from the previous round of battle.} R {} {32 33} {1 2 d3 o3 d9 o9 d18 o18} 1}
    {BR   87 8 14 6 0 {Caliedhe Dosiere} {Can use blood abilities. When attacking, he can cast cleric spells; when defending, he can cast wizard spells.} C {} {32 33} {1 2 d3 o3 d4 o4 d9 o9 d19 o19} 1}
    {BR   88 6 14 6 0 {Tomkin Dross} {Halfling. Can use blood abilities. Tomkin and his allies may attack any realm in play, regardless of position or special power.} C {} {21 32 33} {1 2 d9 o9 d3 o3} 1}
    {BR   89 7 14 6 0 {The Elf Prince Fhileraene} {Elf. Can use blood abilities and cast wizard spells. When attacking, he can call upon his archers to destroy (discard) a monster in a player's pool, once per battle.} R {} {14 32 33} {1 2 d3 o3 d9 o9 d19 o19} 1}
    {BR   90 3 14 6 0 {Tie'skar Graecher the Goblin King} {Can use blood abilities. He can "borrow" one monster from any pool to act as an ally. If defeated, the monster ally is stripped of attachments and returned.} C {} {32 33} {1 2 d9 o9 d3 o3} 1}
    {BR   91 10 14 6 0 {The Noble Outlaw} {Can use blood abilities and hero unarmed combat cards. Once per turn, he can prevent a player from receiving a spoils of victory, giving it to a third player instead. (In a two-player game, no one collects spoils.)} R {} {32 33} {1 2 d3 o3 d9 o9 d18 o18} 1}
    {BR   92 6 14 6 0 {High Mage Aelies} {Elf. Can use blood abilities and cast wizard spells. Gains +2 to his base level for every unrazed Birthright realm in play.} UC {} {14 32 33} {1 2 d3 o3 d9 o9 d19 o19} 1}
    {BR   93 7 14 6 0 {The Sword Mage} {Can use blood abilities and cast wizard spells. Gains 4 levels if spells are used against him.} C {} {32 33} {1 2 d3 o3 d9 o9 d19 o19} 1}
    {BR   94 5 14 6 0 {The Wizard} {Can use blood abilities and cast wizard spells. The Wizard can discard a realm in his player's formation to instantly win a round of battle.} UC {} {32 33} {1 2 d3 o3 d9 o9 d19 o19} 1}
    {BR   95 9 14 6 0 {Nadia Vasily} {Can use blood abilities and cast cleric spells. Clerics facing Nadia are at half their base level (rounded down).} C {} {32 33} {1 2 d3 o3 d4 o4 d9 o9} 1}
    {BR   96 6 14 6 0 Moergan {Can use blood abilities and cast cleric spells. Once per any battle, Moergan can summon rains that force flying allies from the sky. They are discarded instantly.} C {} {32 33} {1 2 d3 o3 d4 o4 d9 o9} 1}
    {BR   97 7 14 6 0 {Barak the Dark} {Can use blood abilities and cast cleric spells. Gains 3 levels if using a magical item weapon; gains 2 levels if allies are used against him.} C {} {32 33} {1 2 d3 o3 d4 o4 d9 o9} 1}
    {BR   98 2 14 6 0 {Jana Orel} {Can use blood abilities and cast cleric spells. Immune to offensive cleric spells. If Jana is to receive a spoils, this player can look at the top two cards in his draw pile and choose the one he wants.} UC {} {32 33} {1 2 d3 o3 d4 o4 d9 o9} 1}
    {BR   99 6 7 6 0 {The Flower of Roesone} {This foppish fighter tends to be underestimated in combat. Allies played against him lose 3 levels. Allies may have negative levels.} C {} {32 33} {1 2 d9 o9 d18 o18} 1}
    {BR  100 3 7 6 0 {Gwenyth the Bard} {Elf. Gwenyth's music is so enchanting she can prevent a champion in another pool from attacking her player's formation. The music lasts until the start of this player's next turn, at which time she can select a different champion to be affected.} UC {} {14 32 33} {1 2 d9 o9 d18 o18} 1}
    {BR  101 {} 6 0 0 {It's Good to Be the King} {Until the beginning of his next turn, this event player chooses which champions are able to attack. Even if negated, all players must still address the event player as "Sir" or "Madam." (Harmful)} VR {} {22 29 30 31 32 33 34} {} 1}
    {BR  102 {} 6 0 0 {The Shadow World} {Until the end of this player's next turn, all undead are immune to offensive spells, magical items, and events that specifically target undead or monsters. (Helpful)} VR {} {23 29 30 31 32 33 34} {} 1}
    {BR  103 {} 6 0 0 {Forced Conscription} {All players must donate an ally to the event player's side in battle, if they have one. All allies are discarded at the end of combat. (Harmful)} VR {} {22 29 30 31 32 33 34} {} 1}
    {BR  104 +5 9 0 0 {Sphere of Annihilation} {Opposing champions defeated by the attached champion are sent to the Abyss instead of being discarded. (Off)} VR {} {27 32 33} {} 1}
    {BR  105 {} 9 0 0 {Vacuous Grimoire} {If the attached champion is defeated by a champion able to cast spells, the book is attached to that champion, subtracting 5 from his base level. If the base level is now 0 or less, the champion is discarded. (Off)} VR {} {27 32 33} {} 1}
    {BR  106 +5 9 0 0 {Manual of Puissant Skill at Arms} {The attached hero may make an extra attack if he win his first round and doesn't raze a realm. (Def)} VR {} {6 32 33} {} 1}
    {BR  107 +4 9 0 0 {Book of Infinite Spells} {The attached champion can cast wizard and cleric spells. Phase 4 spells cast by the attached champion cannot be dispelled. (Def)} VR {} {6 32 33} {d4 o4 d19 o19} 1}
    {BR  108 +10 9 0 0 {Libram of Ineffable Damnation} {Can only be attached to a wizard, who is now immune to offensive spells. If defeated in combat, this champion is sent to the Abyss. (Def)} VR {} {6 32 33} {} 1}
    {BR  109 8 14 6 0 {The Count of Müden} {Swimmer. Can use blood abilities and psionic power cards. The Count controls the most powerful navy in Cerilia. All attached swimming allies of this champion are doubled in level.} VR {} {37 32 33} {1 2 d3 o3 d9 o9 d11 o11} 1}
    {BR  110 4 14 6 0 {The Wizardess Carrie} {Can use blood abilities and cast wizard spells. Carrie can summon a djinni to aid her in battle, which acts as a +8 flying ally.} VR {} {32 33} {1 2 d3 o3 d9 o9 d19 o19} 1}
    {BR  111 7 14 6 0 {The Pontifex of the Southern Coast} {Can use blood abilities and cast cleric spells. The Pontifex can be discarded in phase 5 to call for a crusade against another player. Until the end of this player's next turn, all clerics in pools must attack that player, if possible.} VR {} {32 33} {1 2 d3 o3 d4 o4 d9 o9} 1}
    {BR  112 3 14 6 0 {Olaf the Sly} {Can use blood abilities and hero unarmed combat cards. In combat, Olaf can "borrow" any magical item in play. At the end of the battle the item can be discarded or returned to the player; if returned, this player draws one card.} VR {} {32 33} {1 2 d3 o3 d9 o9 d18 o18} 1}
    {BR  113 4 14 6 0 {Targoth the Unclean} {Can use blood abilities and cast wizard spells. All noncleric champions are halved in base level (rounded down) against Targoth.} VR {} {32 33} {1 2 d3 o3 d9 o9 d19 o19} 1}
    {BR  114 8 14 6 0 {Rhuobhe Manslayer} {Elf. Awnshegh. Can use blood abilities and cast wizard spells. When attacking, Rhuobhe can imitate the special power of any champion in any pool. Gains 4 levels against nonmonster champions.} VR {} {2 14 32 33} {1 2 d3 o3 d9 o9 d19 o19} 1}
    {BR  115 6 14 6 0 {Kaeriaen Whiteheart} {Can use blood abilities and cast cleric spells. Gains 5 levels vs. awnswegh.} VR {} {32 33} {1 2 d3 o3 d4 o4 d9 o9} 1}
    {BR  116 4 14 6 0 {Adara Addlepate} {Can use blood abilities and can cast wizard spells. Adara can instantly defeat any champion with the "# of 25" (chase cards), but must then be discarded herself.} VR {} {32 33} {1 2 d3 o3 d9 o9 d19 o19} 1}
    {BR  117 {} 6 0 0 {The Blood of Azrai} {Adds 5 levels to any monster and makes it an awnshegh, who can now use blood abilities. The event lasts until negated or the champion is discarded. (Helpful)} VR {} {23 29 30 31 32 33 34} {1 2 d3 o3 d9 o9} 1}
    {BR  118 {} 15 6 0 Taxation {Played at the beginning of the player's turn, this card is not discarded. It affects all players and remains in effect until any other rule card is played. Instead of drawing three cards at the beginning of a turn, each player draws one card and a card for each unrazed Birthright realm in his formation. A minimum of one card is drawn; nothing can reduce the draw below one.} VR {} 29 {} 1}
    {BR  119 {} 6 0 0 Diplomacy {Playable only when first being attacked, the event player requests that the attacker attack someone else's realm instead. If he chooses to ignore the event, he must discard two cards from his hand to continue his initial attack. (Harmful)} VR {} {22 29 30 31 32 33 34} {} 1}
    {BR  120 {} 6 0 0 {Blood Challenge!} {Play at any time to make an attack directly against a champion in any pool. Combat lasts for one round, and the loser is discarded. The winner receives a spoils of victory, even though no realm was razed. (Harmful)} VR {} {22 29 30 31 32 33 34} {} 1}
    {BR  121 {} 6 0 0 Festival {No combat can occur until the start of this player's next turn. Each player draws a card when this event is played. (Harmful)} VR {} {22 29 30 31 32 33 34} {} 1}
    {BR  122 {} 6 0 0 {Child's Play} {Subtract the age of the youngest player from the age of the oldest player in the game. That number is counted as a bonus to your side in this round of combat. (Helpful)} VR {} {23 29 30 31 32 33 34} {} 1}
    {BR  123 {} 6 0 0 {The Fates} {Each player draws and discards a card, noting its last digit. If it's even, lose that many cards from your hand, pool, or formation. If it's odd, draw that many cards. (Harmful)} VR {} {22 29 30 31 32 33 34} {} 1}
    {BR  124 {} 6 0 0 {War Declared!} {Until the end of this player's next turn, all players must attack on their turn if they have champions in their pools. All champions and allies can fly, swim, or earthwalk as needed. (Harmful)} VR {} {22 29 30 31 32 33 34} {} 1}
    {BR  125 {} 6 0 0 {Mebhaigl Surge} {All players may return their defensive spells from their discard piles to their hand. (Helpful)} VR {} {23 29 30 31 32 33 34} {} 1}
}
