set CrossFire::cardDataBase {
    Chaos
    {CH    1 9 5 7 0 {Aonia Sunblaze} {Can use hero unarmed combat cards.  Immune to unarmed combat cards useable only by undead and the 'Negative Planar Energies' rule card.  May not use undead allies and is discarded if in a pool with undead champions.} C {} {32 33} {1 2 d4 o4 d9 o9 d18 o18} 1}
    {CH    2 5 5 3 0 {Dark Cleric} {Can use Undead Unarmed Combat cards.  Every turn that this champion doesn't attack, his player may return one undead/werebeast champion from his discard pile to his draw pile which is then reshuffled.  Gains 5 levels if played from 6PM to 6AM.} C {} {32 33} {1 2 d4 o4 d9 o9 d102 o102} 1}
    {CH    3 6 12 7 0 Beastmaster {When in combat, the Beastmaster may summon an ally chosen at random from an opponent's hand.  This ally can not be forced to switch sides or discarded.} C {} {32 33} {1 2 d9 o9 d11 o11} 1}
    {CH    4 6 12 5 0 {Murtha the Gypsy} {Immune to all thief skills.  While in a pool, negates the effects of Necba the Wrathmaker, Poor Oriental Lord, and Wealthy Oriental Vassal for all players.} C {} {32 33} {1 2 d9 o9 d11 o11} 1}
    {CH    5 7 14 6 0 {Gib Cram} {This player's champions and attached cards are immune to the special powers and abilities of realms and realm champions.} C {} {32 33} {1 2 d3 o3 d9 o9} 1}
    {CH    6 10 7 7 0 {Gib Thiaf} {May use any support card.  May use Dragonlance artifacts.  When in combat, her attachments activate first, regardless if attacking or defending.} C {} {32 33} {1 2 d3 o3 d4 o4 d101 o101 d9 o9 d11 o11 d17 o17 d18 o18 d102 o102 d19 o19} 1}
    {CH    7 5 7 7 0 Pirate {Swimmer.  Can use thief skills.  During phase 3 the pirate may send all magic items and artifacts attached to any one champion in play to Limbo.  The attachments are returned to the champion the next time he enters battle.} C {} {37 32 33} {1 2 d9 o9 d17 o17 d18 o18} 1}
    {CH    8 13 7 7 1 {Footlong, Avatar of the Mimic} {Avatar.  A Spoon, Knife (Sword) and Fork; must be discarded to bring this avatar into play.  While this avatar is in play all players must attack on their turns or discard their lowest level champion in play.} C {} 32 {1 2 d9 o9 d18 o18} 1}
    {CH    9 4 7 7 0 {The Brewmaster} {Dwarf.  In phase 0, this champion may either recover one magic item with the words 'oil' or 'potion' in the title from the discard pile, or take one such card from his deck, and play it immediately upon himself.} C {} {12 32 33} {1 2 d9 o9 d18 o18} 1}
    {CH   10 14 7 1 1 {Tyr, Avatar of Justice} {Avatar.  Two heroes must be discarded to bring Tyr into play.  This player and all of his cards are immune to all offensive thief skills.  All champions in play can only be sent to the abyss through combat.  Limit one avatar per pool.} C {} 32 {1 2 d9 o9 d18 o18} 1}
    {CH   11 5 7 7 0 {Cai, Amateur Dragonslayer} {Cai's bravado amuses dragons of base level 6 or higher.  Before combat, the opponent rolls 1d10.  On a roll of 3 or less, the dragon returns to his pool laughing hysterically.  The battle can continue with new champions.} C {} {32 33} {1 2 d9 o9 d102 o102} 1}
    {CH   12 5 20 4 0 {The Chronomancer} {Players must ask the Chronomancer permission to get extra turns.  Once you take a free turn or deny a free turn, at the beginning of your next phase 3, choose an opponent.  The player immediately gains control of the Chronomancer as if it was their champion.} C {} {32 33} {1 2 d9 o9 d19 o19} 1}
    {CH   13 8 20 3 0 Marius {Undead. Elf. Vampire.  Any opposing champion defeated by Marius becomes undead vampire champion, with no special powers, under the control of this player.  May kill one opposing ally during a combat where she is involved.} C {} {14 40 43 32 33} {1 2 d9 o9 d102 o102 d19 o19} 1}
    {CH   14 10 10 3 0 {Shadow Drake} {Dragon, flyer, earthwalker.  Immune to harmful events.  This champion and his allies may attack any Underdark realm regardless of position or restrictions.  Shadowdrake gains 5 levels when facing an Underdark champion.} C {} {8 32 33} {1 2 d9 o9} 1}
    {CH   15 20 10 2 1 Hextor {Avatar.  Two Greyhawk monsters must be discarded to bring Hextor into play.  While in the pool Hextor doubles the level of all monsters of this player and makes them immune to offensive spells.} C {} 32 {1 2 d9 o9} 1}
    {CH   16 3 10 2 0 {Tummbutt, the Faerie Dragon} {Tummbutt can be sent to Limbo at any time, allowing this player to rearrange all attachments in any one players pool.  All attachments still must be legally attached.  Tummbutt returns to the pool at the end of his player's next turn.} C Flyer. {8 16 32 33} {1 2 d101 o101 d9 o9} 1}
    {CH   17 4 10 7 0 Doppelganger {At the start of each turn and/or before combat, this champion can become any type of champion (regent, hero, theif, etc.).  Immune to offensive cards usable by his current champion type.} C {} {32 33} {1 2 d9 o9} 1}
    {CH   18 5 10 6 0 {The Warmonger} {Can use hero unarmed combat cards.  Every time this champion has an ally card played with him in battle, this player may draw a card.  This champion gains 2 levels for each ally currently in play.} C {} {32 33} {1 2 d9 o9 d18 o18} 1}
    {CH   19 18 10 2 1 {Avatar of Osprem} {Avatar.  Discard 12 levels of swimming champions to bring the Avatar of Osprem into play.  All champions and allies of this player become swimmers, and receive +4 to their base levels when attacking.  When attacking coastal realms, one oposing ally may be discarded per battle.  This player's champions are not affected by card powers that target swimmers.} C Swimmer. {32 37} {1 2 d9 o9} 1}
    {CH   20 3 10 7 0 {Lurker Above} {Can only defend.  Attackers mistake the Lurker Above for the ceiling and are surprised.  The opponent rolls 1d10.  If the die roll is greater than attacker's base level, the attacker is discarded.  The Lurker Above is immune to cards that specifically harm monsters.} C {} {32 33} {1 2 d9 o9} 1}
    {CH   21 +1 1 0 0 Piranhas {Hide this ally under a realm indicating water and reveal when an attack occurs.  The opponenet rolls 1d6.  If the number is even the attacking champion and piranhas are discarded.  The piranhas cannot be discarded through combat by any means, and remains with the realm until its power is successful.} C Swimmer. {32 37} {} 1}
    {CH   22 +2 1 0 0 Henchman {Once played, this ally remains with the attached champion.  Any number of magic items and artifacts may be attached to the ally regardless of any restrictions (Rule of Cosmos, world, race, etc.).  If discarded, all cards with the same name as card on the Henchman are discarded also.} C {} 33 2 1}
    {CH   23 +6 1 0 0 {Servants of Faith} {Can cast priest spells.  May be attached to a cleric during phase 3.  While attached to a cleric, that champion's base level is doubled.  This ally cannot be forced to change sides during combat, and returns with the cleric in a victorious combat.} C Flyer {16 32 33} {} 1}
    {CH   24 +9 1 0 0 {Chain Master} {When played, immediately discards all allies of level 5 or higher.  While the chain master is in play, no further allies may be played.} C {} 33 {} 1}
    {CH   25 {} 4 0 0 Divination {Castable at anytime.  Search your draw pile for any rule card.  Put that card into play then discard the casting champion and this spell to the abyss.} C {} {29 30 31 32 33 34} {} 1}
    {CH   26 +8 4 0 0 Chant {Castable only by Clerics.  The champion is immune to offensive magical item and spells.  If the caster win a round of battle, the spell may be used by each champion for the duration of the combat.  The spell is then reshuffled into the draw pile.  If the cleric loses the round, the spell is sent ot the abyss.  (Def/4)} C {} {6 33} {} 1}
    {CH   27 +2 18 0 0 Watahh! {Playable at any time during combat, this player can choose to discard any 2 cards of the opposing player's force (excluding the champion), or to deflect the special power of any just played card back at the opposing player's force before it activates.  (Off)} C {} {27 33} {} 1}
    {CH   28 {} 11 0 0 {Know What You Are Hiding!!!} {While this power is in play, all players must keep all pools face up regardless of immunities.  This power lasts until dispelled.  (Off 3)} C {} {27 32} {} 1}
    {CH   29 {} 3 6 0 {Curse of the Wolves Blood} {Play on any non-Werebeast champion, who now becomes a Werewolf immune to magical items of less thatn +4 enchantment.  However, the attached champion must attack every turn or be discarded regardless of special powers.  (Off 3)} C {} {27 32} {} 1}
    {CH   30 {} 9 0 0 {Oil of Impact} {All other attached weapons that are magic items and artifacts are tripled in icon bonus.  (Def)} C {} {6 32 33} {} 1}
    {CH   31 -4 9 0 0 {Oil of Fumbling} {Attach to any champion in any pool.  The attached champion discards all other magic items and artifacts currently attached to him, and may not attach any more until Oil is removed.  May be dispelled by any dispel spell.  (Off)} C {} {27 32} {} 1}
    {CH   32 {} 9 0 0 {Oil of Disenchantment} {Discard from any pool to the Abyss to send any magic item to the abyss, or any artifact to the discard pile.  (Off)} C {} {27 32 33} {} 1}
    {CH   33 +1 9 0 0 {Potion of Alter Self} {Discard from the attached champion at any time to make the attached champion a flyer; or swimmer; or earthwalker; or may change champion type.  The potion's effect last for 1d4 turns.} C Def {6 32 33} {} 1}
    {CH   34 {} 9 0 0 Nectar {Discard to the abyss during your phase 3 to give your champion +1d6 levels and can only be killed in combat by an opponent's actions.  If the same champion discards Ambrosia to the abyss, your champion cannot be discarded from your pool by any means and becomes an avatar.  Limit one avatar per pool.} C {} {32 33} {} 1}
    {CH   35 {} 9 0 0 Ambrosia {Discard to the abyss during your phase 3 to give your champion +1d6 levels and can only be killed in combat by an opponent's actions.  If the same champion discards Nectar to the abyss, your champion cannot be discarded from your pool by any means and becomes an avatar.  Limit one avatar per pool.} C {} {32 33} {} 1}
    {CH   36 {} 9 0 0 {Potion of ESP} {When discarded from the pool, opponents must then play with their hands face up for 1d4 turns OR send the potion to the Abyss to discard one card from each opponent's hand.  (Off)} C {} {27 32 33} {} 1}
    {CH   37 {} 9 0 0 {Potion of Heroism} {When discarded from battle, the champion gains 3d4 levels until the end of the current turn.} C {} {6 32 33} {} 1}
    {CH   38 +2 9 0 0 {Potion of Invulnerability} {May be discarded from attached champion at any time to make this champion immune to offensive magic items and artifacts for 1d4 turns.} C {} {6 32 33} {} 1}
    {CH   39 {} 9 0 0 {Potion of Undead Control} {May be discarded from battle to summon any undead champion from any pool as an ally.  If the champion is defeated or discarded, then the undead champion goes to the owner's discard pile.} C {} {27 32 33} {} 1}
    {CH   40 {} 9 0 0 {Potion of Super-Heroism} {May be only used by Heros.  When discarded from battle, this hero gains 5d6 levels and is immune to offensive unarmed combat cards until the end of the current turn.} C {} {6 32 33} {} 1}
    {CH   41 {} 9 0 0 {Potion of Glibness} {When discarded from combat, retrieve any one thief skill from the discard pile directly into combat.  (Def/4)} C {} {6 32 33} {} 1}
    {CH   42 {} 9 0 0 {Potion of Healing} {When discarded from battle, any non-undead, non-werebeast ally in the discard pile or Abyss may be immediately played into battle.  (Def)} C {} {6 32 33} {} 1}
    {CH   43 +2 9 0 0 {Loaf of Smiting} {Weapon.  Negates the icon bonus of 1 offensive magic item used by an opponent.  Roll 2d10.  If either die comes up with a 0, the champion is knocked out and placed under the attacked realm.  If doubles are rolled, the loaf breaks and is immediately discarded.  If 00 is rolled, the champion is sent to the abyss.  Knocked out champions return to their pools when the realm is razed of discarded.  (off)} C {} {27 32 33} {} 1}
    {CH   44 {} 9 0 0 {Badge of Honor} {The attached champion is considered an adventurer for the purpose of card play.  (def).} C {} {6 32 33} {} 1}
    {CH   45 +5 9 0 0 {Fork of Defense} {This charmed eating utensil allows a defender to block the use of any sword.  Their bonuses are negated as well as any powers they have.  (def)} C {} {6 32 33} {} 1}
    {CH   46 -2 9 0 0 {Bag of Devouring} {This bag may be sent to the void from the hand or pool at any time to send all other "bags" in play to the abyss, regardless of immunities.  (Def)} C {} {6 29 30 31 32 33 34} {} 1}
    {CH   47 +1 2 7 0 {Metal Detector} {Can only be attached to any champion of base level 5 or less.  Once per turn, this artifact can be used to move a card from the discard pile, chosen at random, to the owner's deck.  The deck is then shuffled.} C {} {32 33} {} 1}
    {CH   48 +6 2 7 0 {Blackjammer's Cutlass} {May be attached to a champion from any world.  This champion is now considered worldless, but gets the world bonus in any combat over a realm.  While in combat, this champion is immune to artifacts attached to a champion from a world different from its own.} C {} {32 33} {} 1}
    {CH   49 {} 6 0 0 {Nuclear Free Zone} {All spell, psionic power and event cards that can discard realms are sent to the Abyss from all hands, discards, and draw piles, regardless of an immunity or special power.  Each player may then draw a card for each card sent to the Abyss.  This event may only be negated, it cannont be calmed by individual players.  (Harmful)} C {} {22 29 30 31 32 33 34} {} 1}
    {CH   50 {} 6 0 0 {Shapeshifters Invade!} {Until the end of this player's next turn, all players can ignore the Rule of Cosmos in regard to champions.  All duplicate champions in play when this event expires fight their "duplicate" to see which champion stays in play.  (Helpful)} C {} {23 29 30 31 32 33 34} {} 1}
    {CH   51 {} 6 0 0 {Planar Refugee} {Target champion has his world designation changed to the event player's choice.  Lasts until negated or discarded.  (Harmful)} C {} {22 29 30 31 32 33 34} {} 1}
    {CH   52 {} 6 0 0 {Spanish Inquisition} {All champions able to cast cleric spells are sent to limbo until the end of their owner's next turn.  (Harmful)} C {} {22 29 30 31 32 33 34} {} 1}
    {CH   53 {} 6 0 0 {Black Jack} {Play during a round of battle.  Each player plays 21, discarding a card from the top of the draw pile and tallying the last digit for each card 'dealt'.  They may 'hit' as many times as desired.  The player closest to 21 (with out going over) wins the battle, all cards are discarded regardless of game play.  If both player's tie the battle is over with no victor, all cards are still discarded.  (Harmful)} C {} {22 29 30 31 32 33 34} {} 1}
    {CH   54 {} 6 0 0 {False Sense of Security} {Roll 1d4.  All immunities are canceled, including immunities to events, for that many turns.  This event may only be negated, it cannot be calmed by individual players.  (Harmful)} C {} {22 29 30 31 32 33 34} {} 1}
    {CH   55 {} 6 0 0 {Burned at the Stake} {Play on any champion that does not have an icon ability to cast (i.e., Hero, Monster, etc.) just after they cast a spell.  That champion is sent to the abyss or the player may discard three cards, at random, from hand to save the champion.} C {} {22 29 30 31 32 33 34} {} 1}
    {CH   56 {} 15 7 0 {High Tide} {Played at the beginning of this player's turn, this card is not discarded.  It affects all players and remains in effect until another rule card is played.  All swimmers can attack any realm regardless of position or restiction.  All swimmers gain +3 to their base levels.} C {} 29 {} 1}
    {CH   57 {} 15 7 0 {Welcome to the Dojo} {Played at the beginning of this player's turn, this card is not discarded.  It affects all players and remains in effect until another rule card is played.  This card is immune to events and the wish spell.  Unarmed combat cards are reshuffled into the draw pile after use.} C {} 29 {} 1}
    {CH   58 {} 15 7 0 {Keep it on the Battlefield} {Played at the beginning of this player's turn, this card is not discarded.  It affects all players and remains in effect until another rule card is played.  The Weasel Attack! Event cannot be played.  Cards in play but not in battle cannot affect a battle.  Cards involved in battle can only affect other cards in the battle.  Powers that take effect after a battle has ended can only target the cards that were involved in the battle, the attacked realm, or the players involved.} C {} 29 {} 1}
    {CH   59 {} 15 7 0 Logistics {Played at the beginning of this player's turn, this card is not discarded.  It affects all players and remains in effect until another rule card is played.  While this rule card is in play, realms which place restrictions on attacking card types or force cards to be discarded to attack now have these conditions placed on defenders instead.} C {} 29 {} 1}
    {CH   60 {} 15 7 0 {Rain of Colorless Fire} {Played at the beginning of this player's turn, this card is not discarded.  It affects all players and remains in effect until another rule card is played.  All events, spells, and psionic powers that cause the razing/discarding of realms outside of combat now come with a cost.  To play the spell, event, or psionic power card, a card of the same type must also be discarded from hand.  If the player can not discard a card of the same type, the initial card can not be played.} C {} 29 {} 1}
    {CH   61 {} 15 7 0 {Speed Kills} {Played at the beginning of this player's turn, this card is not discarded.  It affects all players and remains in effect until another rule card is played.  When a player draws the last card of their deck, the discard pile is NOT reshuffled to make a new draw pile.  The special powers of all cards that return or reshuffles cards from the discard pile to the draw pile are negated.} C {} 29 {} 1}
    {CH   62 {} 21 7 0 {King of Nothing} {All of this player's blood abilities gain an additional bonus equal to the current numbr of cards this player's hand.} C {} {} {} 1}
    {CH   63 {} 21 7 0 {Cloud Giants Castle} {This players Giants may attack any realm, regardless of position or restriction.} C {} {} {} 1}
    {CH   64 {} 21 7 0 {Playing Fair} {This player can play any card from any set/series regardless of any card that an opponent has in play that prohibits said cards from being played.  If this dungeon leaves play, any cards that prohibit card play are sent to the abyss.} C {} {} {} 1}
    {CH   65 {} 21 7 0 {Raistlin's Library} {Whenever this player casts any spell roll 1d10.  On a roll of 1-4, the spell may not be turned or retargeted.  On a roll of 5-8, the spell may not be dispelled.  On a 9-0, the spell is retargeted at a legal target that this player owns.} C {} {} {} 1}
    {CH   66 {} 21 7 0 {The Pack} {All of this player's champions are afflicted with lycanthropy and are considered were-beasts who are immune to offensive magical items of less than +4 enchantment, while this dungeon is in play.} C {} {} {} 1}
    {CH   67 {} 13 7 0 {Amish Nick's Farm} {One holding of each world may be attached to this realm.  If this realm is razed or discarded all attached holdings are reshuffled into their player's draw pile.} C {} 31 {} 1}
    {CH   68 {} 13 7 0 {Picque Moi} {Underdark.  This realm may have any holding attached and must be the first targeted in the formation by cards played outside of combat.} C {} {42 31} {} 1}
    {CH   69 {} 13 5 0 {The Desolation} {Attacking champions lose 4 base levels.  If this realm is razed or discarded, no spoils of victory are drawn for it.} C {} 31 {} 1}
    {CH   70 {} 8 7 0 {Mountain Lookout Tower} {May only be attached to a realm showing mountains from any world.  Any flyer defending the attached realm has their attachments activate first during combat, and may play one card into combat first, regardless of who is currently winning the battle.} C {} 31 {} 1}
    {CH   71 5 8 3 0 Darkmoon {Each attacking champion must roll 2d10.  If doubles are rolled, the attacking champion is discarded, if not the champion attacks normally.  Can defend the realm as a level 5 monster champion (dragon).} C {} {8 31} {1 2 d101 o101 d9 o9} 1}
    {CH   72 {} 8 7 0 {Not So Fast} {This card cannot be included in a deck that includes The Caravan or Good Fortune.  May be discarded from hand or formation when an opponent attempts to draw extra cards (other than spoils), rebuild a realm, or attempts to take an extra turn.  If discarded in this manner, counter that action.} C {} 31 {} 1}
}
