set CrossFire::cardDataBase {
    Conquest
    {CQ    1 +8 1 0 0 {Glass Golem} {Counts as a magic item.  All spells cast at this golem (and the attached champion) are reflected back at the caster.  If defeated in combat, it shatters, sending the victorious champion to the discard pile.  If defeated in combat as an ally, it returns to pool as a level 8 monster champion.} C {} {19 33} {} 1}
    {CQ    2 +6 1 0 0 {Stone Golem} {Counts as a magic item.  Earthwalker.  Immune to offensive spells.  If defeated in combat, all spells in all discard piles are sent to the Abyss.  If defeated in combat as an ally, returns to pool as a level 6 monter.} C {} {13 19 33} {} 1}
    {CQ    3 +5 1 0 0 {Wood Golem} {Counts as a magic item.  Swimmer.  Immune to blood abilities and thief skills.  If defeated in combat, all artifacts in play are sent to the discard pile.  If defeated in combat as an ally, returns to pool as a level 5 monster.} C {} {19 37 33} {} 1}
    {CQ    4 +6 1 0 0 {Sand Golem} {Earthwalker.  Counts as a magic item.  Immune to magic items of less than +6 enchantment.  If defeated, all magic items in play are sent to the Abyss.  If defeated in combat as an ally, returns to pool as a level 6 monster.} C {} {13 19 33} {} 1}
    {CQ    5 +5 1 0 0 {Coral Golem} {Counts as a magic item.  Swimmer.  In combat, discards any one opposing swimming ally.  If defeated in combat, attachments on all non-swimming champions are discarded.  If defeated as an ally, returns to pool as a level 5 monster.} C {} {19 37 33} {} 1}
    {CQ    6 +4 1 0 0 {Bone Golem} {Counts as a magic item.  Immune to the power of undead champions.  If defeated in combat, all undead champions and allies in all discard piles go to the Abyss.  If defeated as an ally, returns to pool as a level 4 undead monster.} C {} {19 33} {} 1}
    {CQ    7 {} 4 0 0 {Corruption of the Soul} {Castable only by clerics.  The corruption runs so deep that the targeted non-avatar champion loses their immunity to offensive spells and is sent to the Abyss.  The casting cleric is sent to limbo for 1d6 turns.  (Off/3/4)} C {} {27 32 33} {} 1}
    {CQ    8 {} 4 0 0 {Earth to Earth} {Castable only by a cleric.  If cast immediately after a realm is razed or discarded, the realm remains in the formation, unrazed.  The casting cleric is then sent to the Abyss.  (Def)} C {} {6 29 30 31 32 33 34} {} 1}
    {CQ    9 {} 19 0 0 {Extension II} {Can be cast only during combat to make a phase 4 spell without a duration last for that entire phase 4.  All of this player's champions involved during the combat gain the level bonus and special powers of the extended spell immediately upon entering battle.  (Def/4)} C {} {6 33} {} 1}
    {CQ   10 +3 19 0 0 {Burning Hands} {Fire spell.  The opposing champion has his hands burned, preventing him from casting spells and using thief skills.  Stays with opposing champion until champion is discarded or this spell is dispelled.  (Off/4)} C {} {27 33} {} 1}
    {CQ   11 {} 19 0 0 {Delayed Fireball} {Cast at a player's pool.  When that player reaches Phase 5 of his next turn, roll 2d6.  All champions of less than the rolled level are sent to the discard pile.  (Off/3/4)} C {} {27 32 33} {} 1}
    {CQ   12 {} 17 0 0 Tampering {Playable only after a champion activates a magic item to use its effects during phase 3.  Instead of working, the champion and the magic item are sent to the Abyss regardless of card play and immunities. (Off)} C {} {27 32} {} 1}
    {CQ   13 {} 17 0 0 {False Arrest} {Can be used by any champion.  Arrest (send to limbo) any champion who has at least one attachment for 2d6 turns.   At the start that player's turn, the player may pay a fine (discard all attachments) to return to their pool. (Off)} C {} {27 32} {} 1}
    {CQ   14 {} 17 0 0 Assassination! {Usable only by a thief.  No champion is safe (immune) from Assassination!  Discard any one champion in play and the thief using Assassination! (Off/3)} C {} {27 32} {} 1}
    {CQ   15 {} 17 0 0 Bribe {Play when a champion attacks this player. The attacking player may choose to continue the attack, or place the top 3 cards of his draw pile off to the side and put them into his hand during the NEXT phase 0 and immediately move to phase 5. (Def)} C {} {6 33} {} 1}
    {CQ   16 {} 17 0 0 Framed! {Play only when one of your champions is targeted by any action by an opponent.  Choose another champion in any player's pool, that champion is now the target of the action, and is affected regardless of special abilities or immunities. (Def)} C {} {6 29 30 31 32 33 34} {} 1}
    {CQ   17 {} 11 0 0 Raise! {Can only be played during another player's phase 0. This power can rebuild a razed realm, but the realm cannot be used to win the game during the turn it was played.  The using champion cannot attack or defend realms until the end this player's next turn. (Def)} C {} {6 29} {} 1}
    {CQ   18 {} 11 0 0 {Destroy Thought} {Play this card after an attack is declared one of your realms.  The attacking champion returns to the pool and cannot attack or defend until this power is dispelled. (Off)} C {} {27 33} {} 1}
    {CQ   19 {} 11 0 0 Domination {Play on a champion in an opposing player's pool and place that champion into your pool. The affected champion may not act while this power is in play. (Off/3)} C {} {27 32} {} 1}
    {CQ   20 {} 18 0 0 {Finishing Move} {Useable by any champion.  Play only if you have just won a round of combat.  You may continue to play cards into the battle.  If at any time your champion's level is at least double that of the opposing champion, you may send the opposing champion (and all attached cards) to the Abyss (regardless of special powers) and draw a card. (Off/4)} C {} {27 33} {} 1}
    {CQ   21 {} 18 0 0 Thwap! {May only be played by a giant with an attached magic item or artifact.  The opposing champion is squished into goo, going directly to the Abyss. (Off/4)} C {} {27 33} {} 1}
    {CQ   22 {} 18 0 0 {Concussing Blow} {Raises this champion's adjusted level to one greater than the level of the opposing champion. If  played immediately after 'Ambush' (152/4th), both cards are shuffled back  into the player's draw pile after battle instead of being discarded. (Def/4)} C {} {6 33} {} 1}
    {CQ   23 {} 18 0 0 Humiliation {Play on any champion in play.  They are so humiliated that they hide under any realm in that player's formation.  He cannot take any action.  He is the first to defend this realm and is brought back into play, if victorious.  If the realm is razed/discarded, outside of combat, he returns to the pool. (Off/3)} C {} {27 32} {} 1}
    {CQ   24 {} 3 6 0 {Blood of Azhul} {The user may attack again until the realm is razed as long as each previous round of the battle was a victory for the user.  (Def/3/4)} C {} {6 32 33} {} 1}
    {CQ   25 +4 9 0 0 {Gatekeeper's Lost Foon} {Counts as a spoon and a fork.  While in play, cards cannot leave the Abyss. (Def)} C {} {6 32 33} {} 1}
    {CQ   26 +5 9 0 0 {Kinetic Armor} {Not usable by thieves or wizards.  Turns offensive unarmed combat cards back at the user.  Can be played in combat to turn a just played unarmed combat card. (Def)} C {} {6 32 33} {} 1}
    {CQ   27 +4 9 0 0 {Mace of Blood Drain} {+8 if used by any undead. May be attached at any time to a champion to absorb any blood ability as it is played.  The blood ability is then put under this card and its bonus is added to the mace. (Off)} C {} {27 32 33} {} 1}
    {CQ   28 +6 2 7 0 {The Apocalypse Stone} {Can only be attached to any realm. If this realm is razed or discarded outside of combat by another player, 1d4 of the opposing player's realms are instantly razed.} C {} {32 33} {} 1}
    {CQ   29 {} 21 4 0 {Palace of the Battle Lord} {In combat, this player's heroes can only be defeated by total levels or cards that cause the battle to end without a victor.} C {} {} {} 1}
    {CQ   30 {} 21 6 0 {All Hail the King!} {In combat, this player's heroes and regents are doubled in base level and cannot be stripped of their special powers by any other card.} C {} {} {} 1}
    {CQ   31 {} 21 7 0 {The Adventure Path} {All of this player's adventurers can use thief skills and any unarmed combat card.} C {} {} {} 1}
    {CQ   32 {} 15 7 0 {The Sands of Time Freeze} {Played at the beginning of the player's turn, this card is not discarded. It affects all players and remains in effect until any other rule card is played. All cards (except rule cards) with a stated duration cannot be played, any already in play when this rule card is played are discarded regardless of any circumstances.} C {} 29 {} 1}
    {CQ   33 {} 15 7 0 {Unified Universe} {Played at the beginning of this player's turn, this card is not discarded. It affects all players and remains in effect until another rule card is played.  The world designation of all cards in play is changed to AD&D.} C {} 29 {} 1}
    {CQ   34 {} 15 7 0 {The Grim Harvest} {Played at the beginning of this player's turn, this card is not discarded.  It affects all players and remains in effect until another rule card is played.  All players must attack on their turn or discard a card from their pool.  All realms can be attacked, regardless of position, restrictions, or holdings.  Champions defeated in battle go to the Abyss.} C {} 29 {} 1}
    {CQ   35 {} 15 7 0 {What Madness is This ?!} {Played at the beginning of this player's turn, this card is not discarded.  It affects all players and remains in effect until another rule card is played.  This rule card is immune to events and the Wish spell.   Phases 0-5 of each player's turn are now played in reverse order.  When first played, the player's phase becomes phase 5.} C {} 29 {} 1}
    {CQ   36 {} 15 7 0 {Cannon Fodder} {Played at the beginning of this player's turn, this card is not discarded.  It affects all players and remains in effect until another rule card is played.  Only the lowest adjusted level champion eligible for combat may be used in battle.} C {} 29 {} 1}
    {CQ   37 {} 15 7 0 {Blessed are the Meek} {Played at the beginning of this player's turn, this card is not discarded.  It affects all players and remains in effect until another rule card is played.  While in play, all champions have their base level changed to 10 minus their printed base level.} C {} 29 {} 1}
    {CQ   38 {} 6 0 0 {Sheriff's in Town} {No thief skills maybe played for 1d4 turns. (Harmful)} C {} {22 29 30 31 32 33 34} {} 1}
    {CQ   39 {} 6 0 0 {Breath of Death} {The player of this event rolls 3d10.  Every player must discard at least that many levels of champions from their pool. (Harmful)} C {} {22 29 30 31 32 33 34} {} 1}
    {CQ   40 {} 6 0 0 {Underground Railroad} {All of this player's allies are considered earthwalkers until the end of this player's next turn. (Helpful)} C {} {23 29 30 31 32 33 34} {} 1}
    {CQ   41 {} 6 0 0 {Double Up} {Play immediately after a card that calls for a dice roll. All players who are rolling dice must now roll 2 times, and add the totals together (1d4 becomes 2d4, etc.). (Helpful/Harmful)} C {} {22 23 29 30 31 32 33 34} {} 1}
    {CQ   42 {} 6 0 0 {Tag Team} {This player can now assist any player currently in combat as if it were their phase 4. If played during their own combat, the player may use any champion in any pool as an ally who is reshuffled into their owner's draw pile at the end of combat. (Harmful)} C {} {22 29 30 31 32 33 34} {} 1}
    {CQ   43 {} 6 0 0 {Tactical Retreat} {This player's champion retreats, leading the opposing champion into an ambush. Battle starts over retaining only allies, magical items, and artifacts. This player can then discard any one card attached to the opposing champion. (Harmful)} C {} {22 29 30 31 32 33 34} {} 1}
    {CQ   44 6 7 2 0 {Romeis Gianthammer} {Giants in combat with Romeis are discarded. If Romeis and Tergoz Tenhammer are in play, all Greyhawk champions are immune to the special powers of opposing non-Greyhawk champions.} C {} {32 33} {1 2 d9 o9 d18 o18} 1}
    {CQ   45 13 7 9 0 {Dungeon Master} {When in pool, the controlling player has their dungeon put into limbo until the Dungeon Master leaves his pool.  While in play all players must ask the dungeon master permission to use the powers of their dungeons.} C {} {32 33} {1 2 d9 o9 d18 o18} 1}
    {CQ   46 7 7 1 0 {Gib Occav} {Can cast wizard spells, immune to harmful events. When in combat, Gib Occav can use any one legally playable card from any discard pile. The card, when discarded, is reshuffled back into its owners draw pile.} C {Card from discard pile (even if it's a Magic Item or Artifact) is discarded (and reshuffled) at the end of the round.} {32 33} {1 2 d9 o9 d18 o18 d19 o19} 1}
    {CQ   47 10 7 4 0 {Ecneps the Bounty Hunter} {Can use psionic power cards. During any battle that  Ecneps is winning (before the opponent can play another card), he can choose to end the battle. He then escorts the opposing champion to jail (both champions go to limbo) for 1d4 turns. Combat can continue with new champions.} C {} {32 33} {1 2 d9 o9 d11 o11 d18 o18} 1}
    {CQ   48 8 7 1 0 {Gib Igoy} {While in play, all players must skip phase 3 of their turns.  When first played, this player's phase 3 ends.} C {} {32 33} {1 2 d9 o9 d18 o18} 1}
    {CQ   49 3 7 5 0 Weredragon {Werebeast. Between 6 PM and 6 AM, this champion becomes a level 10 flying dragon monster who is immune to all cards with no icon bonus.} C {} {45 32 33} {1 2 d9 o9 d18 o18} 1}
    {CQ   50 5 7 9 0 Hero {Immune to the Rule of the Cosmos. If this champion is to be sent to the discard pile or Abyss through any means other than losing combat, place into limbo instead.  This champion returns at the beginning of the player's next turn.} C {} {32 33} {1 2 d9 o9 d18 o18} 1}
    {CQ   51 9 14 6 0 Krijeydif {Can use any unarmed combat card. Only blood abilities and unarmed combat cards that have an icon bonus can be played against Krijeydif.} C {} {32 33} {1 2 d3 o3 d9 o9 d18 o18} 1}
    {CQ   52 7 14 9 0 Regent {Immune to the Rule of the Cosmos. If this champion is to be sent to the discard pile or Abyss through any means other than losing combat, place into limbo instead.  This champion returns at the beginning of the player's next turn.} C {} {32 33} {1 2 d3 o3 d9 o9} 1}
    {CQ   53 9 14 6 0 {Gib Suan} {Being a control freak, all players must ask Gib Suan permission to begin their turn (the turn cannot be prevented by this permission).  If they don't ask, this player may send any champion in that players pool to limbo.} C {} {32 33} {1 2 d3 o3 d9 o9} 1}
    {CQ   54 6 5 2 0 {Gib Remuab, the Chase Hunter} {Elf. Immune to harmful events.  All chase cards and the Wealthy Oriental Vassal lose their special powers.} C {} {14 32 33} {1 2 d4 o4 d9 o9} 1}
    {CQ   55 2 5 1 0 {Lady Marie} {Flyer.  While in play, all players may have up to 3 avatars per pool, regardless of restrictions.  If she leaves play, players must discard any extra avatars.} C {} {16 32 33} {1 2 d4 o4 d9 o9} 1}
    {CQ   56 5 5 9 0 Cleric {Immune to the Rule of the Cosmos. If this champion is to be sent to the discard pile or Abyss through any means other than losing combat, place into limbo instead.  This champion returns at the beginning of the player's next turn.} C {} {32 33} {} 1}
    {CQ   57 2 16 5 0 {Son of Tasslehoff} {Halfling (Kender).  Magic items attached to this champion may not be discarded, even by this player.  Tasslehoff Burrfoot must attach items from the discard pile to his son instead of himself, even if he is in another pool.} C {} {21 24 32 33} {1 2 d9 o9 d17 o17} 1}
    {CQ   58 5 16 9 0 Thief {Immune to the Rule of the Cosmos. If this champion is to be sent to the discard pile or Abyss through any means other than losing combat, place into limbo instead.  This champion returns at the beginning of the player's next turn.} C {} {32 33} {1 2 d9 o9 d17 o17} 1}
    {CQ   59 8 16 5 0 {Gib Sinned} {While this champion remains in play, Menzo, Caer Allison, and Ancient Kalidnay do not count as realms for the purpose of victory.} C {} {32 33} {1 2 d9 o9 d17 o17} 1}
    {CQ   60 9 16 6 0 Pawnmaster {Once per turn, this player may place a card from hand into the Abyss to negate the special power of a champion in play until the beginning of this player's next turn.} C {} {32 33} {1 2 d9 o9 d17 o17} 1}
    {CQ   61 6 20 5 0 Dalamar {Elf. Wizard of the Black Robes. Gains 3 levels between the 7pm and 5am.  When played, this player may go through his draw pile and retrieve and play Mordenkainen and/or Elminster.} C {} {4 14 32 33} {1 2 d9 o9 d19 o19} 1}
    {CQ   62 5 20 9 0 Wizard {Immune to the Rule of the Cosmos. If this champion is to be sent to the discard pile or Abyss through any means other than losing combat, place into limbo instead.  This champion returns at the beginning of the player's next turn.} C {} {32 33} {1 2 d9 o9 d19 o19} 1}
    {CQ   63 ? 10 3 0 {Zakhata, the False God} {Zakhata's base level is equal to the total levels of avatars in play. Avatars have no power as long as Zakhata remains in play.} C {} {32 33} {1 2 d9 o9} 1}
    {CQ   64 6 12 4 0 {Mistress of Destruction} {If this champion razes a realm in phase 4, she may psionically raze an additional realm anywhere in play instead of drawing spoils.} C {} {32 33} {1 2 d9 o9 d11 o11} 1}
    {CQ   65 5 12 9 0 Psionicist {Immune to the Rule of the Cosmos. If this champion is to be sent to the discard pile or Abyss through any means other than losing combat, place into limbo instead.  This champion returns at the beginning of the player's next turn.} C {} {32 33} {1 2 d9 o9 d11 o11} 1}
    {CQ   66 {} 13 9 0 Realm {Immune to the rule of the cosmos.  Cannot be discarded from formation outside of phase 4.} C {} 31 {} 1}
    {CQ   67 {} 13 5 0 Blode {Cannot be attacked by swimmers.  Defenders of Blode fight with such tenacity that opposing allies less than +3 can not be played.  One defending ally (even if stolen) of this player's choice remains with this realm.} C {} 31 {} 1}
    {CQ   68 {} 13 5 0 Tanith {Cannot be attacked by earthwalkers.  Tanith's defenders are immune to the special powers of heros and allies} C {} 31 {} 1}
    {CQ   69 {} 13 7 0 {The Mad Scientist's Secret Lab} {Golem champions may defend this realm twice before being discarded. When this realm first comes into play, this player may either search his deck for any golem card, show it to all players and put it into hand, or shuffle all golems from his discard pile back into his deck.} C {} 31 {} 1}
    {CQ   70 12 13 7 0 Elysium {Can defend itself as a level 12 hero, which can use cleric spells and blood abilities. If this realm is attacked, the defeated champion goes to limbo.  If this realm is razed, it cannot be rebuilt, it goes to the Void and no other player can put Elysium in play again this game.} C {} 31 {1 d18 o18} 1}
    {CQ   71 13 13 7 0 Gehenna {Can defend itself as a level 13 monster, which can use wizard spells and thief skills. If this realm is attacked, the defeated champion is sent to the Abyss. If this realm is razed, it cannot be rebuilt, it goes to the Void and no other player can put Gehenna in play again this game.} C {} 31 1 1}
    {CQ   72 {} 13 7 0 {The Shackled City} {Can defend itself as a level 7 hero. After a successful defense of this realm, one enemy ally, chosen by the defending player, remains with the realm. It is used in the next defense of this realm, and it discarded afterwards.} C {} 31 {1 d18 o18} 1}
    {CQ   73 +7 13 3 0 {Castle Strahd} {Cannot be attacked by flyers or clerics. This realm strips any special movement requirements (swimmers, flyers, etc.) from any realm that this players Ravenloft champions or allies attack. Undead vampire bat allies help to defend this realm each round it is attacked.} C {} 31 {} 1}
    {CQ   74 {} 13 7 0 {Front Lines} {Front Lines must be placed as the lead realm, replacing the current lead realm whether razed or not. Can only be discarded during any phase 4. While this realm is in play this player may have a 2nd phase 4 if a spoils of victory is gained by razing a realm during the 1st phase 4.} C {} 31 {} 1}
    {CQ   75 {} 13 1 0 {Maerimydra, City of the Spider Queen} {Underdark. Can only be attacked by earthwalkers, Forgotten Realms champions, or Underdark champions. Champions defending this realm may use cleric spells.} C {} {42 31} {} 1}
    {CQ   76 {} 13 1 0 {The Frozen Forest} {The bitter cold emanates from this realm, stripping all champions in play of any protection granted by the special powers of realms.} C {} 31 {} 1}
    {CQ   77 {} 13 1 0 {The Wetwoods} {The swamps of the Wetwoods keep their dead.  Defeated champions and allies go to the Abyss.  Attached magic items and artifacts remain with the realm to be used by the next defender and discarded if the realm is razed or discarded.} C {} 31 {} 1}
    {CQ   78 {} 13 4 0 {The Black-Isle} {Cannot be attacked by flyers.  The look-outs of the Black-Isle can see attackers from great distances thus the defenders special powers always activate first.} C {} 31 {} 1}
    {CQ   79 {} 13 4 0 Narchek {Narchek is immune to offensive spells.  Narchek may be razed to retarget any just played psionic power card to any legal target in play.} C {} 31 {} 1}
    {CQ   80 {} 8 7 0 {Civil War} {This holding may be attached to any realm in any player's formation. The attached realm loses all powers while this holding is attached.  Defenders of the attached realm subtract 2 from their base level. Allies cannot be used in defense of this realm.} C {} 31 {} 1}
    {CQ   81 {} 8 7 0 {Mercenary's Guild} {May be attached to any realm.  If any of this player's champions wins a round of combat while attacking, that player may reveal the top card of his/her draw pile.  If it is a champion or ally, it may be taken into hand, otherwise it is placed at the bottom of the deck.} C {} 31 {} 1}
}
