set CrossFire::cardDataBase {
    Draconomicon
    {DR    1 {} 13 1 0 {Rauglothgor's Lair} {Any nondragon champions attacking this realm are at half their base level (rounded down). Undead defending this dragon's lair are immune to harmful events.} C {} 31 {} 1}
    {DR    2 {} 13 7 0 {Dragon Mountain} {Can only be attacked by flyers or earthwalkers. Infryana the Dragon's base level is doubled when defending this realm.} C {} 31 {} 1}
    {DR    3 {} 13 7 0 {Lair of the Shadowdrake} {If Menzoberranzan is in play when this realm is played, Menzo is discarded. While this realm is in play, the Underdark allies gained by the Triumvirate realms are negated.} R {} 31 {} 1}
    {DR    4 6 13 1 0 {Dragonspine Mountains} {Dragons defending this realm are immune to offensive spells, psionics, and blood abilities. This realm can defend itself as a level 6 dragon champion.} R Coast. {5 8 31} {1 d101 o101} 1}
    {DR    5 {} 13 2 0 {Griff Mountains} {Defending dragons and giants are doubled in base level and are immune to offensive magical items. Attacking champions and allies that are not flyers lose their special powers.} C Coast. {5 31} {} 1}
    {DR    6 {} 13 2 0 {Vesve Forest} {Swimmers cannot attack this realm. For each magical item and artifact attached to an attacking champion, subtract 2 levels from his total. The champion's level cannot drop below 1.} C Coast. {5 31} {} 1}
    {DR    7 {} 13 5 0 {Mount Nevermind} {Champions cannot use other cards (even events) or special powers when attacking or defending this realm. Instead, each champion draws one card and adds the last digit to the champion's level. The champion with the highest total wins the battle.} UC Coast. {5 31} {} 1}
    {DR    8 {} 13 5 0 Palanthas {Dragons and wizards cannot attack this realm. Defending dragons and wizards are immune to offensive spells and harmful events.} C Coast. {5 31} {} 1}
    {DR    9 {} 13 6 0 {Mount Deismaar} {This player's champions are immune to offensive blood abilities. Any champion defending this realm can use wizard spells and blood abilities.} R {} 31 {d3 o3 d19 o19} 1}
    {DR   10 {} 8 7 0 {Dragon's Horde} {Dragons attacking this player's formation can attack only the attached realm; else they cannot attack.} R {} 31 {} 1}
    {DR   11 {} 8 7 0 {Dark Depths} {A realm with this holding is immune to the special powers of Underdark realms.} UC {} 31 {} 1}
    {DR   12 {} 8 3 0 {Powers of the Land} {The base level of undead champions defending any realm of this player is doubled. Undead champions defeated while defending the attached realm return to their pool instead of being discarded.} C {} 31 {} 1}
    {DR   13 5 8 2 0 {The Mistmarsh} {Flyers cannot attack the attached realm, and defending swimmers return to their pool if defeated. This holding can defend the attached realm as a level 5 monster.} C {} 31 {1 2 d9 o9} 1}
    {DR   14 {} 8 1 0 {The Mist Caves} {The attached realm cannot be attacked by flyers or swimmers. Giants defending this realm are immune to offensive magical items.} C {} 31 {} 1}
    {DR   15 {} 8 4 0 {Dragon's Crown} {If attached to the Dragon's Crown Mountains, this player's champions all become dragons. If attached to other realms, the defending champion is immune to offensive spells.} C {} 31 {} 1}
    {DR   16 {} 6 0 0 {Council of Wyrms} {Dragons meet to discuss war and peace! Players may draw a card for each dragon in their pool; these champions may not attack or defend until the beginning of the event player's next turn. (Helpful)} C {} {23 29 30 31 32 33 34} {} 1}
    {DR   17 {} 6 0 0 {Dragon Magic} {Until the end of this player's next turn, only dragons can cast spells. (Harmful)} R {} {22 29 30 31 32 33 34} {} 1}
    {DR   18 {} 6 0 0 {Dragon's Graveyard} {Return one dragon champion and one dragon ally from the discard pile to your hand. (Helpful)} UC {} {23 29 30 31 32 33 34} {} 1}
    {DR   19 {} 6 0 0 {Wyrm's Decree} {Until this player's next turn, cards cannot be drawn by another player from your draw deck, discard pile, or hand, and opposing players cannot force you to draw or discard cards. (Helpful)} C {} {23 29 30 31 32 33 34} {} 1}
    {DR   20 {} 6 0 0 {Dragon Raid!} {Until the end of this player's next turn, all dragons can attack as many times as they wish (if successful) until a realm is razed. (Helpful)} R {} {23 29 30 31 32 33 34} {} 1}
    {DR   21 {} 6 0 0 {Dragon Fear} {All champions of base level 5 or less suffer from dragon fear and cannot act (attack or defend, cast spells, use psionics, etc) until the end of this player's next turn. (harmful)} UC {} {22 29 30 31 32 33 34} {} 1}
    {DR   22 {} 6 0 0 Trapped! {Play on an opposing player's champion, who can do nothing until this event is negated. A trapped champion remains in his pool while imprisoned. (Harmful)} C {} {22 29 30 31 32 33 34} {} 1}
    {DR   23 {} 6 0 0 {Forced Revolt} {An opposing player must either discard all allies in his hand or may discard one champion from his pool. If he has no allies, he must discard a champion from his pool. (Harmful)} C {} {22 29 30 31 32 33 34} {} 1}
    {DR   24 {} 6 0 0 {Favorable Winds} {Must be played immediately upon being drawn. Eack player draws one card for each flyer in his pool. (Helpful)} R {} {23 29 30 31 32 33 34} {} 1}
    {DR   25 {} 6 0 0 {Blessing of Zorquan} {Until the end of this player's next turn, cards specifically designed to harm dragons or monsters do not function against this player's champions. (Helpful)} C {} {23 29 30 31 32 33 34} {} 1}
    {DR   26 8 10 7 0 {Infyrana the Dragon} {Flyer. Infryana can cast wizard spells and is immune to the special powers of heroes and allies. If discarded as a result of combat, she can destroy one magical item or artifact in play.} UC {} {8 16 32 33} {1 2 d101 o101 d9 o9 d19 o19} 1}
    {DR   27 9 10 7 0 Flame {Dragon; flyer. Flame must be defeated twice while defending before being discarded. Allies of +3 or less cannot be played against him.} C {} {8 16 32 33} {1 2 d9 o9 o101 d101} 1}
    {DR   28 7 20 1 0 {Pelath the Bronze Dragon} {Flyer; swimmer. Swimming champions and allies cannot face this dragon in combat. At the end of this player's turn, Pelath can retrieve one magical item from the discard pile, which is then attached to him.} C {} {8 16 37 32 33} {1 2 d9 o9 d19 o19 o101 d101} 1}
    {DR   29 9 20 7 0 {Maldraedior, Great Blue Wyrm} {Dragon; flyer. Maldraedior can cast any spell. Phase 4 spells cast by him during combat are shuffled back into the draw pile instead of discarded.} UC {} {8 16 32 33} {1 2 d4 o4 d101 o101 d9 o9 d19 o19} 1}
    {DR   30 8 5 1 0 {Tamarand, Great Gold Wyrm} {Dragon; flyer. While Tamarand is in play all flying monsters must ask his permission to fly. Allies of +3 or less cannot be played against him.} C {} {8 16 32 33} {1 2 d9 o9 d4 o4 o101 d101} 1}
    {DR   31 10 20 1 0 {Lareth, King of Justice} {Dragon; flyer. All dragons must ask Lareth's permission to cast wizard spells. Lareth never needs permission to cast spells. He is immune to cards designated as offensive.} R {} {8 16 32 33} {1 2 d9 o9 d19 o19 o101 d101} 1}
    {DR   32 9 7 7 0 Flashburn {Dragon; flyer. Flashburn has access to a nonflying +9 orc ally that cannot be forced to switch sides during battle.} C {} {8 16 32 33} {1 2 d9 o9 d18 o18 o101 d101} 1}
    {DR   33 7 20 1 0 {Fi Lendicol} {Dragon. Fi Lendicol can teleport with his allies to attack any realm. He can use any unarmed combat card and is immune to offensive cleric spells and offensive psionics.} C Flyer. {8 16 32 33} {1 2 d101 o101 d9 o9 d18 o18 d102 o102 d19 o19} 1}
    {DR   34 7 10 1 0 Rauglothgor {Dragon; undead. Rauglothgor can cast wizard spells and is immune to offensive spells. His total level is doubled if defending Rauglothgor's Lair.} C Flyer. {8 16 40 32 33} {1 2 d101 o101 d9 o9 d102 o102 d19 o19} 1}
    {DR   35 6 12 7 0 {Sparkle, Crystal Dragon} {If an opponent wishes to play an ally against Sparkle, she psionically inspects the player's hand and chooses which ally to play; no more allies can be played by that player. (Off)} UC {} {8 27 32 33} {1 2 d9 o9 d11 o11 o101 d101} 1}
    {DR   36 7 10 7 0 {Shadow Dragon} {This dragon and his allies can attack any realm in a formation. Opposing champions are at half their base level (rounded down), with lost levels being added to the Shadow Dragon's total. He is immune to the special powers of Underdark champions.} R {} {8 32 33} {1 2 d9 o9 o101 d101} 1}
    {DR   37 6 20 2 0 {Greyhawk Dragon} {Flyer. This dragon breathes a toxic gas at the beginning of the battle, preventing an opposing champion from using spells, unarmed combat cards, and blood abilities.} UC {} {8 16 32 33} {1 2 d9 o9 d19 o19 o101 d101} 1}
    {DR   38 7 10 5 0 Flare {Dragon; flyer. One Dragonlance champion in play can be used as an ally (base level only). Win or lose, the borrowed champion returns to his pool.} C {} {8 16 32 33} {1 2 d9 o9 o101 d101} 1}
    {DR   39 6 10 5 0 Sleet {Dragon; flyer. Sleet's numbing cold prevents nonflying allies from being played against him. If instantly defeated by a card's special powers, he returns to his pool instead of being discarded.} C {} {8 16 32 33} {1 2 d9 o9 o101 d101} 1}
    {DR   40 7 10 5 0 Khisanth {Dragon; flyer. If Khisanth razes an opponent's realm in combat, one other unrazed realm anywhere in play is sent to Limbo until the end of the defender's next turn. Realms return from Limbo to any place in that player's formation.} UC {} {8 16 32 33} {1 2 d9 o9 o101 d101} 1}
    {DR   41 7 10 5 0 {Cyan Bloodbane} {Dragon; flyer. Cyan can use wizard spells. Magical items attached to him cannot be removed by any means. Dragonlance allies attached to this champion are doubled in level and cannot be removed or forced to switch sides.} UC {} {8 16 32 33} {1 2 d101 o101 d9 o9 d19 o19} 1}
    {DR   42 7 5 5 0 {Verminaard the Dragonmaster} {Once per battle Verminaard can use any dragon champion in play as an ally (level only). The borrowed champion returns to its pool. He gains 4 levels if Tiamat or Takhisis is in play.} R {} {32 33} {1 2 d9 o9 d4 o4} 1}
    {DR   43 23 5 7 1 {The Celestial Emperor} {Avatar; dragon. Discard 15+ levels of dragons to bring the Emperor into play. Immune to offensive spells and the special powers of champions and allies. When this player's dragons attack, the Emperor chooses which of the opponent's champions will defend. Limit one avatar per pool.} R {} {8 32 33} {1 2 d9 o9 d4 o4 o101 d101} 1}
    {DR   44 20 20 7 1 {Tiamat, God of Evil Dragons} {Avatar; flyer. Discard two spellcasting dragons to bring Tiamat into play. She is immune to offensive psionics, unarmed combat cards, and blood abilities. If this player's dragons lose in battle, they return to their pool instead. Limit one avatar per pool.} UC Dragon. {8 16 32} {1 2 d9 o9 d19 o19 o101 d101} 1}
    {DR   45 21 7 7 1 {Bahamut, God of Good Dragons} {Avatar; flyer. Discard two spellcasting dragons to bring Bahamut into play. He is immune to the special powers of champions and allies. Champions in Bahamut's pool are doubled in base level when defending, as are all dragon allies. Limit one avatar per pool.} UC Dragon. {8 16 32} {1 2 d9 o9 d18 o18 o101 d101} 1}
    {DR   46 {} 19 0 0 {Astral Spell} {Cast at any time to create an astral duplicate of the caster (level and special power) to defend this player's realms once an attacker comes forward. Cards can be attached as normal, but are discarded with the duplicate at the end of that round of battle. (Def)} R {} {6 29 30 31 32 33 34} {} 1}
    {DR   47 {} 19 0 0 {Dragon's Calm} {Castable only by dragon champions. Can be cast at any time to cancel the effects of a harmful event. (Def)} UC {} {6 29 30 31 32 33 34} {} 1}
    {DR   48 {} 19 0 0 {Humanoid Familiar} {Castable only by dragon or monster champions. Cast this spell on a hero not involved in combat to bring him in as an ally. The caster gains the hero's special power and level, and the hero is discarded after the battle. (Off/4)} C {} {27 33} {} 1}
    {DR   49 {} 19 0 0 Venomdust {Castable only by dragons, this spell slays one champion of base level 5 or less, or slays one opposing ally. (Off/3/4)} C {} {27 32 33} {} 1}
    {DR   50 {} 19 0 0 Firetrail {Castable only by dragons, this spell destroys any one holding in play. (Off/3)} C {} {27 32} {} 1}
    {DR   51 {} 19 0 0 {Dragon's Death Door} {Castable only by dragons. Cast at any time to save a dragon champion from going to the discard pile for any reason, or to send it to the discard pile instead of the Abyss. (Def)} C {} {6 29 30 31 32 33 34} {} 1}
    {DR   52 {} 19 0 0 {Cold Curtain} {Castable only by dragons. This spell creates a wall of dragon ice that instantly ends combat. Champions return to their pools and phase 4 of the attacker's turn is over with no spoils of victory. (Def/4)} C {} {6 33} {} 1}
    {DR   53 {} 19 0 0 {Summon Dragon} {May also be cast by any dragon. This spell summons a dragon champion from any pool to act as an ally (level only). Win or lose, the summoned champion returns to his pool. (Def/4)} C (Off/4) {27 33} {} 1}
    {DR   54 {} 19 0 0 {Dragon Mark} {Castable only by dragon champions. Cast on an opposing champion to prevent him from defending against dragon champions attacking this turn. (Off/3)} UC {} {27 32} {} 1}
    {DR   55 +6 19 0 0 {Meteor Swarm} {This spell destroys one magical item or artifact of an opposing champion as well as any opposing allies of +3 or less in combat. (Off/4)} UC {} {27 33} {} 1}
    {DR   56 {} 4 0 0 {Enchanted Flight} {Cast to make a champion and its allies flyers or to make a flyer immune to any card's special powers that directly affect flyers. (Def/3/4)} R {} {6 32 33} {} 1}
    {DR   57 {} 4 0 0 {Blessing of Tiamat} {May also be cast by any dragon. Cast on a dragon champion to ignore the levels or special powers of any opposing allies until the end of this player's next turn. (Def/3/4)} C {} {6 32 33} {} 1}
    {DR   58 {} 4 0 0 {Blessing of Bahamut} {May also be cast by any dragon. Cast on a dragon champion to ignore the levels or special powers of any opposing champions until the end of this player's next turn. (Def/3/4)} C {} {6 32 33} {} 1}
    {DR   59 {} 4 0 0 {Symbol of Pain} {This spell inflicts terrible pain on a champion, preventing casting spells or using psionic power cards. Lasts until dispelled. (Off/3/4)} C {} {27 32 33} {} 1}
    {DR   60 {} 4 0 0 {Symbol of Persuasion} {Cast during battle to force two opposing allies (caster's choice) to switch sides. Allies must be present when the spell is cast. (Off/4)} C {} {27 33} {} 1}
    {DR   61 {} 4 0 0 {Symbol of Death} {This spell destroys up to 10 levels of opposing allies or prevents an opponent from playing magical items in this round of battle. Any already attached are unaffected. (Off/4)} R {} {27 33} {} 1}
    {DR   62 {} 4 0 0 Confusion {Cast on an attacking champion who must choose another player's realm to attack. If he cannot attack another realm, or it's a two-player game, the champion returns to his pool defeated. (Off/4)} C {} {27 33} {} 1}
    {DR   63 {} 4 0 0 {Find the Path} {This player's champions and allies can attack any opposing realm, regardless of position or restrictions, until the end of this turn. (Def/3)} C {} {6 32} {} 1}
    {DR   64 {} 4 0 0 {True Seeing} {This spell can be cast at any time to inspect an opponent's hand or the next three cards of one draw pile. (Off)} C {} {27 29 30 31 32 33 34} {} 1}
    {DR   65 {} 4 0 0 Plague {When this spell is cast on an opposing champion, that player must draw and discard a card, noting the last digit. If the number is higher than the champion's base level, he is discarded. (Off/4)} R {} {27 33} {} 1}
    {DR   66 {} 11 0 0 {Inertial Barrier} {Until the beginning of this player's next turn, champions of base level 6 or less cannot attack this player's realms. (Def/5)} C {} {6 34} {} 1}
    {DR   67 {} 11 0 0 {Combat Mind} {Until the end of this turn, the champion using this power can attack an opposing realm multiple times until he is either defeated or the realm is razed. (Def/3)} UC {} {6 32} {} 1}
    {DR   68 {} 11 0 0 Phase {Before attacking, a champion can use this power to ignore any realm's special power. (Def/3)} C {} {6 32} {} 1}
    {DR   69 +3 11 0 0 {Death Field} {Usable only during combat, the opposing champion can no longer use spells, psionic power cards, blood abilities, or unarmed combat cards. (Off/4)} C {} {27 33} {} 1}
    {DR   70 +5 11 0 0 Ultrablast {When this card is used, the opponent must draw and discard a card, noting the last digit. If the number is 2 or less, the opposing champion is discarded. (Off/4)} R {} {27 33} {} 1}
    {DR   71 {} 11 0 0 {Synaptic Static} {Use this power at any time to cancel an offensive psionic power card when it is first played. (Off)} C {} {27 29 30 31 32 33 34} {} 1}
    {DR   72 {} 11 0 0 Daydream {A champion using this power cannot act again until the end of his player's next turn. At the beginning of this player's next turn, he may draw five cards instead of three if the daydreaming champion is still in play. (Def/5)} R {} {6 34} {} 1}
    {DR   73 {} 11 0 0 {Psychic Blade} {Until the end of this player's turn, all magical items used by this player's champions are doubled in level. (Def/3)} C {} {6 32} {} 1}
    {DR   74 +4 9 0 0 {Gauntlets of Combat} {The attached champion can use any type of unarmed combat card. (Def)} C {} {6 32 33} {d101 o101 d18 o18 d102 o102} 1}
    {DR   75 +3 9 0 0 {Talisman of the Beast} {A champion wearing the talisman can fly and is considered a dragon. (Def)} R {} {6 32 33} {} 1}
    {DR   76 {} 9 0 0 {Wand of Magic Detection} {Use this wand in phase 3 of your turn to force all opponents to show you all magical items and artifacts in their hand and face down in pools. (Off)} C {} {27 32 33} {} 1}
    {DR   77 {} 9 0 0 {Well of Many Worlds} {Discard this card from the attached champion during a round of combat to send two cards attached to the opposing champion to the Abyss. (Off)} UC {} {27 32 33} {} 1}
    {DR   78 {} 9 0 0 {Wand of Negation} {During combat only, this wand negates all the immunities of an opposing champion (including immunity to offensive magical items). (Off)} R {} {27 32 33} {} 1}
    {DR   79 +9 9 0 0 {Maul of the Titans} {Usable only by giants. The attached champion ignores the special powers of opposing realms, holdings, and allies. (Def)} UC {} {6 32 33} {} 1}
    {DR   80 +2 1 0 0 {Cult of the Dragon} {Playable only with a dragon champion. This ally doubles the base level of the attached dragon. It is discarded if forced to switch sides.} R {} 33 {} 1}
    {DR   81 +5 1 0 0 {Undead Dragonrider} {Dragon; undead; flyer. All opposing allies that are not undead or flyers are level 0 and have no special powers.} UC {} {8 16 40 33} {} 1}
    {DR   82 +5 1 0 0 Dragonne {Dragon; flyer. This ally can use unarmed combat cards usable only by dragons. Playing this ally discards an opposing ally of +2 or less already in play.} C {} {8 16 33} {o101 d101} 1}
    {DR   83 +3 1 0 0 {Faerie Dragon} {Flyer. This ally can cast wizard spells. The faerie dragon cannot be forced to switch sides or be discarded in combat for any reason.} C {} {8 16 33} {d19 o19} 1}
    {DR   84 +6 1 0 0 Firedrake {Dragon; flyer. The base level of an opposing nondragon champions is reduced to 2 for this round of battle.} C {} {8 16 33} {} 1}
    {DR   85 +5 1 0 0 Drake {Dragon; flyer. This ally can be discarded from a player's hand to prevent a dragon champion from going to the discard pile for any reason.} C {} {8 16 33} {} 1}
    {DR   86 +4 2 7 0 {Amulet of the Wyrm} {This artifact can only be attached to a dragon champion of any world. The champion can cast any spell and is immune to offensive unarmed combat cards.} UC {} {32 33} {d4 o4 d19 o19} 1}
    {DR   87 +4 2 7 0 {Fang of the Dragon} {This artifact can only be attached to a dragon champion of any world. The champion can use any psionic power card or blood ability.} UC {} {32 33} {d3 o3 d11 o11} 1}
    {DR   88 {} 2 7 0 {Orb of the Eternal Dragon} {This artifact can only be attached to dragon champions of any world. The level bonus of all cards attached to this dragon are doubled. Opposing dragons cannot enter battle against this champion.} R {} {32 33} {} 1}
    {DR   89 +8 2 7 0 {Mighty Servant of Leuk-o} {A champion with this artifact is immune to the special powers of champions and allies of level 5 or less.} UC {} {32 33} {} 1}
    {DR   90 {} 18 0 0 Swoop {Usable only by dragons. This maneuver doubles the base level of an attacking dragon if the opposing champion cannot fly. (Def/4)} R {} {6 9 33} {} 1}
    {DR   91 +4 18 0 0 Claw {Usable only by dragon champions. Victims of this maneuver can play no further allies or magical items in this battle. (Off/4)} C {} {9 27 33} {} 1}
    {DR   92 +5 18 0 0 {Tail Sweep} {Usable only by dragon champions. Victims of this maneuver can play no further spells, psionic power cards, or blood abilities in this battle. (Off/4)} C {} {9 27 33} {} 1}
    {DR   93 +6 18 0 0 Bite {Usable only by dragons. Victims of this maneuver must discard an attached magical item or discard the first one they play if they have none attached. (Off/4)} R {} {9 27 33} {} 1}
    {DR   94 +4 18 0 0 {Breath Weapon I} {Usable only by dragon champions. Instantly destroys all allies of +3 or less. (Off/4)} C {} {9 27 33} {} 1}
    {DR   95 +6 18 0 0 {Breath Weapon II} {Usable only by dragon champions. Discard an opposing champion or ally of base level 4 or less. (Off/4)} UC {} {9 27 33} {} 1}
    {DR   96 +8 18 0 0 {Breath Weapon III} {Usable only by dragon champions. Discards an opposing champion of base level 5 or less or any two opposing allies. (Off/4)} R {} {9 27 33} {} 1}
    {DR   97 {} 18 0 0 {Swallow Whole} {Usable only by dragon champions. Play once a dragon's total level exceeds 24 to swallow (discard) the opposing champion and automatically win the round of battle. (Off/4)} UC {} {9 27 33} {} 1}
    {DR   98 {} 18 0 0 Evade {Usable by any champion. Play at any time to cancel the effects of an unarmed combat card. (Def)} C {} {6 29 30 31 32 33 34} {} 1}
    {DR   99 {} 15 7 0 {Age of the Dragon} {Played at the beginning of this player's turn, this card is not discarded. It affects all players and remains in effect until any other rule card is played. All dragon champions and dragon allies in play are immune to offensive spells, magical items, and psionic power cards.} R {} 29 {} 1}
    {DR  100 {} 15 7 0 {The Battle Must Go On!} {Played at the beginning of the player's turn, this card is not discarded. It affects all players and remains in effect until the end of the game. It is immune to spells and events. A player must have six unrazed realms at the start of his turn in order to win. Further, any player who runs out of cards must shuffle his discard pile and use that as his new draw pile.} UC {} 29 {} 1}
    {DR  101 12 10 7 0 {T'chaar, Dragon of Flame} {Flyer. T'chaar thrives on destruction and may use any offensive card (spell, psionic powers, unarmed combat, blood abilities, etc). Defensive cards played against T'chaar are doubled in icon level.} VR {} {8 16 32 33} {1 2 o3 o4 d101 o101 d9 o9 o11 o17 o18 o102 o19} 1}
    {DR  102 {} 6 0 0 {Lair Raid!} {Until the end of this player's next turn, all dragons are halved in level when in combat with nondragon champions. While this event is in play, all dragons lose their special powers. (Harmful)} VR {} {22 29 30 31 32 33 34} {} 1}
    {DR  103 8 10 7 0 Boreas {Dragon, flyer. Boreas can cast wizard spells. He can charm opposing champions, forcing them to give him an attached item (this player's choice). At the end of the battle, the attachment is shuffled back into the owning player's draw pile.} VR {} {8 16 32 33} {1 2 d101 o101 d9 o9 d19 o19} 1}
    {DR  104 6 7 1 0 {Morcanth Dragontamer} {Flyer. Dragons cannot oppose Morcanth in battle. In combat, she can force any dragon champion to act as her ally, adding its level and special power to her own. If she is defeated, the dragon champion allied with her is also discarded.} VR {} {16 32 33} {1 2 d9 o9 d18 o18} 1}
    {DR  105 10 10 2 0 {Cron the Black} {Dragon; flyer; swimmer. During combat, Cron's powerful acid breath can destroy any single attachment of an opposing champion.} VR {} {8 16 37 32 33} {1 2 d9 o9 o101 d101} 1}
    {DR  106 {} 6 0 0 {Draconic Allies} {Until the end of this player's turn, his champions may attack any realm, regardless of position or restrictions. These champions attack with surprise, preventing the opposing player from playing cards other than allies in the battle. (Harmful)} VR {} {22 29 30 31 32 33 34} {} 1}
    {DR  107 ? 10 7 0 {Lernaean Hydra} {The Lernaean Hydra has a base level equal to the adjusted level of the champion opposing it when combat is first entered. When in the player's pool, it is immune to offensive spells, psionic power cards and harmful events.} VR {} {32 33} {1 2 d9 o9} 1}
    {DR  108 2 10 7 0 {Dragon Hatchling} {Dragon champions will not fight against the Dragon Hatchling. If defeated in battle, the discard piles of all players are shuffled back into their draw piles.} VR {} {8 32 33} {1 2 d9 o9 o101 d101} 1}
    {DR  109 8 5 1 0 {Dragon Cultist} {The Dragon Cultist can raise dragons from the dead. Every turn that this champion doesn't attack, his player may return one dragon champion from his discard pile to his hand.} VR {Dragon. NOT a flyer.} {8 32 33} {1 2 d4 o4 d101 o101 d9 o9} 1}
    {DR  110 {} 15 7 0 {Playing to Lose} {Played at the beginning of the player's turn, this card is not discarded. It affects all players and remains in effect until any other rule card is played. During phase 2 a player can opt to raze one of his own realms, in addition to playing a realm or holding. While this rule is in effect, the first player to have six razed realms in his formation for one full turn wins, instead of the normal winning conditions. Players may attack razed realms in another player's formation to discard them, if successful.} VR {} 29 {} 1}
    {DR  111 4 10 7 0 Wyvern {The Wyvern's poisonous sting is extremely deadly. Each ally played with it reduces the opposing champion by half that many levels (rounded down).} VR Flyer. {16 32 33} {1 2 d9 o9} 1}
    {DR  112 9 5 7 0 {Charm, the Crystal Dragon} {Flyer. Charm can cast wizard spells and psionic power cards. If opposed when she attacks, her dazzling breath weapon destroys all holdings in that player's formation.} VR {} {8 16 32 33} {1 2 d4 o4 d101 o101 d9 o9 d11 o11 d19 o19} 1}
    {DR  113 +9 1 0 0 Chimera {Flyer. When played in combat, the Chimera uses its fiery breath to blast away one card in the opposing champion's force (excluding the champion).} VR {} {16 33} {} 1}
    {DR  114 +5 9 0 0 {Red Dragon Figurine} {This magical item can be attached to a champion to add 5 levels or may be played as a 5 level monster (dragon) champion. (Def)} VR {} {6 32 33} {1 2 d101 o101 d9 o9} 1}
    {DR  115 6 12 7 0 {Sapphire the Blue Dragon} {Flyer. Sapphire can use wizard spells. At the start of battle, he may breath lightning on the opposing champion, who must discard all attached items or a realm from his player's hand.} VR {} {8 16 32 33} {1 2 d101 o101 d9 o9 d11 o11 d19 o19} 1}
    {DR  116 7 7 7 0 {Glimmer the Brass Dragon} {Flyer, Earthwalker. Glimmer can cast cleric spells. He has a large hoard and is constantly adding to it. Whenever is victorious in battle, his player can return a magical item or artifact from his discard pile and attach it to Glimmer.} VR {} {8 13 16 32 33} {1 2 d4 o4 d101 o101 d9 o9 d18 o18} 1}
    {DR  117 {} 6 0 0 {Treasure Hoard} {Rumors of a great treasure lure dragons from their lairs. Dragon champions in play are sent to Limbo and cannot return until their owner's discard one magical item for each champion. (Harmful)} VR {} {22 29 30 31 32 33 34} {} 1}
    {DR  118 +4 9 0 0 {Dragon's Bones} {The attached champion can discard this item at any time to end a battle involving a dragon champion. The combat ends without a victor. (Off)} VR {} {27 32 33} {} 1}
    {DR  119 {} 6 0 0 {Dragon Skirmish} {A power struggle among dragonkind leads to a brutal war. In one pool chosen by this player, all dragons -except for the one with the highest level- are discarded. (Harmful)} VR {} {22 29 30 31 32 33 34} {} 1}
    {DR  120 +5 9 0 0 Wyrmblight {Sword; may only be attached to nondragon heroes .The attached champion is immune to the special powers of all dragons and the special powers of any cards attached to them. (Def)} VR {} {6 32 33} {} 1}
    {DR  121 {} 6 0 0 {Wyrms' Conclave} {Until the end of this player's next turn, no dragon champions or allies may be involved in combat. (Harmful)} VR {} {22 29 30 31 32 33 34} {} 1}
    {DR  122 {} 15 7 0 {Dragon's Breath} {Played at the beginning of this player's turn, this card is not discarded. It affects all players and remains in effect until any other rule card is played. Only dragon champions may attack.} VR {} 29 {} 1}
    {DR  123 {} 15 7 0 {Ancient Draconic Magic} {Played at the beginning of this player's turn, this card is not discarded. It affects all players and remains in effect until any other rule card is played. Spells cast by dragon champions cannot be dispelled.} VR {} 29 {} 1}
    {DR  124 {} 13 7 0 {Underground Lair} {Cannot be attacked by flyers or swimmers. Defending dragons can take any one card from their discard pile and play it immediately.} VR {} 31 {} 1}
    {DR  125 {} 9 0 0 {Dragon's Scale} {The attached champion is immune to both offensive wizard spells and offensive unarmed combat cards - though only if played by dragon champions. (Def)} VR {} {6 32 33} {} 1}
}
