set CrossFire::cardDataBase {
    Dungeons
    {DU    1 {} 21 7 0 {Mausoleum of the Zombie Master} {This player's champions can never enter the Abyss. If sent there by an opposing player's action, the champion instead goes to the discard pile. If sent there by this player's action, it is removed permanently from the game.} C {} {} {} 1}
    {DU    2 {} 21 6 0 {Dungeon of the King} {This player's champions do not need to ask permission to use spells, psionic powers, unarmed combat cards, blood abilities, or thief skills.} C {} {} {} 1}
    {DU    3 {} 21 4 0 {Lair of Dregoth, the Undead Dragon-King} {This player may discard a Dark Sun champion from his pool or hand to psionically turn a just-cast spell back at its original caster.} UC {} {} {} 1}
    {DU    4 {} 21 5 0 {Domain of Takhisis, Queen of Darkness} {This player's monster (dragon) champions are immune to all events, spells, artifacts, and magical items that instantly discard or defeat them.} C {} {} {} 1}
    {DU    5 {} 21 1 0 Undermountain {Each time this player is entitled to draw spoils of victory, he may also take the bottom three cards of his draw pile. Any monster champions there may be placed into his pool. Any other cards are placed on the top of his draw pile.} C {} {} {} 1}
    {DU    6 {} 21 2 0 {Labyrinth of Castle Greyhawk} {This player's Greyhawk realms may only be razed or discarded through combat.} R {} {} {} 1}
    {DU    7 {} 21 3 0 {Under Castle Strahd} {This player's Ravenloft champions all become undead, and Young Strahd's special power has no effect on this player's champions.} C {} {} {} 1}
    {DU    8 {} 21 7 0 {Palace of the Celestial Light} {This player's clerics need never ask permission to cast spells. Avatars may not attack this player's realms, nor may defend against this player's cleric champions.} C {} {} {} 1}
    {DU    9 {} 21 7 0 {Field of the Battle Lord} {This player's heroes do not discard unarmed combat cards at the end of combat. Instead, they are retained for future combat, adding the cards' bonuses but ignoring their special powers.} R {} {} {} 1}
    {DU   10 {} 21 7 0 {The Belly of the Beast} {This player's monsters are immune to hero unarmed combat cards. They may also use any unarmed combat card themselves (hero, dragon, undead, etc), regardless of restrictions.} C {} {} {d101 o101 d18 o18 d102 o102} 1}
    {DU   11 {} 21 7 0 {Pit of the Mind Lord} {This player's realms and his psionicist champions are immune to all spells cast in phase 3.} C {} {} {} 1}
    {DU   12 {} 21 6 0 {The Torture Room} {This player may reshuffle his discard pile into his draw pile any time there are three of more blood abilities in his discard pile. No champions have immunity to this player's blood abilities while this dungeon card is in play.} C {} {} {} 1}
    {DU   13 {} 21 7 0 {Maze of the Guild} {This player's thief champions can use stealth to attack any realm, regardless of powers or restrictions. Allies must still follow movement restrictions.} C {} {} {} 1}
    {DU   14 {} 21 7 0 {Carrock of High Magicks} {This player can keep a spellbook. Each time this player is entitled to draw spoils of victory, he may instead search through his draw pile and retrieve any spell; the spell cannot be played immediately.} R {} {} {} 1}
    {DU   15 {} 21 5 0 {The Enchanted Land} {This player's champions and allies become elves, elves (drow), dwarves, or halflings as the player chooses. Selection must be made in phase 3 and lasts until the player's next phase 3.} C {} {10 12 14 21} {} 1}
    {DU   16 {} 21 7 0 {Purveyor of Events} {This player's helpful events cannot be negated or cancelled by any card.} UC {} {} {} 1}
    {DU   17 {} 21 7 0 {Spells of the Archmage} {Any wizard spells with a stated duration that are cast by this player's AD&D champions are doubled in duration.} C {} {} {} 1}
    {DU   18 {} 21 1 0 {Spells of the Friar} {Any cleric spells with a stated duration that are cast by this player's Forgotten Realms champions are doubled in duration.} C {} {} {} 1}
    {DU   19 {} 21 2 0 {Spells from the Grave} {Any defensive spells cast by this player's undead Greyhawk champions cannot be dispelled or turned.} R {} {} {} 1}
    {DU   20 {} 21 4 0 {Powers from the Savage Land} {Psionic power cards used by this player's Dark Sun champions are doubled in bonus level.} C {} {} {} 1}
    {DU   21 {} 21 6 0 {Might of the Blood Right} {This player's champions are all considered regents and can use blood abilities.} C {} {} {d3 o3} 1}
    {DU   22 {} 21 5 0 {Song of the Dragonlance} {This player's realms can only be attacked by flyers, swimmers, or earthwalkers. His champions and allies all have the ability to swim as needed.} R {} 37 {} 1}
    {DU   23 {} 21 3 0 {Bats in the Belfry} {No offensive magical items can be used by opponents when attacking this player's realms. The items remain behind in the attacker's pool. If the champion returns, they are reattached; if not, the items are discarded.} R {} {} {} 1}
    {DU   24 {} 21 7 0 {The Azure Tower of Onad the Fallen} {This player's helpful events cannot be negated, and his harmful events cannot be copied. Events that are discarded without being used are placed in the discard pile instead of the Abyss.} R {} {} {} 1}
    {DU   25 {} 21 7 0 {Beneath Castle Drawmij} {This player's holdings cannot be discarded except by razing the attached realm. This player can ignore the Rules of the Cosmos when playing holdings.} UC {} {} {} 1}
    {DU   26 {} 21 7 0 {Return of the Dwarven King} {This player's dwarf champions are immune to all events (helpful and harmful). This player's dwarves add 3 to their adjusted levels.} C {} {} {} 1}
    {DU   27 {} 21 7 0 {The Guildhall} {Each time this player's thief champions are in combat, their player may take the top card from any other player's draw pile. If it can be legally played, do so. Otherwise it goes to its owner's hand. Cards used are returned to the bottom of the owner's draw pile after combat is resolved.} C {} {} {} 1}
    {DU   28 {} 13 7 0 {The Dragon's Refuge} {If an opposing player's dragon champion is defeated in combat, this player may attach the dragon to this realm and use it as an ally (level only) the next time the realm is attacked.} UC {} 31 {} 1}
    {DU   29 {} 13 6 0 {Cities of the Sun} {This player's champions may all use blood abilities.} C {} 31 {d3 o3} 1}
    {DU   30 5 13 2 0 {Border Post} {This realm can defend itself as a level 5 hero. If it is in the same formation as the Border Garrison, its level adds to that realm.} UC {} 31 {1 d18 o18} 1}
    {DU   31 10 13 2 0 {Border Garrison} {This realm can defend itself as a level 10 wizard. Regardless of where it is in the formation, it must be attacked first.} R {} 31 {1 d19 o19} 1}
    {DU   32 {} 13 3 0 {The Ruins of Iolonia} {These ruins are so forlorn that only undead champions and allies will attack this realm.} R Ravenloft. 31 {} 1}
    {DU   33 {} 13 5 0 {Tower by the Sea} {The lighthouse is a haven, letting this player increase or reduce his swimming champions' and allies' base level by 3.} C {} {5 31} {} 1}
    {DU   34 {} 13 4 0 {The Forgotten Ruins} {A powerful psionic shield emanates from this realm, protecting this player's champions from unarmed combat cards.} C {} 31 {} 1}
    {DU   35 +8 13 1 0 {The Hidden Village} {The treant ally guarding this realm is immune to all cards played by or attached to an opposing champion except those that contain the word "fire" or "flame."} C {} 31 {} 1}
    {DU   36 {} 13 7 0 {Bitter Knoll} {Any realm played into the formation after the Bitter Knoll is converted into an AD&D realm. If this realm is razed or discarded, all converted realms return to their original trademarks.} C {} 31 {} 1}
    {DU   37 7 7 6 0 {The Ogre} {Awnshegh; can use blood abilities and all unarmed combat cards. In combat this player may take the top three cards from any opponent's draw pile. Any monsters join the Ogre's side as allies; all other cards are placed at the bottom of the owner's draw pile. At the end of combat, the monster-allies go to their owner's pool.} UC {} {2 32 33} {1 2 d3 o3 d101 o101 d9 o9 d18 o18 d102 o102} 1}
    {DU   38 10 10 5 0 {Fire Dragon} {Flyer. This monster's searing breath weapon destroys all cards attached to a champion when it first enters combat. Other cards can be attached subsequently.} R {} {8 16 32 33} {1 2 d9 o9 o101 d101} 1}
    {DU   39 7 14 6 0 {Zaranda Star} {Adventurer. Zaranda can store blood abilities face down beneath her in the pool, using whichever ones she wishes in combat.} C {} {1 32 33} {1 2 d9 o9 d3 o3} 1}
    {DU   40 5 16 7 0 Skulker {Swimmer. Leader of a band of undersea pirates, Skulker can plunder any opponent's discard pile during combat, using any allies, magical items, or artifacts (if legal) found there. At the end of the round, the cards are returned to their owner's draw pile, which is reshuffled.} R {} {37 32 33} {1 2 d9 o9 d17 o17} 1}
    {DU   41 4 7 1 0 Jasper {Adventurer. Cautious and wary, Jasper deflects unarmed combat cards played against him to a champion in any pool.} UC {} {1 32 33} {1 2 d9 o9 d18 o18} 1}
    {DU   42 5 16 5 0 {The Hapless Halfling} {Adventurer. A morale booster, the halfling adds 2 levels to all fellow adventurers and halfling champions and allies played by this player.} C {} {1 21 32 33} {1 2 d9 o9 d17 o17} 1}
    {DU   43 9 7 4 0 {Feral Halfling} {Can use all unarmed combat cards and defensive psionic powers. An opposing champion defeated by the feral halfling is eaten (sent to the abyss.)} UC {} {21 32 33} {1 2 d101 o101 d9 o9 d11 d18 o18 d102 o102} 1}
    {DU   44 6 20 1 0 {Dearlyn Ambersong} {Adventurer. Especially distrustful of thieves, Dearlyn can choose to negate one thief skill played against her or a fellow adventurer in combat once per turn.} C {} {1 32 33} {1 2 d9 o9 d19 o19} 1}
    {DU   45 10 5 2 0 {Tyvorg the Frost Giant} {Can cast wizard spells. Tyvorg instantly slays the Living Wall when he is brought into play. For each giant ally played with him, Tyvorg's base level increases by 10.} C {} {17 32 33} {1 2 d4 o4 d9 o9 d19 o19} 1}
    {DU   46 +5 1 0 0 Troglodyte {Underdark. This creature's odor is such that all cards in an opposing player's force of icon level 4 or less are discarded (including the champion, if applicable).} C {} {42 33} {} 1}
    {DU   47 +6 1 0 0 {Hook Horror} {Underdark. Because of this creature's acute hearing, it can "hear" the next card to be played by an opposing player (the card is shown but not played) and choose to scuttle back to its pool along with the attached champion.} C {} {42 33} {} 1}
    {DU   48 +9 1 0 0 {Lurker in the Earth} {Underdark; earthwalker. The Lurker can be played at any time as a harmful event to burrow over to a player's pool and devour (discard) any earthwalking champion of level 6 or less or it can be played in combat to discard one opposing ally already played.} UC {} {13 29 30 31 32 33 34 42} {} 1}
    {DU   49 +3 1 0 0 {Skull Tumor} {Underdark. This ally may be played directly into a pool; this player's discarded champions are attached to the Tumor, which increases in level only and may be used in any future combat. Immune to events.} R {} {32 33 42} {} 1}
    {DU   50 +6 1 0 0 {Hero Slayer} {Giant. This ally negates a just played unarmed combat card or instantly slays an opposing hero of base level 4 or less.} C {} {17 33} {} 1}
    {DU   51 +7 1 0 0 {The White Weird} {Underdark; flyer. The White Weird can be played at any time as a harmful event to fly over to a player's formation and poison (discard) one holding or it can be played in combat to halve (round down) an opposing champion's adjusted level.} R {} {16 29 30 31 32 33 34 42} {} 1}
    {DU   52 +? 1 0 0 {Psion Sucker} {When this dreaded ally appears in combat, all psionicists in play are reduced by 2 levels, which are added to the Psion Sucker. The level reductions last until this player's next turn.} C {} 33 {} 1}
    {DU   53 +7 1 0 0 {Master Illithid} {Underdark. When played, this ally can shift any two cards of one type in the opposing player's force to this side. Choice need not be immediate.} UC {} {42 33} {} 1}
    {DU   54 +? 1 0 0 {Bottomless Horror} {Underdark; earthwalker. This horrid creature can reach into any player's Abyss when in combat. The icon levels of all cards there are totaled to become the Horror's bonus. The cards used are removed from the game.} UC {} {13 42 33} {} 1}
    {DU   55 +4 2 2 0 {Boiling Oil} {This artifact can only be attached to a Greyhawk realm. Any attacking champions are destroyed in a vat of boiling oil after the battle (win or lose) and discarded.} R {} {32 33} {} 1}
    {DU   56 +5 2 4 0 {Siege Ladder} {This artifact can only be attached to a Dark Sun realm. Any cards attached to attacking champions are discarded after the battle (win or lose).} UC {} {32 33} {} 1}
    {DU   57 +3 2 1 0 {Net of Ensnaring} {This artifact can only be attached to a Forgotten Realms realm. Any cards played by attacking champions during combat are sent to the Abyss after the battle is resolved.} R {} {32 33} {} 1}
    {DU   58 +? 2 2 0 {Battering Ram} {This artifact can only be attached to a Greyhawk realm. Its bonus is equal to the number of Greyhawk realms and holdings in play.} UC {} {32 33} {} 1}
    {DU   59 +5 2 5 0 Ballista {This artifact can only be attached to a Dragonlance realm. If this realm is attacked, it can target an opposing player's pool and destroy one artifact or magical item.} R {} {32 33} {} 1}
    {DU   60 +3 2 6 0 {Cannon Ball} {This artifact can only be attached to a Birthright realm. If this realm is attacked, it can fire into an opposing player's pool and kill one champion.} R {} {32 33} {} 1}
    {DU   61 +7 2 3 0 Borer {This artifact can only be attached to a Ravenloft realm. It instantly destroys all opposing allies and magical items of less than level 7.} R {} {32 33} {} 1}
    {DU   62 +6 2 7 0 Catapult {This artifact can only be attached to an AD&D realm. At any time during a round of combat, this player can choose to catapult the attacking champion to the Abyss. This realm is razed and the artifact discarded, but no one gains spoils.} C {} {32 33} {} 1}
    {DU   63 {} 2 7 0 {Siege Machine} {This artifact can only be attached to an Underdark realm. It protects all holdings in the player's formation, allowing a holding to be moved to another realm if its attached realm is razed or discarded; the holding is discarded if it cannot be attached to a new realm.} C {} {32 33} {} 1}
    {DU   64 +3 9 0 0 {Sword of Sharpness} {This weapon easily pierces the strongest armor, instantly defeating champions of base level 3 or less. (Off)} C {} {27 32 33} {} 1}
    {DU   65 +4 9 0 0 {The Triton Throne} {This magical item may only be attached to any realm. Its +4 bonus adds to any champion defending the realm and only swimmers may attack the attached realm. (Off)} C {} {27 32 33} {} 1}
    {DU   66 +5 9 0 0 {Flask of Curses} {The attached champion becomes a swimmer. If the champion with this item is defeated in combat, the flask is attached to the victor, becoming a -5 item that negates the attached champion's special powers. (Off)} C {} {27 32 33 37} {} 1}
    {DU   67 +3/+9/+18 9 0 0 {Crystal Dragon Figurine} {This figurine can be used to add a +3 in battle; or can add a +9, but is then discarded; or can add a mighty +18, but then both the magical item and the attached champion are discarded. (Def)} UC {} {6 32 33} {} 1}
    {DU   68 {} 9 0 0 {Amulet of the Dragon King} {This magical item can only be attached to any realm. For each attacking champion defeated while defending the attached realm, 1 dragon champion can be returned from the discard pile to this player's pool or hand. (Def)} UC {} {6 32 33} {} 1}
    {DU   69 +7 9 0 0 {Breath Charm} {This powerful charm makes the attached champion immune to the special powers of an opposing dragon. (Def)} C {} {6 32 33} {} 1}
    {DU   70 +5 9 0 0 {Pearl Pegasus} {This figurine of wondrous power causes its owner to become a flyer. The figure's flight is so dexterous that the owner is immune to all offensive spells, psionic powers, blood abilities, unarmed combat cards, and thief skills that affect a single target. (Def)} R {} {6 32 33} {} 1}
    {DU   71 +8 9 0 0 {Clockwork Ogre} {If the attached champion is discarded in battle, this mechanical marvel returns to the pool and is instantly attached to another champion. If there are no champions in the pool it returns to this player's hand. (Def)} UC {} {6 32 33} {} 1}
    {DU   72 +3 9 0 0 {Amulet of Spell Turning} {Whenever an offensive spell is cast at the attached champion or his pool, this player cuts his draw pile and checks the last digit of the card number of the card revealed. If it is 0-7, the spell is turned back at the caster. On an 8 or 9, the spell takes effect normally. (Def)} R {} {6 32 33} {} 1}
    {DU   73 {} 11 0 0 {Psionic Disintegration} {Cannot be used in a deck containing Disintegrate (393/2nd). Destroys one realm, regardless of position. The destroyed realm must be discarded. This player can make no attacks this turn. (Off/3)} R {} {27 32} {} 1}
    {DU   74 {} 11 0 0 {Magic Draining Field} {Can be played at any time to negate all spells in play, including a just cast spell. No more spells may be cast until the end of this player's next turn. (Def)} C {} {6 29 30 31 32 33 34} {} 1}
    {DU   75 {} 11 0 0 {Drain Will} {Discards one champion of adjusted level 9 or less in one pool. No champions in that pool may attack until after that player's next turn. (Off/3)} UC {} {27 32} {} 1}
    {DU   76 {} 18 0 0 {Eat Dirt!} {Opposing champion returns to his pool with his attachments. The battle may continue with a new champion. (Off/4)} C {} {27 33} {} 1}
    {DU   77 +5 18 0 0 {Vital Blow} {The opposing champion is sent to the Abyss if defeated, regardless of any special power he may have. (Off/4)} UC {} {27 33} {} 1}
    {DU   78 {} 18 0 0 {Supernatural Strength} {Usable only by any undead or dragon champion. The base level of this champion is doubled until the end of this round of combat. (Off/4)} C {} {9 27 33 41} {} 1}
    {DU   79 {} 3 0 0 {Create Minion} {Return one champion from your discard pile to your pool. The restored champion is now considered undead. (Def/3/5)} C {} {6 32 34} {} 1}
    {DU   80 +6 3 0 0 {Melt Bone} {Opposing champion must immediately play an ally or return to his pool defeated (discard all attachments). The battle may continue with a different champion. (Off/4)} UC {} {27 33} {} 1}
    {DU   81 {} 3 0 0 {Death Field} {One champion of base level 6 or higher is discarded. (Off/3)} UC {} {27 32} {} 1}
    {DU   82 {} 17 0 0 {Con Game} {All champions and their attachments in one opponent's pool are shuffled together. This player deals out the shuffled cards between he and their owner. This player then discards the cards dealt to him. The other player may immediately place the cards he was dealt back into his hand or into his pool. (Off/3)} R {} {27 32} {} 1}
    {DU   83 {} 17 0 0 {Legal Loophole} {This skill may be attached to any thief to allow all of this player's thieves to ignore the effects of any rule cards in play. Lasts until the attached thief is discarded. (Def//3)} C {} {6 32} {} 1}
    {DU   84 {} 17 0 0 {Tumble Out of Danger} {This skill may be played at any time to redirect a spell or event that targets the champion using this skill. It can be redirected at any champion in any pool or in battle. (Def)} UC {} {6 29 30 31 32 33 34} {} 1}
    {DU   85 +4 17 0 0 {Broad Jump} {When played in combat, this skill allows the attached thief to bypass a defending wizard, cleric, or psionicist and automatically raze the realm. The defending champion returns to his pool. (Off/4)} R {} {27 33} {} 1}
    {DU   86 {} 17 0 0 Hijacking {This skill may be played any time that another player is to receive cards from his draw pile as the result of an event, realm, artifact, champion, or holding's power. You may take an equal number of cards from your draw pile, and the other player must immediately discard his draws. (Off)} R {} {27 29 30 31 32 33 34} {} 1}
    {DU   87 {} 17 0 0 {Fortune Telling} {Play this skill on a champion in any opponent's pool and call odd or even. Then cut the owner's draw pile and check the card's last digit. If you are correct, the champion is sent to Limbo until his owner discards a champion with a base level equal to or higher than the champion's. If you are wrong, your opponent gets the card that you cut to and may play it immediately (if legal). (Off/3)} C {} {27 32} {} 1}
    {DU   88 {} 17 0 0 {Gather Information} {Look at the top 5 cards in any opponent's draw pile. If you choose, you may discard the champion using this skill to place the cards on the bottom of their draw pile. (Off/3)} C {} {27 32} {} 1}
    {DU   89 {} 17 0 0 Intimidation {Tell your opponent to break off the attack. If he does, the battle ends without spoils and nothing is razed. If he presses the attack, you may take the top 5 cards from your draw pile. Place any realms or holdings on the bottom of your draw pile. Any other cards may be played into the battle, regardless of restrictions (ie, multiple artifacts may be attached, spells may be used by nonspellcasters, etc). After combat is resolved, only legal cards may remain attached. (Def/4)} UC {} {6 33} {} 1}
    {DU   90 +5 17 0 0 Trailing {The attached thief can "follow" a champion that has just attacked a realm that has special movement or other restrictions. This champion may ignore those restrictions. Lasts until the attached champion is discarded. (Def/3)} C {} {6 32} {} 1}
    {DU   91 {} 19 7 0 {Extension I} {Castable only by AD&D champions. Can be cast to extend the duration of any spell or event that lasts until the start or end of your next turn. Draw and discard a card, noting the card number's last digit. This is the number of additional turns added to the duration. (Def/3/4/5)} C {} {6 32 33 34} {} 1}
    {DU   92 {} 19 6 0 {City Shield} {Castable only by Birthright champions. This spell prevents offensive spells from affecting any of your realms. Lasts until dispelled. (Def/3)} UC {} {6 32} {} 1}
    {DU   93 {} 19 5 0 {Spectral Dragon} {Castable only by Dragonlance champions. This spell creates a monstrous illusory dragon that sweeps through all opposing player's pools, sending all champions of base level 4 or less to the discard pile. (Off/3)} C {} {27 32} {} 1}
    {DU   94 +? 19 1 0 {Ball Lightning} {Castable only by Forgotten Realms champions. This spell increases in power; a champion gets 1 lightning ball for every 2 base levels he has, to a maximum of 4. Each lightning ball can add 3 to the caster's level or can destroy one opposing ally. (Off/4)} UC {} {27 33} {} 1}
    {DU   95 {} 19 2 0 {Drawmij's Beneficent Polymorph} {Castable only by Greyhawk champions. This spell allows the caster to fly, swim, or earthwalk, as desired. This champion may also copy the special powers of any champion in his pool. Lasts until the start of this player's next turn. (Def/3/4)} UC {} {6 32 33} {} 1}
    {DU   96 {} 19 3 0 {Animate Gargoyle} {Castable only by Ravenloft champions. This spell creates a flying monster champion whose base level is equal to twice the caster's adjusted level. This champion flies immediately to his pool and is in all ways treated as a normal monster. This spell may only be dispelled or negated when it is first cast. (Def/3/4)} R {} {6 32 33} {} 1}
    {DU   97 {} 19 0 0 {Minions of Darkness} {Castable only by drow or Underdark champions (UD). Cast when defending an Underdark realm, this spell allows this player's Triumvirate allies to be used in defense. They may not be discarded or forced to switch sides for any reason. (Def)} C {} {6 10 33 42} {} 1}
    {DU   98 +? 19 4 0 {Conjure Greater Fire Elemental} {Castable only by Dark Sun champions. This spell creates an ally equal in bonus to the base level of the caster. The greater fire elemental causes all magical items held by an opposing champion to be sent to the Abyss. (Off/4)} C {} {27 33} {} 1}
    {DU   99 {} 4 0 0 {Divine Assistance} {This spell negates the effects of all dungeon cards in play until dispelled. (Off/3/4)} C {} {27 32 33} {} 1}
    {DU  100 {} 15 7 0 {What Goes Around Comes Around} {Played at the beginning of the player's turn, this card is not discarded. It affects all players and remains in effect until any other rule card is played. All cards that allow a single player to draw extra cards into his hand (such as events, realms, artifacts, holdings, etc) allow all players to draw an equal number of cards instantly. This rule card can only be removed by playing another rule card. It is immune to champion powers, events, and the Wish spell.} C {} 29 {} 1}
    {DU  101 +5 2 7 0 {Winner's Trophy} {May be attached to a champion of any world. In combat, the attached champion may use any type of card playable in phase 4.} VR {} {6 27 32 33} {d3 o3 d4 o4 d101 o101 d9 o9 d11 o11 d17 o17 d18 o18 d102 o102 d19 o19} 1}
    {DU  102 +6 9 0 0 {Pretty Magical Ring} {The attached champion and his allies can fly, swim, or earthwalk as desired. This champion and his allies are immune to all cards that specifically target fliers, swimmers, or earthwalkers. (Def)} VR {} {6 32 33} {} 1}
    {DU  103 +? 18 0 0 {Fighting Dirty!} {Usable by any champion. Opposing player draws and discards a card, noting its last digit. The opposing player must immediately discard that many cards from his hand. (Off/4)} VR {} {27 33} {} 1}
    {DU  104 {} 19 0 0 Dissolution {One razed realm (this player's choice) is discarded. (Off/3/5)} VR {} {27 32 34} {} 1}
    {DU  105 {} 8 7 0 {Black Hand Thieves' Guild} {May be attached to any realm. While this holding is in play, all players must discard down to five cards any time they have nine or more cards in their hand.} VR {} 31 {} 1}
    {DU  106 {} 6 0 0 {Elminster's Intuition} {Name a card out loud. Immediately search an opponent's draw pile for that card. If you find it, send the card to the Abyss. If you don't find it, immediately send your foremost realm to the Abyss instead. (Harmful)} VR {} {22 29 30 31 32 33 34} {} 1}
    {DU  107 {} 6 0 0 {Fool's Paradise} {This charming fool distracts all of one player's non-monster champions, preventing them from performing any actions until this player's next turn. (Harmful)} VR {} {22 29 30 31 32 33 34} {} 1}
    {DU  108 6 16 2 0 Aliki {Halfling. Aliki can cast wizard spells. During combat, this cunning rogue can steal one magical item from an opposing champion. The item returns to its owner at the end of battle.} VR {} {21 32 33} {1 2 d9 o9 d17 o17 d19 o19} 1}
    {DU  109 5 7 1 0 {Lilac Hesabon} {Adventurer; elf; swimmer. Lilac's dog, Lightning, acts as a +3 ally to her or a fellow adventurer. Lightning can be discarded in combat to negate one offensive card.} VR {} {1 14 37 32 33} {1 2 d9 o9 d18 o18} 1}
    {DU  110 {} 6 0 0 {Enter Darkness Together} {Play this card to cancel the effects of any just-played event or spell. This event cannot be calmed, and it may only be negated by tearing up the card which this event was played on. If this happens, the original event or spell works normally. (Harmful)} VR {In online play, send this card to Out of Play (The Void) to "tear up" the card.} {22 29 30 31 32 33 34} {} 1}
    {DU  111 +3 2 7 0 {Recorder of Ye'Cind} {Usable by any champion. At any time, this player may look at any cards which are in play face down. Once per turn, this player may randomly pull half the cards from any player's hand and look at them.} VR {} {32 33} {} 1}
    {DU  112 7 7 2 0 {Telarie Willowind} {Can cast cleric spells. Telarie's unicorn steed acts as a +4 ally. If defending, she can teleport out of battle back to her pool with her attachments, though the realm is then razed.} VR {} {32 33} {1 2 d4 o4 d9 o9 d18 o18} 1}
    {DU  113 9 7 7 0 {The Llama King} {During battle, the Llama King may summon an army of llamas to aid him. The llamas act as a +9 ally that can trample one opposing ally (discarding it).} VR {} {32 33} {1 2 d9 o9 d18 o18} 1}
    {DU  114 5 16 5 0 {Necba the Wrathmaker} {Halfling (kender). Immune to offensive spells and harmful events. Opposing players must attack and raze a realm each turn or discard their highest level champion while Necba is in play.} VR {} {21 24 32 33} {1 2 d9 o9 d17 o17} 1}
    {DU  115 7 7 1 0 {Shan, Karate Master} {Double the bonus of any unarmed combat card. This champion hates magic and cannot use magical items or artifacts. Gains 2 levels for each spell, magical item, or artifact used against him.} VR {} {32 33} {1 d18 o18} 1}
    {DU  116 {} 6 0 0 Handmine {Keep this event in your hand. A player who looks into your hand and finds this card must immediately discard his entire hand and the card that allowed him to look. (Harmful)} VR {} {22 29 30 31 32 33 34} {} 1}
    {DU  117 5 7 2 0 {The Builder} {Dwarf; earthwalker. When in a pool, this champion allows a razed realm to be rebuilt by discarding only one card, instead of the normal three.} VR {} {12 13 32 33} {1 2 d9 o9 d18 o18} 1}
    {DU  118 +2 2 7 0 {Slorath's Gloves} {At the start of this player's turn, he draws a card from an opponents hand and sends it to Limbo. All such cards selected remain in Limbo while the Gloves are in play, returning to the player's hand when the Gloves are discarded.} VR {} {32 33} {} 1}
    {DU  119 4 20 2 0 {Rary's Apprentice} {Immune to harmful events. While this champion is in play, Rary cannot be discarded for any reason. If Rary loses a battle, he returns to his pool with his attachments. Rary can use all items attached to his apprentice, gaining 2 levels for each so used.} VR {} {32 33} {1 2 d9 o9 d19 o19} 1}
    {DU  120 10 16 1 0 {Poor Oriental Lord} {While this champion is in play, no cards marked "First Edition" can be played. All those already in play remain, but no new ones may be played.} VR {} {32 33} {1 2 d9 o9 d17 o17} 1}
    {DU  121 10 12 7 0 {Highmaster Illithios} {Underdark. Immune to offensive spells, magical items, and artifacts. Draw a card whenever a psionic power card is played.} VR (Def) {6 42 32 33} {1 2 d9 o9 d11 o11} 1}
    {DU  122 9 14 6 0 {Chaos Lord} {Can cast wizard and cleric spells. This champion is immune to harmful events and rule cards. Chaos Lord may be sent to the Abyss to rearrange all realms in all formations (this player's choice).} VR {} {32 33} {1 2 d3 o3 d4 o4 d9 o9 d19 o19} 1}
    {DU  123 +10 1 0 0 {Giant Troll} {Giant. This ally regenerates and remains in play for an entire attack on a realm; it is discarded only after the realm is razed or the attack discontinued.} VR {} {17 33} {} 1}
    {DU  124 5 16 7 0 {Elyk the Bard} {At the beginning of this player's turn, Elyk can choose to change into a wizard or hero. Elyk's legend lore ability confers immunity to the effects of any one artifact (chosen at the start of this player's turn) to his player.} VR {} {32 33} {1 2 d9 o9 d17 o17 d18 o18 d19 o19} 1}
    {DU  125 5 7 1 0 {Dor Amberglow} {Adventurer. Dor can cast wizard spells and is immune to offensive psionics. He can act as an ally for any other adventurer, returning to his pool after the battle.} VR {} {1 32 33} {1 2 d9 o9 d18 o18 d19 o19} 1}
}
