set CrossFire::cardDataBase {
    Inquisition
    {IQ    1 {} 13 2 0 {Castle Arborgate} {This realm is immune to offensive spells, psionics, and harmful events.  If discarded from any hand or deck by an opponent's action, put this realm into play and place all other Castle Arborgates in play in the Void regardless of any other cards special power.} C {} 31 {} 1}
    {IQ    2 {} 13 7 0 {The Shadowlands} {When played or rebuilt, this realm steals the power of any other realm in an opponent's formation, which is now considered to have no special power until this realm is razed or discarded.} C {} 31 {} 1}
    {IQ    3 {} 13 7 0 {Arena of Dori the Barbarian} {This realm is the home of combat.  In phase 4, in place of attacking a realm, any player during their turn, may attack another champion in an opponents pool.  The winner of this fight gets spoils.  The loser is goes to the discard pile, regardless of special powers.} C {} 31 {} 1}
    {IQ    4 {} 13 7 0 {Land of Legends} {When this realm is played, it may copy the world designation and special powers of any realm an opponent's formation, except Ancient Kalidnay, Menzoberranzan, or Avanil.} C {} 31 {} 1}
    {IQ    5 {} 13 7 0 {Hollow World} {Underdark.  This realm extends under all opponent's AD&D realms, allowing them to be attacked by this player's champions and allies, regardless of position or movement restrictions.} C {} {42 31} {} 1}
    {IQ    6 10 13 7 0 {The Oracle at Delphi} {Can defend itself as a level 10 cleric that is immune to the powers of opposing champions.  If this realm is razed, the attacker may search his draw pile and put any rule card into play.  If successfully defended, the defender may do so instead.} C {} 31 {1 d4 o4} 1}
    {IQ    7 7 13 7 0 Bastion {During this players phase 0, this player can send any other non-realm card in play to the Void by razing another realm in this players formation and discarding this realm to the Void.} C {} 31 1 1}
    {IQ    8 {} 13 5 0 Thorbardin {Thorbardin is immune to offensive spells and can only be defended by dwarves.  Any dwarf defending this realm can be sent to the abyss to seal its mighty gates.  The attacker returns to its pool and the battle ends with no spoils.} C {} 31 {} 1}
    {IQ    9 1 13 2 0 Quasqueton {This realm can only be attacked by champions of base level 5 or less.  If the attacking champion is defeated, all attached magic items and artifacts stay with this realm (until it is razed or discarded) and can be used by its future defenders (regardless of world designations for artifacts).} C {} 31 1 1}
    {IQ   10 {} 13 2 0 {Village of Nulb} {While this realm is in play, the Temple of Elemental Evil cannot be played.  If played when the Temple of Elemental Evil is already in play, that player must immediately discard 3 cards at random from his hand.} C {} 31 {} 1}
    {IQ   11 {} 8 6 0 {Adventurer's Guild} {During this players phase 0, this player may return all adventurers from his discard pile to his hand by sending this holding to the Abyss.  All of adventurers in play gain 1 level and are immune to thief skills.} C {} 31 {} 1}
    {IQ   12 {} 8 7 0 {Castle Moovania} {This holding can be attached to any realm.  Draw 2 extra cards during your draw phase, but your hand size is reduced by 4.} C {} 31 {} 1}
    {IQ   13 -1 8 7 0 {Trojan Horse} {Attach this holding to any realm belonging to another player.  The realm may be attacked by any player, regardless of position or restrictions, and each defending champion defends at a -1 from his adjusted level.  The attacker chooses who will defend.} C {} 31 {} 1}
    {IQ   14 0 7 7 0 {Mij Reltub, the Spellfire Oracle} {This champion may be sent to the Void from pool or hand to stop any event or spell that razes or discards realms.  The card stopped is also put into the Void.} C {} {29 30 31 32 33 34} {1 2 d9 o9 d18 o18} 1}
    {IQ   15 6 12 4 0 {Tagor Migor} {In combat, this champion may use his chameleon power to make his allies (only) immune to the special power of opposing allies for the remainder of this combat round.} C {} {32 33} {1 2 d9 o9 d11 o11} 1}
    {IQ   16 5 14 6 0 {The Enchantress} {Can cast wizard spells.  Before combat, only when defending, she can enchant the opposing champion, causing the champion to lose its special powers for the duration of this combat round.} C {} {32 33} {1 2 d3 o3 d9 o9 d19 o19} 1}
    {IQ   17 2 20 5 0 {Saldon the White} {This champion can double the level of any card in play once per combat round, even in a combat where he is not involved.  Between 6AM and 6PM, he can double the level of any one additional card in a combat in which he is involved.} C {} {32 33} {1 2 d9 o9 d19 o19} 1}
    {IQ   18 4 5 7 0 {Orcish Shaman} {Orc.  Can cast wizard spells.  This champion's Orc tribe counts as a permanent +5 ally for this champion.} C {} {28 32 33} {1 2 d4 o4 d9 o9 d19 o19} 1}
    {IQ   19 5 12 2 0 {Aramil of Tusmit} {This champion is immune to psionic power cards.  During combat, Aramil may use his superior mind control powers to steal a just played opposing ally.} C {} {32 33} {1 2 d9 o9 d11 o11} 1}
    {IQ   20 ? 10 7 0 {Dragon Mountain Kobold} {Limit per deck: Up to the Maximum number of champions per deck.  Immune to Rule of the Cosmos. Adjusted level is equal to the number of Dragon Mountain Kobolds in play.  If Infryana and Dragon Mountain are in play and belong to the same player, all Dragon Mountain Kobolds in play go to that players pool.  If either leave play, then all Kobolds in play are discarded.} C {No limit per deck.} {25 32 33} {} 1}
    {IQ   21 5 7 7 0 Luccia {Adventurer. Flyer.  Can use thief skills.  Luccia has a +7 flying griffin mount as her ally and makes Luccia a flyer.  She is a great scout, thus when she is in the pool, all adventures may use their special powers (and those of attached cards) first when defending.} C {} {1 16 32 33} {1 2 d9 o9 d17 o17 d18 o18} 1}
    {IQ   22 9 7 7 0 {Mij Draw, the Epitome of Purity and Might} {If this champion wins a round of combat while attacking, he may look through his draw pile and put into play any (obviously) female champion as a "groupie".  If he successfully defends a realm, he gets a number of spoils equal to the number of "groupies" in his pool.} C {} {32 33} {1 2 d9 o9 d18 o18} 1}
    {IQ   23 8 7 2 0 Karistyne {Adventurer.  Can use cleric spells.  If owned by a player with at least 3 other adventurers, none of this player's adventurers can be sent to the abyss for any reason by any player (even this one).} C {} {1 32 33} {1 2 d4 o4 d9 o9 d18 o18} 1}
    {IQ   24 9 5 4 0 Silversun {Silversun was driven insane in her quest for a balance between good and evil.  If she attacks and wins a round of combat, the realm is razed, but she is discarded.} C {} {32 33} {1 2 d4 o4 d9 o9} 1}
    {IQ   25 10 5 2 0 {Jerome Kazinskaia} {Jerome does not need permission to cast any cleric spell.  During this players turn, Jerome may do one of the following: During phase 3, he may retrieve from his discard pile any non-undead/werebeast ally.  Or, during phase 5, he may retrieve any one defensive cleric spell from the discard pile.} C {} {32 33} {1 2 d4 o4 d9 o9} 1}
    {IQ   26 ? 10 3 0 {The Grim Reaper} {Undead. The number of champions and allies currently in all discard piles and abyss's determines this champion's level.} C {} {40 32 33} {1 2 d9 o9 d102 o102} 1}
    {IQ   27 7 7 4 0 {Aria Kyra} {Halfling.  Can use thief skills.  Champions of base level 6 or higher cannot defend against this champion.} C {} {21 32 33} {1 2 d9 o9 d17 o17 d18 o18} 1}
    {IQ   28 7 5 2 0 Sarana {Immune to offensive wizard spells.  This champion can be sent to Limbo until the end of this player's next turn to prevent one non-event card from going to the Abyss.} C {} {32 33} {1 2 d4 o4 d9 o9} 1}
    {IQ   29 6 5 2 0 {Kiri Allavesse} {Elf.  Can cast wizard spells.  If Kiri razes a realm, this player can choose to retrieve (and play) a non- realm card from his discard pile, instead of taking normal spoils.} C {} {14 32 33} {1 2 d4 o4 d9 o9 d19 o19} 1}
    {IQ   30 5 5 1 0 Vargas {Dwarf. Earthwalker.  Vargas is accompanied by an earthwalking earth elemental ally whose level is twice the number of unrazed realms in play.  This ally is immune to the powers of flyers and all their attached cards.} C {} {12 13 32 33} {1 2 d4 o4 d9 o9} 1}
    {IQ   31 1 7 7 0 Etarkine {Adventurer.  Halfling.  Etarkine is immune to offensive magic items.  Before combat, you must play "rock, paper, scissors" with the opponent.  The winner wins the round of battle and the loser is discarded.  If the game is a draw, the battle continues normally.} C {} {1 21 32 33} {1 2 d9 o9 d18 o18} 1}
    {IQ   32 10 7 2 0 {Gib Ergo} {Immune to events. No spell may be cast at this champion or at any pool he currently occupies.  This player must attack each turn (at least once), or raze one of his own realms.} C {} {32 33} {1 2 d9 o9 d18 o18} 1}
    {IQ   33 7 7 1 0 {Adamar Session} {Can use any cleric from any pool as an ally in battle.  If victorious in combat, Adamar may retrieve one card from the owning player's discard pile or abyss.  Both Adamar and the recovered card are then shuffled into the draw pile.} C {} {32 33} {1 2 d9 o9 d18 o18} 1}
    {IQ   34 9 10 7 0 {The Devourer} {This champion must attack on the owning players' turn or be sent to the abyss.  It is immune to all cards that prevent attacks from occurring and the powers of all realms and holdings.  If the Devourer wins a round of combat, the owning player may send one champion in any players' pool to the abyss.} C {} {32 33} {1 2 d9 o9} 1}
    {IQ   35 6 12 4 0 Ba'Thrang {If this champion attacks a realm that has the capability to defend itself, he can psionically force the realm champion to defend against him in battle.  (off)} C {} {32 33} {1 2 d9 o9 d11 o11} 1}
    {IQ   36 7 14 6 0 {Morgan Rynes} {May cast defensive Cleric spells.  After a winning a round of combat, Morgan may choose to show mercy upon the defeated champion, letting the champion return to his pool with all attached cards.  Morgan then may draw one card for each card the goes back to the opponents pool (not as spoils).} C {} {32 33} {1 2 d3 o3 d4 d9 o9} 1}
    {IQ   37 5 20 2 0 Otiluke {Gains 4 levels after being declared as an attacker or defender.  All spells cast by Otiluke with a numerical bonus are doubled in level.  If Otiluke draws a wizard spell as spoils, he may cast that spell and then draw the next card as spoils also.} C {} {32 33} {1 2 d9 o9 d19 o19} 1}
    {IQ   38 9 20 2 0 Nystul {Once per turn, Nystul may cast a +7 Radiant Arch (4/off) into battle to aid another champion, discarding one ALREADY attached card of Nystul's choice.  Nystul's ability at disguise allows him to ignore any cards that defeat or discard wizards.} C {} {32 33} {1 2 d9 o9 d19 o19} 1}
    {IQ   39 8 20 2 0 {Jallazari Sallavarian} {During combat over a Greyhawk realm, she may use any Greyhawk champion as an ally.  Jallazari goes to limbo if defeated defending a GH realm, returning at the end of the owning players next turn.} C {} {32 33} {1 2 d9 o9 d19 o19} 1}
    {IQ   40 8 20 2 0 {Treemon Crosse} {Elf.  Can use Hero Unarmed Combat cards and thief skills.  Treemon, a master infiltrator, can always see any pool that is face down.  Before battle as a defender only, Treemon can send the attacking champion back to its pool and choose a different champion to attack instead.} C {} {10 14 32 33} {1 2 d9 o9 d17 o17 d18 o18 d19 o19} 1}
    {IQ   41 6 5 7 0 {Torgo, the Mad Scientist's Assistant} {During phase 3, while this champion is in play, any two allies can be combined (levels added together) into a single monster champion.  This champion keeps the powers of the allies as its own.  Any champions formed this way stay in play even if Torgo leaves play.} C {} {32 33} {1 2 d4 o4 d9 o9} 1}
    {IQ   42 {} 6 0 0 {Unavailing Sacrifice} {Play this event after a player has discarded or put a card into the abyss in order to perform or activate a special power.  The power granted by the "discard" is wasted.  (Harmful)} C {} {22 29 30 31 32 33 34} {} 1}
    {IQ   43 {} 6 0 0 {The Gathering} {When played, this player may search his deck for up to 10 levels of non-avatar champions (4 maximum) and place them in his hand. (Helpful)} C {} {23 29 30 31 32 33 34} {} 1}
    {IQ   44 {} 6 0 0 {Pangea Effect} {All dungeon cards in play move clockwise one player.  Players my discard a wizard during their phase 3 to move them again in the same direction.  This event remains in play until canceled.  (Harmful)} C {} {22 29 30 31 32 33 34} {} 1}
    {IQ   45 {} 6 0 0 {Dragons Turn the Tide} {If a dragon razes a realm though combat, that player's champion may immediately rebuild one of his own realms.  This event lasts until the end of the event player's next turn.  (Helpful)} C {} {23 29 30 31 32 33 34} {} 1}
    {IQ   46 {} 6 0 0 {An Eye for an Eye!} {An opponent who just forced a discard of one (or more) of this players champions or realms, must now discard the same amount and same type as those discarded, chosen by this player.  This card may not be duplicated, deflected, or canceled.  (harmful)} C {} {22 29 30 31 32 33 34} {} 1}
    {IQ   47 {} 6 0 0 {The Apocalypse} {Each player chooses one of each card type that they have in play, if any.  All other cards in play are discarded regardless of any special powers that they may have (including Chernivik).  Players then reshuffle their hands, draw piles and discard piles into a new draw pile and draw 5 new cards.  Cannot be canceled, calmed, duplicated, or EDT'd.  This event can only be played once per game. (Harmful)} C {This event may not be played if you have ever had three or more realms in play at the same time.} {22 29 30 31 32 33 34} {} 1}
    {IQ   48 {} 6 0 0 {A Good Defense} {This event cannot be used by a player with the Azure Tower of Onad the Fallen in play.  All abilities and cards owned by this player are considered defensive (or helpful).  This event lasts until negated.  (Helpful)} C {} {23 29 30 31 32 33 34} {} 1}
    {IQ   49 {} 6 0 0 Cheat!!! {The player of this event can choose one of the following 3 effects: a) Draw 2 cards. (Helpful)  b) Look at all hands and discard 1 card from each (even his own). (Harmful)  c) All players may unraze one realm, then this player can unraze another of his choosing, but only if everyone unrazes a realm. (Helpful)} C {} {23 29 30 31 32 33 34} {} 1}
    {IQ   50 {} 21 7 0 {Hall of King Snurre the Fire Giant} {All of this player's giants gain 4 levels.  Allies of icon level +4 or less cannot be played against this player's giants.} C {} {} {} 1}
    {IQ   51 {} 21 7 0 {Level Playing Field} {This player is not effected by any cards that cause instant defeats or by any cards that require permission to use cards.} C {} {} {} 1}
    {IQ   52 {} 21 7 0 {The Guild of Adventurers} {If this player has an adventurer discarded outside of combat, he may replace it by searching for any adventurer in his deck and put it into his pool.} C {} {} {} 1}
    {IQ   53 {} 15 7 0 {Spite and Malice} {When played, all players name one other card.  The named cards have no special power while this rule card is in play.} C {} 29 {} 1}
    {IQ   54 {} 15 7 0 {Out of Phase} {Played at the beginning of this player's turn, this card is not discarded.  It affects all players and remains in effect until another rule card is played.  Each player may exchange up to 2 phases of his current turn (phases 1, 2, and/or 3 only) for an additional phase 4 for each phase given up.  Each phase 4 ends when a spoils is drawn by the acting player, the attacking champion is defeated in combat, or card play causes the round of combat to end in a draw.  Spoils are drawn normally during each phase 4.} C {} 29 {} 1}
    {IQ   55 +3 2 1 0 {Tymora's Coin} {This player is immune to "A Sure Thing" rule card. When forced to draw and discard noting the last digit, this player may look at his top 3 cards of his draw pile and choose which one to use.} C {} {32 33} {} 1}
    {IQ   56 +3 2 5 0 {Staff of Mishakal} {Usable only by clerics of any world.  During phase 5, if this champion did not attack, the staff resurrects one champion from either the Abyss to the discard pile, or from the discard pile to the draw pile, which is then reshuffled.} C {} {32 33} {} 1}
    {IQ   57 +6 2 5 0 {The Shield Tree} {May only be attached to any Dragonlance realm.  During this players phase 0, you MUST discard a champion or ally from your pool or hand or the Shield Tree is discarded.  The attached realm and any champion defending this realm is immune to the special powers of all offensive cards.} C {} {32 33} {} 1}
    {IQ   58 +1 9 0 0 {Holy Symbol} {Usable only by any cleric.  During combat, subtract the base level of this champion from the base level of any one undead in play.  If the undead champion or ally drops below level 0 it is discarded.  (off)} C {} {27 32 33} {} 1}
    {IQ   59 +3 2 1 0 {Monacle of Bagthalos} {No pool is considered hidden for this player.  Any choices at a "face down" pool are made face up to this player.  Once during each opposing players turn, this champion can halve the base level (round down) of any champion during a combat in which this player is not involved.  (Off)} C {} {27 32 33} {} 1}
    {IQ   60 +2 2 7 0 {The Tomes of Spellfire} {Usable by champions of any world.  When the attached champion is victorious in a round of battle, this player may shuffle and cut any players draw pile, then look at the top three cards and remove one to the abyss.  (Off)} C {} {27 32 33} {} 1}
    {IQ   61 +2 9 0 0 {Wand of Enemy Detection} {In a combat round, this enchanted wand allows the attached champion to activate his powers and attachments first.  (def)} C {} {6 32 33} {} 1}
    {IQ   62 +2 9 0 0 {Scarab of Death} {When the attached champion is defeated, this magic item attaches to the opposing champion.  That champion's player draws and discards a card, noting the cards last digit.  The opposing champion is discarded to the abyss after that many turns (or immediately if the player doesn't or cannot draw and discard a card), unless he can discard the scarab.  This magic item returns to the original owners discard pile when discarded. (def)} C {} {6 32 33} {} 1}
    {IQ   63 {} 9 0 0 {Nosrenda's Amulet} {While this magic item is in play, no card maybe duplicated, copied, or imitated.  (def)} C {} {6 32 33} {} 1}
    {IQ   64 {} 9 0 0 Bandage {This magic item may also be played onto a champion that has just lost a combat for any reason.  The attached champion goes back to its pool with all attachments (including allies).  Then this magic item is discarded.  (def)} C {} {6 32 33} {} 1}
    {IQ   65 +10 9 0 0 {Murlynd's Spoon} {This magic item cannot be discarded by an opponent, or by any card an opponent controls.  (Def)} C {} {6 32 33} {} 1}
    {IQ   66 +8 2 7 0 {Mystical Orb of the Black Eight} {Can be attached to any champion regardless of world restrictions.  This artifact of random answers also gives an opposing champion a level bonus equal to the last digit of the last card played into battle, on either side.  This power and the level bonus are defensive in nature.} C {} {32 33} {} 1}
    {IQ   67 +5 9 0 0 {Ogre's Horned Helm} {This magic item may be discarded from the hand or pool to cancel a just played counter effect card.  This power even works on Enter Darkness Together, but then it goes to the abyss.  (def)} C {} {6 29 30 31 32 33 34} {} 1}
    {IQ   68 +6 9 0 0 {Orb of Delight} {During phase 3 or 5 (but not both in the same turn), this player can return to his hand from the discard pile any two non-undead allies.} C Def {6 32 33} {} 1}
    {IQ   69 {} 4 0 0 Atonement {Place this card and the caster into the abyss, then take any other card from your abyss and put it into play.  (def)} C {} {6 32} {} 1}
    {IQ   70 {} 19 0 0 Reincarnate {This spell returns any one non-avatar champion from your discard pile to your pool, but changes the icon of the returned champion to that other than the one shown on the card.  The casting player chooses the new icon.  The other abilities of the returned champion are unchanged.} C Def {6 32} {} 1}
    {IQ   71 {} 19 0 0 Stoneskin {May be cast at any time to counter any just played unarmed combat card, and makes the champion immune to unarmed combat cards for the duration of that combat round.} C {} {6 29 30 31 32 33 34} {} 1}
    {IQ   72 +1 1 0 0 Gen {Can only be attached to a wizard, to whom it becomes a familiar.  Once attached, Gen MAY search this players draw pile for any spell that can be cast during phase 4.  The spell must be shown to all players.  After retrieving the spell, the Gen is then shuffled back into the draw pile.} C {} {15 33} {} 1}
    {IQ   73 {} 3 0 0 {The King's Justice} {Lasts until dispelled.  If a thief skill is used while this ability is in play, the thief using the skill is sent to limbo until this ability is dispelled.} C {} 32 {} 1}
    {IQ   74 {} 4 0 0 Gate {The caster can use any champion (except an avatar) from another player's draw or discard pile as an ally for this round of combat.  At the end of the round, this champion/ally is sent to Limbo until the end of the actual owner's next turn.  (off/4)} C {} {27 33} {} 1}
    {IQ   75 {} 4 0 0 Repentance {Can be cast at any time to negate a thief skill.  If used on a just played thief skill, the thief attempting to use the skill is discarded.  (def)} C {} {6 29 30 31 32 33 34} {} 1}
    {IQ   76 {} 11 0 0 {Time Travel} {This player can take another turn after his current turn is finished, starting with his phase 3 (skipping phases, 0, 1, and 2).  This card is placed in the Void after its successful use.  If canceled, it goes to the discard pile.  (def/5)} C {} {6 34} {} 1}
    {IQ   77 {} 17 0 0 {Double Cross} {Usable by any champion.  Play in response to another Offensive Thief skill to turn that skill back upon the original player.} C Def {6 27 29 30 31 32 33 34} {} 1}
    {IQ   78 {} 18 0 0 Slap! {Usable by non-spell casting champions.  This maneuver disrupts the concentration of any champion, canceling the effects of a just played spell, blood ability, psionic power, or thief skill.} C Off {27 29 30 31 32 33} {} 1}
    {IQ   79 {} 19 0 0 Permanency {Cast this spell on a spell with a stated duration, which then becomes permanent.  The original spell cannot be dispelled until this spell is dispelled.  Permanency can always be dispelled, regardless of special powers.  The caster of this spell cannot be used again until the end of the owning players next turn.  (def)} C {} 32 {} 1}
    {IQ   80 {} 19 0 0 Contingency {When this spell is cast, this champion can retrieve any spell that can be cast in phase 4 and place it underneath the retrieving champion.  When he enters a round of combat, this spell is considered cast before combat begins.  (def)} C {} 32 {} 1}
    {IQ   81 {} 18 0 0 Tankity-Tankity-Tank {Usable by any champion of level base level 7 or higher.  This card allows the using champion (if victorious in this round of combat) to steam-roll over the defeated champion to raze the attacked realm.  (def)} C {} {6 33} {} 1}
    {IQ   82 +? 19 0 0 {Imaginary Friend} {This spell creates an ally equal to the base level of the casting champion.  This ally may not be stolen or discarded by any means.  The ally stays with the champion until dispelled or until the champion is discarded.  (Def 3/4)} C {} {6 32 33} {} 1}
    {IQ   83 {} 19 0 0 {Dispel Illusion} {This spell may be cast at any time.  This spell prevents a card from being played (return it to the players hand).  The card is considered to have been "not played", and cannot be played again until that players next turn.  (off)} C {} {27 29 30 31 32 33} {} 1}
    {IQ   84 {} 4 0 0 Curse {This spell causes a magic item or artifact to be cursed.  The cursed item no longer has any special powers and any level bonus granted by it is now subtracted from the champion's base level.  Any champion reduced to 0 or below are discarded.  (Off 3/4)} C {} {27 32 33} {} 1}
    {IQ   85 {} 11 0 0 {I know what you are thinking!!!} {While this power is in play, all opponents must now play with their hands face up on the table.  This power lasts until negated.} C Def {6 32} {} 1}
    {IQ   86 +7 1 0 0 {White Dragon} {Dragon. Flyer. Can use dragon unarmed combat cards.  This ally's breath weapon, a cone of cold, causes all magic items currently in the battle to break and be discarded.} C {} {8 16 33} {d101 o101} 1}
    {IQ   87 +8 1 0 0 {Soth's Steed} {Undead.  Flyer.  May breathe fire to discard one ally or magic item of +5 or less currently in combat.  If played with Lord Soth, this ally doubles in level and cannot be discarded or forced to switch sides, returning to the pool with Lord Soth at the end of combat.} C {} {16 40 33} {} 1}
    {IQ   88 +? 1 0 0 Mimic {During combat, this ally can copy any one magical item or artifact attached to the opposing champion.} C {} 33 {} 1}
    {IQ   89 +5 1 0 0 {Mina's Knights} {May play hero unarmed combat cards.  If played with a cleric, this ally cannot be forced to switch sides and are only discarded if the cleric is discarded also.} C {} 33 {d18 o18} 1}
    {IQ   90 +1 1 0 0 {Stool Pigeon} {When played in combat, an opposing thief champion is defeated and sent to the abyss.} C {} 33 {} 1}
    {IQ   91 +3 1 0 0 Gloomwing {Flyer.  Because of its shimmering markings, an opposing champion is confused and loses the use any special abilities and its icon ability during this round of combat.} C {} {16 33} {} 1}
    {IQ   92 +? 1 0 0 {Knights of Neraka} {This army is equal in level to the attached champion's base level.} C {} 33 {} 1}
    {IQ   93 +5 17 0 0 {Improved Initiative} {Play this card when both attacker and defender have been chosen.  The player of this card activates all of their cards first.  (def/4)} C {} {6 33} {} 1}
    {IQ   94 {} 17 0 0 Hostage {Play on any champion in any opponent's pool before a defender is chosen.  If the attacker doesn't halt the attack, the hostage is sent to the discard pile.  (off/4)} C {} {27 33} {} 1}
    {IQ   95 +9 1 0 0 Mercenaries {One card from this player's hand must be discarded to purchase the service of the mercenaries.  When played, the player can choose any one type of support card that can be played by them.} C {} 33 {d3 o3 d4 o4 d101 o101 d11 o11 d17 o17 d18 o18 d102 o102 d19 o19} 1}
    {IQ   96 {} 17 0 0 Entrapment {Play at any time to cancel a just played thief skill and send its user to the discard pile. (def)  Can be played during phase 3 or 5 to send one thief champion to Limbo. (Off)} C {} {29 30 31 32 33 34} {} 1}
    {IQ   97 +10 1 0 0 Behir {Earthwalker.  During combat, this ally can release a bolt of lightning that renders the opposing champions magical items powerless for this round of combat.} C {} {13 33} {} 1}
    {IQ   98 +4 3 0 0 {Claws of the Wolf} {Stays with the champion until dispelled or the champion is defeated.  This champion can discard one opposing ally of level 7 or less.  (Off /3/4)} C {} {27 32 33} {} 1}
    {IQ   99 {} 17 0 0 {A Piece of the Action} {Play only when another player is to draw a spoils of victory.  That player must draw and discard his spoils, while this player draws a card showing it to all players.  If it is a realm card, it is sent to the Abyss.  Otherwise it may be played just like a spoils of victory.} C Off {27 33} {} 1}
}
