set CrossFire::cardDataBase {
    Millennium
    {MI    1 +2 1 0 0 Duergar {Dwarf. The next card played by the opponent that is not defensive, loses its special power and level bonus (discarding Leber).  May also be discarded from hand to negate the effects of the Blamblower.} C {} {12 33} {} 1}
    {MI    2 +6 1 0 0 {Mountain Dwarf} {Earthwalker.  Automatically defeats a monster if attached to a hero.  Automatically defeats an undead if attached to a cleric.} C Dwarf {12 13 33} {} 1}
    {MI    3 +5 1 0 0 {Ranger of the Highlands} {No more than one card of any type can be played against the attached champion.} C {} 33 {} 1}
    {MI    4 +2 1 0 0 {Olive Slime} {When played into combat, discard all the attached cards currently in battle on both sides, and only Olive Slime remains.} C {} 33 {} 1}
    {MI    5 +5 1 0 0 {Locust Plague} {Earthwalker.  Play on an opposing realm during phase 3.  Acts as an ally for any champion attacking the realm.  Stays with razed realm, if not discarded through combat, which cannot be rebuilt while Locust Plague is attached to it.} C {} {13 32} {} 1}
    {MI    6 -5 1 0 0 {Bumbling Idiot} {Can be played into any combat on any champion.  The champion and all of its attached cards (except this one) lose all abilities.} C {} 33 {} 1}
    {MI    7 +8 1 0 0 {Death Knight} {When played, discards an ally already in play.  If attached to an attacking champion who is defeated in combat, Death Knight becomes a level 8 undead monster champion who returns to its controller's pool.} C Undead {40 33} {} 1}
    {MI    8 +6 1 0 0 Aurumvorax {Earthwalker.  For each card played into combat by the opponent, roll 2d4 and add that number to the level of this ally.} C {} {13 33} {} 1}
    {MI    9 +4 1 0 0 {Crypt Thing} {Can only be attached during phase 3 to a realm with a holding.  Cannot be discarded during combat by another player.  May be discarded at any time to send an opposing champion attacking the attached realm to Limbo.} C {} 32 {} 1}
    {MI   10 +1 1 0 0 Shrieker {Can only be attached during phase 3 to an Underdark realm.  This fungus alerts defenders, allowing them to activate their powers first.  "When attacking" and "Before combat" powers of champions owned by opponents do not work while this ally is in play.} C {} 33 {} 1}
    {MI   11 +? 1 0 0 {Blink Dog} {May be played into a combat where this player is not involved.  When played into combat, roll 2d4 for the level of this ally.  Can blink back to its owner's hand at any time, before combat ends.} C {} 33 {} 1}
    {MI   12 +4 1 0 0 {Reef Giant} {Gains 6 levels if in combat over a coastal realm.  All non-swimming champions and allies in combat against the Reef Giant lose 2 levels.} C Giant {17 33} {} 1}
    {MI   13 +5 1 0 0 {Desert Giant} {Gains 5 levels if in combat over a Dark Sun realm.  All swimming champions and allies in combat against the Desert Giant lose 2 levels.} C Giant {17 33} {} 1}
    {MI   14 10 20 7 0 {Feinoue, Void Shaper} {If Feinoue wins a round of battle, he can either randomly draw one card from the opponents draw pile to send to the Void and then he goes to limbo for 1d10 turn; or he can search the opponents deck for one card and send it to the Void and he then goes to the Void also.} C {} {32 33} {1 2 d9 o9 d19 o19} 1}
    {MI   15 +3 1 0 0 Cooshie {Gains 6 levels if allied with an elf.  Can be attached during phase 3 to any elf champion, staying with the champion until defeated or discarded during combat.} C {} 33 {} 1}
    {MI   16 +8 1 0 0 Phoenix {Flyer.  During phase 0, if this ally is in the discard pile, roll 2d6.  If doubles are rolled, put this ally into the abyss, otherwise return this ally to its owner's hand.} C {} {16 33} {} 1}
    {MI   17 +4 1 0 0 Cockatrice {Flyer.  When this ally is played, roll 2d6.  If the roll is higher than the opposing champion's base level, that champion is turned to stone and sent to the abyss.  If equal to the opponent's base level, this ally is turned to stone and sent to the abyss.} C {} {16 33} {} 1}
    {MI   18 +5 1 0 0 Solrac {Can be discarded from combat or hand to cancel a just played thief skill or blood ability.} C {} {29 30 31 32 33 34} {} 1}
    {MI   19 +1 2 4 0 {Defilers Crown} {Whenever any player casts an offensive spell, he must raze a realm in his own formation.  If a realm cannot be razed, then the spell may not be cast.} C {} {32 33} {} 1}
    {MI   20 {} 17 0 0 Gamblin' {Choose 3 champions of a single opponent and shuffle them, leaving the attachments behind.  Have that opponent name one of the champions, who must be selected by picking a card at random.  If correctly picked, all three are returned, if not, the two non-selected champions are discarded.  (Off 3)} C {} {27 32} {} 1}
    {MI   21 {} 2 2 0 Doomgrinder {When Doomgrinder is in play, any cards that make any player draw more (or less) cards than anyone else are discarded and none may be played either.} C {} 31 {} 1}
    {MI   22 {} 17 0 0 {Rigged Dice} {Playable at anytime before there is a die (or dice) roll to be made.  The player of this skill chooses the results of the roll instead of an actual roll.  (Off)} C {} {27 29 30 31 32 33 34} {} 1}
    {MI   23 +3 2 3 0 {Strahd's Medallion} {This artifact transforms the attached champion into a flying, undead vampire.  If attached to Strahd, all of this players champions become flying, undead vampires.} C {} {32 33} {} 1}
    {MI   24 {} 17 0 0 {Jail Break} {May be played at any time to return all champions and allies that are controlled by another player, back to their original owners.  Discard any cards that are attached to them.  (Def)} C {} {6 29 30 31 32 33 34} {} 1}
    {MI   25 {} 2 7 0 {Egg of Emulation} {The Egg may be used at any time to negate any event (sending the egg to the discard pile).  If the negated event was harmful, this player may smash the Egg (sending it to the abyss instead) to make a copy of the negated event.} C {} {32 33} {} 1}
    {MI   26 {} 17 0 0 {Under Handed Deal} {Playable when this player is forced to discard cards by an opponent.  Instead, this player now draws the amount of cards that would have been discarded.  (Def)} C {} {6 29 30 31 32 33 34} {} 1}
    {MI   27 {} 2 1 0 {Treasures of Netheril} {During this player's phase 0, this player must roll 1d4 and perform the following:  1) Search for one ally in their draw pile.  Show it and place it into their hand.  2) As 1, but for a magic item or artifact.  3) Move to phase 2 skipping phase 1.  4) Shuffle any one card in any discard pile into its owners draw pile.} C {} {32 33} {} 1}
    {MI   28 +5 2 7 0 {Crown of Dragon Royalty} {Usable only by any dragon champion.  The crown grants the wearer immunity to offensive spells, blood abilities, and thief skills.  If used by a dragon avatar, the immunities extend to all dragon champions in the player's pool.} C {} {32 33} {} 1}
    {MI   29 {} 3 6 0 Corruption {Usable only by Awnshegh.  Place a champion in another player's pool in yours with this card attached.  The corrupted champion remains under this players control until either it or Corruption is discarded.  (Off 3)} C {} {27 32} {} 1}
    {MI   30 {} 2 5 0 {Bloodstone of Fistandantilus} {Can only be attached to any wizard.  If the wizard using this artifact wins a round of battle, he can take the special power of the opposing champion, if it went to the discard pile.  The power is additional to his own.} C {} {32 33} {} 1}
    {MI   31 {} 3 6 0 {Absorb Spell} {May be played at any time.  This card makes the user of this blood ability the target of an offensive spell.  Both the user of this ability and the spell are sent to the abyss.  (Def)} C {} {6 29 30 31 32 33 34} {} 1}
    {MI   32 +2 2 3 0 {Madame Griselda's Tarroka Deck} {Every time this artifact goes into battle, draw a card for a bonus (place it underneath).  If the last digit is a 9, discard the attached champion.  Otherwise, the total bonus of the deck is equal to 2 plus the sum of last digits of all cards under the deck.  If the deck leaves play, all of the cards under it (including events) go to the discard pile.} C {} {32 33} {} 1}
    {MI   33 {} 3 6 0 {Law & Order} {Playable at any time to cancel a just played thief skill.  The player of the thief skill must discard one card from hand, pool, or formation for each thief in his pool.  (Def)} C {} {6 29 30 31 32 33 34} {} 1}
    {MI   34 +3 2 3 0 {The Forgotten Idol} {When entering combat, the attached champion may use the idol's influence to have one champion from any pool battle instead.  Win or lose, the stolen champion and the Idol are discarded after combat.} C {} {32 33} {} 1}
    {MI   35 +? 3 6 0 {Desperate Consultation} {Roll 1d6 for the bonus of this card.  If the die value is greater than the number of cards in your hand, draw that many cards.  (Def/4)} C {} {6 33} {} 1}
    {MI   36 {} 2 7 0 {Ring of Displacement} {Usable by any champion.  Whenever any player draws extra cards (beyond the 3 allowed for their draw phase and spoils), they must also discard an equal number from hand, pool, or formation.} C {} {29 30 31 32 33 34} {} 1}
    {MI   37 {} 4 0 0 {Sacred Flame} {The cleansing power of the fire allows this player to remove any card currently attached to any champion, regardless of special powers. (Off 3/5)} C {} {27 32 34} {} 1}
    {MI   38 -1 4 0 0 Consequence {All cards that say "copy", "copies", "imitates", "imitate", "mimic", "mimics", "duplicate" or "duplicates" are discarded.  (Off 3/4)} C {} {27 32 33} {} 1}
    {MI   39 {} 4 0 0 {Animate Dead} {Take any non-avatar champion in ANY discard pile, and place it into your pool with this spell attached.  The attached champion loses 2 levels.  Discard this champion if this spell leaves play for any reason.  (Off 3)} C {} {27 32} {} 1}
    {MI   40 {} 4 0 0 {Magic Font} {This spell stays in play until dispelled or negated.  Pools cannot be hidden from this player.  (Def 3)} C {} {6 32} {} 1}
    {MI   41 5 5 7 0 {Amish Nick} {Can cast wizard spells.  Immune to the powers of all cards from card sets made after Forgotten Realms.  He cannot use them either.} C {} {32 33} {1 2 d4 o4 d9 o9 d19 o19} 1}
    {MI   42 {} 4 0 0 Withdraw {If about to be defeated or discarded as the result of combat, the champion may cast this spell to return to his pool with attachments.  (Def 4)} C {} {6 33} {} 1}
    {MI   43 {} 4 0 0 {Dispel Evil} {Discard any monster in play, regardless of special powers.  (Off 3/4)} C {} {27 32 33} {} 1}
    {MI   44 {} 4 0 0 {Unholy Word} {Send any hero to the abyss, regardless of special powers.  (Off 3/4)} C {} {27 32 33} {} 1}
    {MI   45 {} 4 0 0 {Animate Object} {Play with a magic item or artifact into your pool.  The object is now a champion (hero) with a level equal to its icon bonus (no bonus is level 0).  The champion keeps its special powers, but it is still considered a magic item or artifact.  (Def 3)} C {} {6 32} {} 1}
    {MI   46 {} 6 0 0 Turncoat!!! {Choose a champion in play.  The owner of that champion rolls a 2d4.  They must choose and discard that many cards from hand, pool or formation to keep that champion.  Otherwise, the owning player must place that champion into any other player's pool.  (Harmful)} C {} {22 29 30 31 32 33 34} {} 1}
    {MI   47 {} 6 0 0 {Insanely Good Fortune} {Play on another player's event card.  If played on a helpful event, negate the event.  If played on "Unusually Good Fortune", negate the event, both players then draw 6 cards, and the other player then randomly discards his hand down to 2 cards.} C Harmful {22 29 30 31 32 33 34} {} 1}
    {MI   48 {} 6 0 0 Conspiracy! {All players write down a champion that they think should be discarded.  The results are revealed and the champion with the highest vote total is discarded (regardless of special powers).  If the results are tied, all champions in the tie are discarded. (Harmful)} C {} {22 29 30 31 32 33 34} {} 1}
    {MI   49 {} 21 2 0 {Barracks of the City of Greyhawk} {During combat, this player's allies cannot be discarded or forced to switch sides.  If victorious, one ally used in battle can be returned to the hand.} C {} {} {} 1}
    {MI   50 {} 6 0 0 Kamikaze! {Usable only when attacking.  The attacking champion charges without fear, discarding all champions involved in the combat to the discard pile, and razing the realm (with no spoils).  (Harmful)} C {} {22 33} {} 1}
    {MI   51 {} 21 7 0 {Two Fisted Player} {This player draws one less card per turn, but his hand size is increase to 12 and is immune to all cards and abilities that would cause cards to be discarded from his hand.} C {} {} {} 1}
    {MI   52 {} 6 0 0 {Kender Taunting} {Force two champions to attack you during their owners' next phase 4.  If they cannot attack, both champions are discarded.  If the first champion to attack is defeated or razes the realm, the second is not discarded.  (Harmful)} C {} {22 29 30 31 32 33 34} {} 1}
    {MI   53 {} 6 0 0 {Great Depression} {Each player must discard a 1d4 magic item(s) and/or artifact(s), or discard all non-thieves in their pool.  If there is a regent in a pool, that pool requires a discard of 2d4 magic item(s) and/or artifact(s) instead. (Harmful)} C {} {22 29 30 31 32 33 34} {} 1}
    {MI   54 {} 6 0 0 {A Horrible Mistake} {Play whenever an opponent copies another card.  Both cards are discarded to the abyss.  If the opponent owns both cards, then that player must also draw and discard two cards from their draw pile to the abyss.  (Harmful)} C {} {22 29 30 31 32 33 34} {} 1}
    {MI   55 +4 9 0 0 Fedifensor {Sword.  When in battle against a thief, the thief is halved in current level and may not play thief skills.  May be discarded from the pool to counter a just played thief skill.  (Off)} C {} {27 32 33 38 44} {} 1}
    {MI   56 8 7 5 0 Ariakan {All of this player's realms can defend themselves as level 5 champions.  If the realm can already defend itself, the realm champion gets a +5 to its adjusted level.} C {} {32 33} {1 2 d9 o9 d18 o18} 1}
    {MI   57 {} 9 0 0 {Cloak of Protection} {During phase 3, this player may elect the attached champion to be immune to the powers of one card type (cleric spell, blood ability, ally, etc.).  Cannot be used by a champion with the word immune in his power.  (Def)} C {} {6 32 33} {} 1}
    {MI   58 +5 9 0 0 {Club of Bashing} {Usable only by giants.  May be discarded during battle to subtract the base level of the attached champion from the adjusted level of the opposing champion.  If the new adjusted level is below zero, the opposing champion is discarded.  (Off)} C {} {27 32 33} {} 1}
    {MI   59 +1 9 0 0 {Sling of Seeking} {When in pool, this champion can sling a rock that kills one giant (champion or ally) in any combat before its power activates.} C Offensive {27 32 33} {} 1}
    {MI   60 +6 9 0 0 {Necklace of Fangs} {Usable only by clerics.  During Phase 4, may enslave any undead champion in play to attack and defend for this player.  The champion returns to its owner's pool only if it survives the combat. (Off)} C {} {27 32 33} {} 1}
    {MI   61 +3 9 0 0 {Cupid's Arrows} {Can be discarded at any time from play to send two champions in combat on a romantic trip to limbo.  The battle may continue with new champions.  (Off)} C {} {27 32 33} {} 1}
    {MI   62 11 10 7 0 {Kronos the Titan} {Giant.  Earthwalker.  Swimmer.  Can use wizard spells, cleric spells, and psionic power cards.  Whenever a monster attacks, it must ask Kronos permission to use its special powers.} C {} {13 17 37 32 33} {1 2 d4 o4 d9 o9 d11 o11 d19 o19} 1}
    {MI   63 {} 9 0 0 {Chaos Wand} {Whenever an opponent in combat with the attached champion wants to play a card, the wand's owner picks it randomly from their hand, discarding any cards that are unusable.  (Off)} C {} {27 32 33} {} 1}
    {MI   64 {} 11 0 0 Aversion {Can only be played by a player who attacked and was defeated.  Play onto winning defender.  While Aversion remains attached, the champion cannot enter combat with any of this player's champions.   (Off 5)} C {} {27 34} {} 1}
    {MI   65 {} 11 0 0 {Mind Alteration} {This champion may switch the power of any 2 champions in play.  This power lasts until it is negated, or if the champions face each other in battle. (Off 3)} C {} {27 32} {} 1}
    {MI   66 {} 11 0 0 {Absorb Disease} {Can be played at any time to redirect the effect of any spell, event or blood ability directed at any other champion of this player, whether in pool or in battle, to the champion using this power.  (Def)} C {} {6 29 30 31 32 33 34} {} 1}
    {MI   67 {} 11 0 0 {Teleport Other} {Usable only when one of your realms is attacked.  Each player rolls 1d6 for each unrazed realm in his formation.  The highest total roll has their front-most realm attacked instead for this battle, regardless of movement restrictions or special powers.
(Off)} C {} {27 33} {} 1}
    {MI   68 {} 8 4 0 {Poisoned Oasis} {May be attached to any realm.  May be played at any time to skip phases 0 through 5 (inclusive) of a turn following a Caravan.} C {} 31 {} 1}
    {MI   69 {} 11 0 0 {Body Control} {The using champion gains the special powers and abilities of the opposing champion until the end of this player's next turn.  (Def 4)} C {} {6 33} {} 1}
    {MI   70 {} 11 0 0 Awe {Roll 2d6 when this power is used.  If the roll is lower than the using champions base level, the opposing champion loses this round of combat and returns to its pool stripped of all attached cards, regardless of special powers.  (Off 4)} C {} {27 33} {} 1}
    {MI   71 {} 11 0 0 {Ballista Attack} {Discard an opposing ally already in play, or any champion in any pool.  (Off 4)} C {} {27 33} {} 1}
    {MI   72 {} 11 0 0 Cannibalize {All champions in your pool lose 2 levels until the end of the current turn.  The using champion gains 2 levels for each champion in your pool until the end of the current turn.  (Def 4)} C {} {6 33} {} 1}
    {MI   73 12 10 5 0 {Gellidus, Dragon of Ice} {Flyer.  Gellidus thrives on creation and may use any defensive card.  Offensive cards played against Gellidus are doubled in level.  If Gellidus and T'chaar are owned by the same player, both may use any offensive and defensive cards and the penalties for doubling cards used against them is negated.} C {} {8 16 32 33} {1 2 d3 d4 d101 d9 d11 d17 d18 d102 d19} 1}
    {MI   74 4 16 7 0 {Louie the Pit Boss} {Cannot be the target of any card or power designated as harmful or offensive.  May be sent to limbo at any time to have any die (or dice roll) be re-rolled.} C {} {32 33} {1 2 d9 o9 d17 o17} 1}
    {MI   75 6 7 4 0 {Gib Nedyah} {Cannot attack. Can use any unarmed combat card. While defending, may use any one unarmed combat card from any discard pile.  Immune to all events (even helpful ones), thief skills, and blood abilities.} C {} {32 33} {1 2 d101 o101 d9 o9 d18 o18 d102 o102} 1}
    {MI   76 {} 15 7 0 {Inverted Pyramid} {Played at the beginning of the player's turn, this card is not discarded.  It affects all players and remains in effect until any other rule card is played.  All formations are inverted when this rule card comes into play.  The front row now has three realms, the middle row has two, and the back has one.} C {} 29 {} 1}
    {MI   77 {} 15 7 0 Humility {Played at the beginning of the player's turn, this card is not discarded.  It affects all players and remains in effect until any other rule card is played.  This card is immune to events and the wish spell.  All extra cards that are granted by any means (except spoils) are send to limbo and cannot be used while this rule card is in play.  If this rule card leaves play, each player who lost one or more cards may roll 1d10 and retrieve all cards with a last digit matching the roll (return those cards to hand).  All other cards are not retrieved and send to the discard pile.} C {} 29 {} 1}
    {MI   78 {} 15 7 0 {Hornung's Randomness} {Played at the beginning of the player's turn, this card is not discarded.  It affects all players and remains in effect until any other rule card is played.  All cards that require a "Draw and discard noting the last digit", now require that a die roll of 1d10 be used instead.} C {} 29 {} 1}
    {MI   79 17 12 7 1 Bansmareton {Avatar.  Discard a psionic champion to bring Bansmareton into play.  Each opponent draws a card when Bansmareton enters play.  Immune to psionic attack. Bansmareton psionically teleports all of this players champions and allies, allowing them to attack any realm regardless of position or movement restrictions.} C {} {32 33} {1 2 d9 o9 d11 o11} 1}
    {MI   80 7 7 1 0 Kalator {Can cast cleric spells.  Immune to offensive thief skills.  Any magical item attached to Kalator becomes a Forgotten Realms artifact, discarding from play any magical items with the same name (no more can be played).} C {} {32 33} {1 2 d4 o4 d9 o9 d18 o18} 1}
    {MI   81 8 7 1 0 {Wealthy Oriental Vassal} {Immune to harmful events.  When in play, only cards marked as "First Edition" can be played.  If the Poor Oriental Lord and this champion are in play at the same time, both go to limbo for 1d10 turns (each champion's owner rolls for their champion).} C {} {32 33} {1 2 d9 o9 d18 o18} 1}
    {MI   82 {} 19 0 0 {Entropy Shield} {For every card attached to the opposing champion, the opponent must roll a d10.  If the number rolled is even, the attached card is discarded.  (Off 4)} C {} {27 33} {} 1}
    {MI   83 {} 13 7 0 {Dark Cloud} {This realm negates the powers of Tyr, Arkhold, and Mulmaster.} C {} 31 {} 1}
    {MI   84 +? 19 0 0 {Melf's Acid Arrow} {May be played into a combat where this player is not involved.  Roll 2d6 for the level of this spell when it is cast.  If the roll is less than the caster's base level, destroy one ally already in play.  (Off 4)} C {} {27 33} {} 1}
    {MI   85 {} 13 2 0 {The Yatils} {Magical items cannot be used when attacking this realm.  If Mordenkainen is anywhere in play, each defender of this realm gains a +9 ally able to cast wizard and cleric spells.} C {} 31 {} 1}
    {MI   86 {} 19 0 0 {Control Weather} {Until the end of this player's next turn, your realms can only be attacked by earthwalkers, "teleporters", or through Underdark realms.  (Def 5)} C {} {6 34} {} 1}
    {MI   87 {} 13 7 0 Assembre {This realm has a gate to Krynn hidden within its vineyards.  Once per battle, you may search your deck for a Dragonlance champion and place it into your pool.} C {} 31 {} 1}
    {MI   88 {} 19 0 0 {Polymorph, Any Object} {Change any one attachment (anywhere in play) into an attachment with a +1d4 and no special abilities.  Lasts until dispelled or negated.  (Off 3/4)} C {} {27 32 33} {} 1}
    {MI   89 {} 13 7 0 {Elven Towers} {This realm can never be rebuilt.  Due to its high resistance to magic, this player is immune to the effects to other player's dungeon cards.} C {} 31 {} 1}
    {MI   90 {} 19 0 0 {Leomund's Secure Shelter} {This player's pool cannot be the target of harmful events or offensive spells.  Lasts until dispelled or negated.  (Def 3)} C {} {6 32} {} 1}
    {MI   91 {} 18 0 0 {Knee to the Groin} {Usable by any champion.  May not be used on dragons.  The opposing champion must either retreat to his pool from battle (treat as a defeat) or continue at half of his base level (opponent's choice).  (Off 4)} C {} {27 33} {} 1}
    {MI   92 +5 18 0 0 Stomp! {Usable only by giants.  Kills all allies in play of icon level 5 or less.  (Off 4)} C {} {27 33} {} 1}
    {MI   93 +? 18 0 0 {Heaven & Earth} {Usable also by any adventurer.  Roll 1d6 for the bonus of this card. (Off 4)  May also be played at any time in response to any card played by a champion of lower base level.  That card is negated and this player draws a card.} C {} {27 29 30 31 32 33 34} {} 1}
    {MI   94 -4 18 0 0 {Tsuki Kotegaeshi} {Usable also by any adventurer.  Play on an opposing champion whose player must draw (face up) the top two cards from their draw pile.  If neither can be played into battle, discard the cards along with the opposing champion. (Off 4)} C {} {27 33} {} 1}
    {MI   95 +? 18 0 0 Headbutt {Usable by any champion.  Roll 2d6 for the bonus of this card, and 1d4 for a bonus to the opposing champion if the user is not a monster.  Spells and psionics cannot be used by either champion for the remainder of this round of combat.  (Off 4)} C {} {27 33} {} 1}
    {MI   96 +? 18 0 0 Roundhouse {Usable by any champion.  Roll 3d6 for the bonus of this card.  This champion may not play any more cards that are designated as Defensive.  (Off 4)} C {} {27 33} {} 1}
    {MI   97 {} 18 0 0 Trip {Usable by any champion.  Sends one of the opposing champion's allies to the discard pile, regardless of immunities and before its powers activate.  (Off 4)} C {} {27 33} {} 1}
    {MI   98 +10 18 0 0 {Stunning Fist} {If this champion is winning by more than 8 immediately after this card is played into battle, then the opposing champion is instantly defeated. (Off 4)} C {} {27 33} {} 1}
    {MI   99 +5 18 0 0 {Whirling Dervish} {The using champion ignores any instant defeat conditions and must be defeated by level alone.  May be played as a counter to an instant defeat. (Def 4)} C {} {6 33} {} 1}
}
