set CrossFire::cardDataBase {
    {Night Stalkers}
    {NS    1 9 13 2 0 {The Vast Swamp} {Can defend itself as a level 9 undead wizard. Nonflying attackers are at half their adjusted level (rounded down).} R Coast. {5 31} {1 d102 o102 d19 o19} 1}
    {NS    2 {} 13 2 0 {The Bandit Kingdoms} {Thieves defending this realm gain 2 levels for every attached card.} UC {} 31 {} 1}
    {NS    3 {} 13 1 0 Mintarn {Can only be attacked by flyers or swimmers. Whenever a thief in this player's pool is to be discarded outside of combat, it instead goes to Limbo, returning at the end of this player's next turn.} C Coast. {5 31} {} 1}
    {NS    4 {} 13 1 0 Nelanther {Can only be attacked by flyers or swimmers. Nelanther has a powerful pirate navy. All champions and allies attacking any realm by swimming must discard a magical item from their hand or pool or return to their pool immediately.} C Coast. {5 31} {} 1}
    {NS    5 {} 13 3 0 Falkovnia {Because of the poisonous nature of this realm, if Falkovnia is razed, all the champions who attacked it that turn must be discarded.} R {} 31 {} 1}
    {NS    6 7 13 3 0 Richemulot {Can defend itself as a level 7 werebeast (monster) that can use thief skills.} UC {} 31 {1 d17 o17} 1}
    {NS    7 {} 13 4 0 Cromlin {While Cromlin is in play, this player may freely exchange magical items and artifacts between the champions in his pool and his hand in Phase 3.} UC {} 31 {} 1}
    {NS    8 {} 13 6 0 UnderCerilia {Underdark. This realm extends under opponents' Birthright realms, allowing them to be attacked by this player's champions and allies, regardless of position or restrictions.} C {} {42 31} {} 1}
    {NS    9 {} 13 6 0 {The Vampire's Realm} {This realm is protected by a great swarm of bats that attack all nonearthwalking champions, reducing their adjusted levels by half (rounded down).} UC {} 31 {} 1}
    {NS   10 {} 8 2 0 {Thieves' Guild} {Draw a card whenever a thief skill card is played.} UC {} 31 {} 1}
    {NS   11 +6 8 3 0 {Haunted Graveyard} {Act as a +6 ghost ally (undead). This ghost is so terrifying that only undead allies and events may be played to attack the attached realm after the attacking champion has been sent forward. Items attached before battle function normally.} R {} 31 {} 1}
    {NS   12 {} 8 2 0 {Guild Shop} {This player's thieves can swim or earthwalk as needed. They ignore all wall spells.} C {} 31 {} 1}
    {NS   13 {} 8 1 0 {Forgotten Crypt} {Any champion attacking this realm is discarded at the end of combat, whether he wins or loses. Undead are immune to this holding.} C {} 31 {} 1}
    {NS   14 {} 8 2 0 {Assassin's Guild} {When the Guild is in play, each turn this player may discard a champion from his pool, forcing an opposing player to discard a champion from pool or hand to the Abyss.} C {} 31 {} 1}
    {NS   15 {} 8 4 0 {The Pristine Tower} {Champions attacking the attached realm are considered monsters for each round of combat.} UC {} 31 {} 1}
    {NS   16 {} 8 4 0 {Giustenal Ruins} {This player's realms cannot be attacked by psionicists or champions able to use psionic power cards.} R {} 31 {} 1}
    {NS   17 {} 8 1 0 {Hellgate Keep} {The attached realm, this holding, and its defenders are immune to harmful events and offensive spells. If the Keep is discarded during battle but the realm isn't razed, the attacking champion may draw a card.} UC {} 31 {} 1}
    {NS   18 {} 8 7 0 {Cavern of Ancient Knowledge} {May be attached to any Underdark realm. While the Cavern is in play, all offensive spells cast at this player are reflected back at the casting player. This holding can be attached at any time to reflect a just-cast spell.} R {} 31 {} 1}
    {NS   19 {} 6 0 0 {Paying Your Dues} {All players who have a thief in battle or in pools must discard one magical item from their hand. If they cannot, they must discard all thieves in their pool. (Harmful)} C {} {22 29 30 31 32 33 34} {} 1}
    {NS   20 {} 6 0 0 {Moonlight Madness} {Until the end of this player's next turn, all undead and werebeasts gain 5 levels and can attack any realm, regardless of position or restrictions. (Helpful)} C {} {23 29 30 31 32 33 34} {} 1}
    {NS   21 {} 6 0 0 {The Boss Wants a Cut} {Until the end of this player's next turn, all realms, holdings, and artifacts that give another player extra cards are instead given to the event player. (drawn from this player's draw pile) This event cannot be copied or negated. (Harmful)} UC {} {22 29 30 31 32 33 34} {} 1}
    {NS   22 {} 6 0 0 {Dawn of the Dead} {Until the end of this player's next turn, undead champions and allies discarded for any reason are immediately shuffled back into their draw pile. (Helpful)} C {} {23 29 30 31 32 33 34} {} 1}
    {NS   23 {} 6 0 0 {The Long Arm of the Law} {All thieves in play are immediately sent to Limbo until their players post bail by discarding a card to the Abyss to retrieve each thief. (Harmful)} R {} {22 29 30 31 32 33 34} {} 1}
    {NS   24 {} 6 0 0 {Wail of the Banshee} {All players must discard a champion from their pool; undead are immune to this event. If a player has no champions in his pool, he must discard two cards from his hand. (Harmful)} UC {} {22 29 30 31 32 33 34} {} 1}
    {NS   25 {} 6 0 0 {Complete Surprise} {Played during combat, this player's champion is doubled in level and no cards other than events can be played by the opposing player. (Harmful)} R {} {22 29 30 31 32 33 34} {} 1}
    {NS   26 {} 6 0 0 {The Black Death} {All players must draw and discard a card, noting its last digit. That many base levels or more of champions must be discarded from each pool. Players with an undead champion in their pool are immune to this event. (Harmful)} C {} {22 29 30 31 32 33 34} {} 1}
    {NS   27 {} 6 0 0 {Three Card Monte} {All players draw three cards face up. Realms go to the Abyss. The icon level of all other cards are tallied for each player. The player with the highest number gets to keep his cards; all others are discarded. (Harmful)} R {} {22 29 30 31 32 33 34} {} 1}
    {NS   28 10 16 2 0 {The Guildmaster} {Thieves cannot use thief skills without the Guildmaster's permission. He is immune to unarmed combat cards.} R {} {32 33} {1 2 d9 o9 d17 o17} 1}
    {NS   29 8 16 1 0 {Artemis Entreri} {Artemis can use unarmed combat cards usable by heroes, and he gains 5 levels if the opposing champion plays no allies.} UC {} {32 33} {1 2 d9 o9 d17 o17 d18 o18} 1}
    {NS   30 3 16 1 0 {Daryth of Calimshan} {Daryth wears a pair of magical gloves that give a +2 bonus to any thief skills used by him.} C {} {32 33} {1 2 d9 o9 d17 o17} 1}
    {NS   31 9 16 1 0 {Storm Silverhand} {Storm can be sent to Limbo at any time, allowing her player to look at an opponent's hand. She returns to the pool at the end of her player's next turn.} UC {} {32 33} {1 2 d9 o9 d17 o17} 1}
    {NS   32 7 16 3 0 {Jacqueline Renier} {Werebeast. Opposing champion is automatically defeated unless he can cast spells, or has or can play a magical item or artifact.} C {} {45 32 33} {1 2 d9 o9 d17 o17} 1}
    {NS   33 5 16 3 0 {Ratik Ubel} {Undead. Immune to offensive spells and harmful events. Ratik can ignore any one magical item played against him.} C {} {40 32 33} {1 2 d9 o9 d17 o17 o102 d102} 1}
    {NS   34 2 16 3 0 {Julio, Master Thief of Haslic} {If victorious in battle, Julio can return one nonspell card from the discard pile to his player's hand.} C {} {32 33} {1 2 d9 o9 d17 o17} 1}
    {NS   35 8 16 2 0 {Turin Deathstalker} {Undead. Turin carries a dagger of venom that instantly discards allies of +4 or less. He is immune to unarmed combat cards and the special powers of all Forgotten Realms champions.} R {} {40 32 33} {1 2 d9 o9 d17 o17 o102 d102} 1}
    {NS   36 7 16 2 0 {Simpkin "The Weasel" Furzear} {Halfling. Any magical items attached to champions who oppose Simpkin become Simpkin's for that round of battle. Afterwards they are discarded.} UC {} {21 32 33} {1 2 d9 o9 d17 o17} 1}
    {NS   37 4 16 4 0 Phostrek {Halfling; can use psionic power cards. Phostrek is a savage warrior - against nonmonster champions his base level rises to 8.} C {} {21 32 33} {1 2 d9 o9 d11 o11 d17 o17} 1}
    {NS   38 5 16 4 0 Jamlin {Elf. Jamlin must be beaten by 10 or more points in combat to be discarded; if not, he returns to his pool with attached cards.} UC {} {14 32 33} {1 2 d9 o9 d17 o17} 1}
    {NS   39 8 16 4 0 Donval {Dwarf; earthwalker. Donval can have any number of attached artifacts from any world. However, he may not use magical items.} C {} {12 13 32 33} {1 2 d9 o9 d17 o17} 1}
    {NS   40 4 16 6 0 El-Hadid {El-Hadid can use blood abilities. In combat his opponent must choose up to 4 cards he plans to use that round and place them face up in front of him. Only cards from this "minihand" may be used in the battle.} UC {} {32 33} {1 2 d9 o9 d17 o17} 1}
    {NS   41 3 16 6 0 {Kelda Auslawsen} {Kelda gains 5 levels against heroes and/or 3 levels if defending a Birthright realm.} C {} {32 33} {1 2 d9 o9 d17 o17} 1}
    {NS   42 3 16 6 0 Moriad {Halfling. Moriad is immune to the special powers of undead champions.} C {} {21 32 33} {1 2 d9 o9 d17 o17} 1}
    {NS   43 7 16 7 0 {Uldo Dracobane} {Elf (drow); earthwalker. If not involved in battle at the end of this player's turn. Uldo may send all cards attached to a dragon champion to the bottom of that player's draw pile. He must attack his next turn or be discarded.} R {} {10 13 14 32 33} {1 2 d9 o9 d17 o17} 1}
    {NS   44 ? 10 7 1 Orcus {Avatar. Undead. Two undead champions must be discarded to bring Orcus into play. This player's undead gain 5 to their base levels; they may attack at half adjusted level to discard a realm instead of razing it. Orcus's base level is equal to the sum of the base levels of the undead discarded to bring him into play. Limit one avatar per pool.} R {} {32 40} {1 2 d9 o9 o102 d102} 1}
    {NS   45 17 16 1 1 Mask {Avatar. A thief must be discarded to bring Mask into play. This player's thieves gain 3 to their base levels. Mask may be sent to the Abyss at any time to force all magical items, artifacts, spells, and allies in one player's discard pile to be sent to the Abyss. Limit one avatar per pool.} R {} 32 {1 2 d9 o9 d17 o17} 1}
    {NS   46 +7 9 0 0 {Dancing Sword} {May also be used as a level 7 hero for one round of combat. If so used, only allies may be played with it. If victorious, it returns to this player's hand or pool. The dancing sword can be involved in two rounds of battle, once as a magical item, once as a champion. (Def)} C {} {6 38 44 32 33} {1 2 d9 o9 d18 o18} 1}
    {NS   47 +3 9 0 0 {Rod of Zombie Mastery} {A champion defeated by the rod wielder is not discarded. Instead it is used as an undead ally in this champion's next battle and is discarded afterward. (Off)} C {} {27 32 33} {} 1}
    {NS   48 +3 9 0 0 {Whip of Disarming} {All magical items and artifacts attached to the opposing champions are instantly discarded; no more may be added. (Off)} UC {} {27 32 33} {} 1}
    {NS   49 +3 9 0 0 {Gauntlets of Dexterity} {The attached champion can use thief skills. If attached to a thief, anytime there are three or more thief skills are in his discard pile, the player may shuffle his discards back into his draw pile. (Def)} UC {} {6 32 33} {d17 o17} 1}
    {NS   50 +4 9 0 0 {Wand of Bone} {Usable only by undead. The attached champion gains 1 level for every undead champion in play. His undead allies cannot be discarded or forced to switch sides for any reason. (Def)} R {} {6 32 33} {} 1}
    {NS   51 +4 2 2 0 {Book of the Dead} {All undead (and any attached cards) in this player's pool are immune to harmful events and the Wish spell.} R {} {32 33} {} 1}
    {NS   52 +5 2 7 0 {Heart of Darkness} {If attached to an undead champion, the bonus becomes +10. This champion can cast wizard spells, and undead champions and allies cannot be used to defend against him.} C {} {32 33} {d19 o19} 1}
    {NS   53 {} 2 2 0 {Trumpet of Doom} {Each turn, draw and discard a card, noting its last digit. Corresponding to the digit, discard all of the following in play; 1-magical items; 2-artifacts; 3-razed realms; 4-holdings; 5-rule cards; 6-flyers, swimmers, earthwalkers; 7-elves, dwarves, halflings; 8-dragons, awnshegh; 9-undead, werebeasts; 0-events.} R {} {32 33} {} 1}
    {NS   54 {} 2 1 0 {Herald of Mei Lung} {This player is immune to all cards that force cards to be discarded from his hand and to all cards that examine his draw pile and discard or rearrange cards found there.} C {} {32 33} {} 1}
    {NS   55 {} 17 0 0 Backstab {Doubles the attached thief's base level for one round. (Def/4)} C {} {6 33} {} 1}
    {NS   56 +2 17 0 0 {Pick Pockets} {Use another player's magical item for this round of combat. At the end of combat, the item's owner draws and discards a card, noting its last digit. If it is higher than the thief's base level, the item is returned; if not, it is discarded. (Off/4)} C {} {27 33} {} 1}
    {NS   57 +2 17 0 0 {Move Silently} {Attached champion ignores realm champions, instantly defeating them. This skill lasts until this champion is discarded. (Off/3/4)} C {} {27 32 33} {} 1}
    {NS   58 {} 17 0 0 {Set Traps} {Draw a card and place it face down under the lead realm. When that realm is attacked, discard the card, noting its last digit. Attackers with a base level equal or less than this number are discarded immediately. (Def/3)} C {} {6 32} {} 1}
    {NS   59 {} 17 0 0 {Hide in Shadows} {This champion can retreat from a battle back to his pool. He is defeated but not discarded. (Def/4)} UC {} {6 33} {} 1}
    {NS   60 +4 17 0 0 {Climb Walls} {Until the end of this player's next turn, this champion ignores all walls and can attack realms normally attacked only by flyers or swimmers. (Def/3/4)} C {} {6 32 33} {} 1}
    {NS   61 +2 17 0 0 {Detect Noise} {This skill may be played any time and lasts until the beginning of this player's next turn. This champion can use his special power first when defending. (Def)} C {} {6 29 30 31 32 33 34} {} 1}
    {NS   62 +2 17 0 0 {Read Languages} {This champion can cast wizard spells. This skill may be played any time and lasts until the champion is discarded. (Def)} C {} {6 29 30 31 32 33 34} {d19 o19} 1}
    {NS   63 +3 17 0 0 {Use Poison} {The opposing champion must draw and discard a card, noting its last digit. If that digit is 3 or less, that champion is defeated. Lasts until a champion has been defeated by the poison. (Off/4)} UC {} {27 33} {} 1}
    {NS   64 +4 17 0 0 {Concealed Weapon} {Negates all unarmed combat cards played during this round of combat. No further unarmed combat cards can be played. (Off/4)} UC {} {27 33} {} 1}
    {NS   65 9 10 7 0 Werebear {Werebeast. The Werebear is immune to the special powers of champions base level 6 or less and their attached cards.} R {} {45 32 33} {1 2 d9 o9} 1}
    {NS   66 1 10 1 0 {Crawling Claws} {Undead. Immune to offensive spells and psionic power cards. Crawling Claws gain 1 base level for every champion in this player's pool.} C {} {40 32 33} {1 2 d9 o9 o102 d102} 1}
    {NS   67 12 5 3 0 {Nemon Hotep} {Undead. Immune to offensive spells except those with the word "flame" or "fire" in the title. Opposing champions base level 5 or less are discarded after combat, win or lose.} C {} {40 32 33} {1 2 d9 o9 d4 o4 o102 d102} 1}
    {NS   68 6 20 3 0 {Shera the Wise} {Werebeast; flyer. Shera is such a masterful flyer that she is immune to harmful events and allies that affect flyers.} C {} {16 45 32 33} {1 2 d9 o9 d19 o19} 1}
    {NS   69 9 20 2 0 {Winslow the Lich} {Undead. All cards with icon bonuses played against Winslow lose 2 levels because of his freezing cold touch.} UC {} {40 32 33} {1 2 d9 o9 d19 o19 o102 d102} 1}
    {NS   70 12 12 4 0 {Caller in Darkness} {Undead. Immune to offensive psionic power cards and offensive spells. Psionicists defeated by the Caller are sent to the Abyss.} UC {} {40 32 33} {1 2 d9 o9 d11 o11 o102 d102} 1}
    {NS   71 8 14 6 0 {The Vampire} {Awnshegh; undead; earthwalker. Can use blood abilities and thief skills. All allies played with this champion are considered undead.} R {} {2 13 40 32 33} {1 2 d3 o3 d9 o9 d17 o17 d102 o102} 1}
    {NS   72 6 10 5 0 Wereshark {Werebeast; swimmer. The Wereshark is immune to swimming allies and discards any played against him.} C {} {37 45 32 33} {1 2 d9 o9} 1}
    {NS   73 {} 15 7 0 {Negative Planar Energy} {Played at the beginning of the player's turn, this card is not discarded. It affects all players and remains in effect until any other rule card is played. Undead champions subtract their base levels from the base levels of opposing champions. If the opposing champion is reduced to 0 or less, it is immediately discarded. Clerics and avatars are immune to this rule.} R {} 29 {} 1}
    {NS   74 {} 15 7 0 {A Sure Thing} {Played at the beginning of the player's turn, this card is not discarded. It affects all players and remains in effect until any other rule card is played. Instructions to draw and discard a card, noting its last digit, are ignored. All opponents receive the worst possible outcome (0 if high is good, 9 if low is best). This player receives the opposite.} R {} 29 {} 1}
    {NS   75 +6 1 0 0 Kaisharga {Undead. Immune to offensive magical items. Attached champion may cast wizard spells.} C {} {40 33} {d19 o19} 1}
    {NS   76 +5 1 0 0 {Guild Master} {Halfling. The attached champion may use thief skills. He may also use one magical item from any pool for this round of combat.} C {} {21 33} {d17 o17} 1}
    {NS   77 +4 1 0 0 Raaig {Undead. Immune to harmful events and offensive magical items. The attached champion may use cleric spells.} C {} {40 33} {d4 o4} 1}
    {NS   78 +3 1 0 0 {Cat Burglar} {Elf. When played in combat, discard a card at random from all other players' hands.} C {} {14 33} {} 1}
    {NS   79 +5 1 0 0 {Zombie Horde} {Undead. Gains an additional 2 levels for each ally or spell played against it.} UC {} {40 33} {o102 d102} 1}
    {NS   80 +3 1 0 0 Beggar {Ask each player not involved in combat for a card playable in the battle. Play any given immediately. If they refuse and you win the round, look at their hand and discard one card of your choice.} R {} 33 {} 1}
    {NS   81 +9 1 0 0 {Ancient Dracolich} {Undead; flyer; dragon. One opposing ally of this player's choice is instantly discarded.} R {} {8 16 40 33} {} 1}
    {NS   82 +2 1 0 0 {Loric the Fence} {When this ally is used in battle, you may discard up to 3 magical items or artifacts from your pool or hand and draw two cards for each.} UC {} 33 {} 1}
    {NS   83 +3 19 0 0 {Bigby's Dexterous Digits} {Until dispelled, this champion can use thief skills. (Def/3/4)} C {} {6 32 33} {d17 o17} 1}
    {NS   84 {} 19 0 0 {Guardian Mist} {Prevents either flyers, swimmers, or earthwalkers from attacking this player's formation (caster's choice) until the end of his next turn. (Off/3/4/5)} C {} {27 32 33 34} {} 1}
    {NS   85 +2 19 0 0 Alarm {Cancels a just-played thief skill and prevents the opposing champion from using any more skills for this round of combat. (Off/4)} C {Can be cast at any time to cancel a just played thief skill (Def).  May also be used in battle to prevent an opposing champion from using thief skills. (Off/4)} {27 33} {} 1}
    {NS   86 +4 19 0 0 {Corruption of the Flesh} {The affected champion becomes undead; this spell lasts until negated or dispelled. (Def/3/4/5)} UC {} {6 32 33 34} {d102 o102} 1}
    {NS   87 +3 4 0 0 {Power of Faith} {Negates the effect of all unarmed combat cards playable only by dragons or undead and prevents any more from being played in this round. (Off/3/4)} R {} {27 32 33} {} 1}
    {NS   88 {} 4 0 0 {Find Traps} {The affected champion and his allies can attack a realm, regardless of its special powers. The champion also ignores the power of attached holdings, spells, or thief skills. (Def/3/4)} C {} {6 32 33} {} 1}
    {NS   89 {} 4 0 0 {Blessed Abundance} {For this round of combat, all cards attached to the affected champion are doubled in level bonus. (Def/3)} C (Def/3/4) {6 32} {} 1}
    {NS   90 {} 4 0 0 {Monster Mount} {Any monster in an opposing pool may be used as an ally for this round of battle. Win or lose, that champion returns to his pool at the end of combat. (Off/4)} C {} {27 33} {} 1}
    {NS   91 +4 18 0 0 Aging {Usable only by any undead. Opponent's base level is halved (rounded down). (Off/4)} C {} {27 33 41} {} 1}
    {NS   92 +2 18 0 0 {Cause Despair} {Usable only by any undead. Opposing allies of +3 or less are immediately removed from combat. (Off/4)} C {} {27 33 41} {} 1}
    {NS   93 +3 18 0 0 {Cause Fear} {Usable only by any undead. All opposing allies are discarded. No more may be played this round. (Off/4)} C {} {27 33 41} {} 1}
    {NS   94 +1 18 0 0 {Cause Paralysis} {Usable only by any undead. An opposing champion of base level 5 or less immediately returns to his pool, defeated. (Off/4)} C {} {27 33 41} {} 1}
    {NS   95 +2 18 0 0 {Constitution Drain} {Usable only by any undead. An opposing champion is discarded at the end of this round of combat, win or lose. (Off/4)} C {} {27 33 41} {} 1}
    {NS   96 +3 18 0 0 {Strength Drain} {Usable only by any undead. Discard a card from your draw pile, noting its last digit. Subtract this number from the opposing champion's level. If reduced to 0 or less, that champion is discarded. (Off/4)} C {} {27 33 41} {} 1}
    {NS   97 +5 18 0 0 {Level Drain} {Usable only by any undead. Subtract the base level of the attached champion from the base level of the opposing champion. If reduced to 0 or less, that champion is discarded. (Off/4)} R {} {27 33 41} {} 1}
    {NS   98 +2 18 0 0 {Magic Resistance} {Usable only by any undead. Attached champion is immune to offensive spells, magical items, artifacts, and blood abilities until the end of this player's next turn. (Def/3/4)} UC {} {6 32 33 41} {} 1}
    {NS   99 +4 18 0 0 {Rapid Regeneration} {Usable only by any undead. Attached champion gains 2 levels for every card attached to an opposing champion for this round of combat. (Def/3/4)} C {} {6 32 33 41} {} 1}
    {NS  100 +6 18 0 0 {Cause Disease} {Usable only by any undead. If this champion is defeated in combat, attach this card to the opposing champion. His base level is reduced to 1 until negated. (Off/4)} R {} {27 33 41} {} 1}
    {NS  101 {} 15 7 0 {Good Triumphs in the End} {Played at the beginning of the player's turn, this card is not discarded. It affects all players and remains in effect until any other rule card is played. Players without undead or werebeast champions in play gain 2 to the base levels of their champions and are immune to harmful events played by players who have undead champions in their pools.} VR {} 29 {} 1}
    {NS  102 {} 15 7 0 {Crime Does Not Pay} {Played at the beginning of the player's turn this card is not discarded. It affects all players and remains in effect until any other rule card is played. Players who have thieves in play must discard a card at the beginning of their turn in order to use thief skills or thief champions' special powers that turn.} VR {} 29 {} 1}
    {NS  103 {} 6 0 0 Busted! {Play any time to prevent a thief skill from taking effect. The champion using the skill is immediately discarded. (Harmful)} VR {} {22 29 30 31 32 33 34} {} 1}
    {NS  104 {} 6 0 0 {Confused Hunchback} {Play on any monster to force it to attack another champion, player's choice, in its own pool. The opposing player lays down his hand face up and you both play cards from it until one side wins and draws a card, it may be played immediately. (Harmful)} VR {} {22 29 30 31 32 33 34} {} 1}
    {NS  105 {} 6 0 0 {Dark Prophesy} {Play before any combat you're not involved in, just after a defender comes forward. Write down who you think will win. If you're correct or the battle ends with no winner, draw three cards or discard the top three cards from any draw pile. If you're wrong, raze or discard a realm in your formation. (Helpful)} VR {} {23 29 30 31 32 33 34} {} 1}
    {NS  106 {} 6 0 0 {Dark Dreams} {Play at the end of a round of combat you've lost. Replay the round of combat with the same champions, except that the winner's attachments are discarded; you get to keep yours. The previous round of battle never happened and this one is decisive. (Harmful)} VR {} {22 29 30 31 32 33 34} {} 1}
    {NS  107 {} 6 0 0 {Celestial Lights} {Destroys all undead champions in one player's pool and prevents any undead champions from being involved in combat until the end of this player's next turn. (Harmful)} VR {} {22 29 30 31 32 33 34} {} 1}
    {NS  108 {} 2 7 0 {Mirror of Corruption} {Offensive spells, psionic power cards, blood abilities and harmful events are reflected away from the attached champion and affect the champion of this player's choice, regardless of immunities.} VR {} {32 33} {} 1}
    {NS  109 {} 9 0 0 {Amulet of Undead Aura} {Subtract the base level of the attached champion from the adjusted level of the opposing champion.} VR {} {32 33} {} 1}
    {NS  110 +5 9 0 0 {Arcane Formula for a Lich} {Can only be attached to a wizard. The attached champion becomes undead and gains 5 levels to his base level. This item remains attached to him until he's discarded; it cannot be discarded in any other way. (Def)} VR {} {6 32 33} {} 1}
    {NS  111 {} 9 0 0 {Bag of Beans} {During phase 3 you may cut your draw pile and take the card you cut to. If it is a realm, discard it immediately. Any other type of card may be held, put in the pool, or played as desired. (Def)} VR {} {6 32 33} {} 1}
    {NS  112 +5 9 0 0 Shadowcloak {Attached champion can use thief skills. If attached to a thief the shadowcloak becomes +8 and allows the thief to bypass a defending cleric or wizard and automatically raze a realm. The defending champion returns to his pool. (Def)} VR {} {6 32 33} {d17 o17} 1}
    {NS  113 {} 9 0 0 {Pavlov's Bell} {Each turn, select any realm in any formation. If players attack that realm on their turn, every one of their champions and allies receives a +1 bonus. If not, each champion and ally is at -1. This player is not affected. (Off)} VR {} {27 32 33} {} 1}
    {NS  114 +4 9 0 0 {Ring of Lycanthropy} {The attached champion becomes a werebeast and is immune to offensive magical items of +4 or less enchantment. (Def)} VR {} {6 32 33} {} 1}
    {NS  115 2 7 7 0 Zombie {Undead. The Zombie is immune to offensive psionic powers and the special powers of psionicists. It negates the level bonus of magical items and spells used by opposing champions.} VR {} {40 32 33} {1 2 d9 o9 d18 o18 o102 d102} 1}
    {NS  116 7 20 3 0 {Varney the Vampire} {Undead; flyer. Can use his charm gaze to force one ally to his side during combat. If defeated in battle, he can change to mist and escape to Limbo, returning at the end of his player's next turn.} VR {} {16 40 43 32 33} {1 2 d9 o9 d19 o19 o102 d102} 1}
    {NS  117 8 10 7 0 Moonbeast {Werebeast. All allies played with this champion become werebeasts and are immune to offensive magical items.} VR {} {45 32 33} {1 2 d9 o9} 1}
    {NS  118 10 10 3 0 {Gib Lhadsemlo} {This fearsome flesh golem is immune to offensive spells (including Wish), magical items, psionic powers, blood abilities, unarmed combat cards, thief skills, and harmful events.} VR {} {19 32 33} {1 2 d9 o9} 1}
    {NS  119 6 7 7 0 {Gib Hcivonad} {While this champion is in a players pool, any ally can be played into his pool as an undead monster champion (base level equal to its level bonus). It retains any special powers. If Gib Hcivonad is discarded, no more ally champions can be played, but those in a pool remain.} VR {} {32 33} {1 2 d9 o9 d18 o18} 1}
    {NS  120 8 16 1 0 {Gib Reltub} {Elf; earthwalker. Can cast wizard spells. Gib Reltub is immune to the effects of all events and may choose to ignore rule cards. Any Wish spells cast by him cannot be spell turned.} VR {} {13 14 32 33} {1 2 d9 o9 d17 o17 d19 o19} 1}
    {NS  121 13 20 2 0 {Gib Irod} {Undead. Can cast cleric spells. This reanimated horror is immune to harmful events, the Wish spell, and the special powers of allies. In combat, her player may discard up to 3 cards from his hand and draw replacements.} VR {} {40 32 33} {1 2 d4 o4 d9 o9 d102 o102 d19 o19} 1}
    {NS  122 20 5 5 1 {Gib Drawsemaj} {Avatar. Can be brought into play just after this player causes an opponent's realm to be discarded. When he appears, his player chooses the special powers of any two non-avatar champions to be his for that game. Limit one avatar per pool.} VR {} 32 {1 2 d9 o9 d4 o4} 1}
    {NS  123 9 12 4 0 {Gib Aklem} {Elf. This powerful mentalist can invoke his Telekinesis power during combat, causing any champion to become his ally during that round. If he loses the round, the ally is discarded instead of him. (Off/4)} VR {} {14 32 33} {1 2 d9 o9 d11 o11} 1}
    {NS  124 {} 13 7 0 {Den of Thieves} {When attacking any realm in this player's formation, the attacking player must discard a card from his hand or pool for each champion and ally sent forward.} VR {} 31 {} 1}
    {NS  125 {} 13 3 0 {Mad Scientist's Laboratory} {This player can reanimate champions and allies from any discard pile. Each acts as a +1 undead ally. At the end of the battle, all cards used in this manner are placed in the Abyss.} VR {} 31 {} 1}
}
