set CrossFire::cardDataBase {
    Powers
    {PO    1 +2 9 0 0 {Adjatha, the Spell Drinker} {Cannot be attached to a wizard or a cleric. For one round of battle, Adjatha drains all magical items of the opposing champion, rendering the useless. Add +2 to Adjatha for each item drained. (Off)} UC Sword. {27 32 33 38 44} {} 1}
    {PO    2 +3 9 0 0 {Abhorrence of Shapechangers} {Cannot be used by monsters. Against all shapechangers (werebeasts, Strahd von Zarovich, and the Kargat Vampire) Abhorrence becomes a +7 weapon. (Def)} R Sword. {6 32 33 38 44} {} 1}
    {PO    3 +1 9 0 0 {Sword of the Avoreen} {Cannot be used by monsters. This sword automatically defeats giant champions, and it reduces opposing undead and werebeasts to level 0. (Off)} R {Sword. Level 0 at time of play; subsequent cards add normally.} {27 32 33 38 44} {} 1}
    {PO    4 +4 9 0 0 {Sword of Blackflame} {During battle, the Sword of Blackflame reflects all spells back at the caster. Can be played in combat to reflect a spell just cast. (Def)} UC Sword. {6 32 33 38 44} {} 1}
    {PO    5 +4 9 0 0 {Sword of the High King} {Cannot be used by monsters. In battle, this mighty weapon causes fear. The opposing champion becomes level 1, and his allies are each reduced to a +1 bonus. (Off)} R Sword. {27 32 33 38 44} {} 1}
    {PO    6 +6 9 0 0 Dragonsbane {During battle, Dragonsbane destroys all dragons. (Off)} UC Sword. {27 32 33 38 44} {} 1}
    {PO    7 +2 11 0 0 {Post-Hypnotic Suggestion} {Psionic power. Usable by psionicist champions. If the psionic champion with this power is defeated, the opposing champion may not attack this player's realms for the rest of the game.} C (Off) {27 33} {} 1}
    {PO    8 +3 9 0 0 {Sword of the Black Rose} {Only usable by monster champions. This sword becomes a +7 weapon when used by an undead champion or werebeast. (Off)} R Sword. {27 32 33 38 44} {} 1}
    {PO    9 9 12 4 0 {Davron Parscall} {Psionicist Champion; can use psionic power cards. Davron's psionic Death Field can destroy the opposing champion automatically. Davron is sent to the Abyss (taken out of play) if the power is used.} UC (Off) {27 32 33} {1 2 d9 o9 d11 o11} 1}
    {PO   10 3 12 4 0 {Yorgia Sandow} {Psionicist Champion; can use psionic power cards. Discard one magical item from your pool to activate Yorgia's Metamorphosis, allowing her to imitate the power of any monster in play and add its level to her own.} C (Def) {6 32 33} {1 2 d9 o9 d11 o11} 1}
    {PO   11 8 12 4 0 {Roghal Baen} {Psionicist Champion; can use psionic power cards. When used in defense, Roghal can employ his Precognition, forcing the attacker to lay face up all cards he intends to use in this battle. The attacker can use only those cards.} UC (Off) {27 32 33} {1 2 d9 o9 d11 o11} 1}
    {PO   12 8 12 2 0 {Kelsur Brighteye} {Psionicist Champion; can use psionic power cards. Kelsur can employ his Telekinesis to steal a single magical item or artifact from the opposing champion for the duration of the battle. The item can be of any world.} C (Off) {27 32 33} {1 2 d9 o9 d11 o11} 1}
    {PO   13 7 12 4 0 {Rand the Bowyer} {Psionicist Champion; can use psionic power cards. Rand can employ his Levitation, preventing all but flyers from battling him.} UC {(Def); Works like a wall spell.} {6 32 33} {1 2 d9 o9 d11 o11} 1}
    {PO   14 7 12 4 0 {Seveia Shadowmaster} {Psionicist Champion; can use psionic power cards. If defeated when attacking, Seveia can employ her Shadow-form to return, invisibly, to her owner's pool. The defender still gets the spoils of victory.} C (Def) {6 32 33} {1 2 d9 o9 d11 o11} 1}
    {PO   15 7 12 4 0 {Rafe Racker} {Psionicist Champion; can use psionic power cards. Rafe can psionically Cause Decay, instantly destroying all of the opposing champion's magical items or an artifact of +4 or less.} UC (Off) {27 32 33} {1 2 d9 o9 d11 o11} 1}
    {PO   16 6 12 1 0 {Jacenelle Traen} {Psionicist Champion; can use psionic power cards. While in the pool, Jacenelle can psionically double another psionicist champion's level during battle.} C (Def) {6 32 33} {1 2 d9 o9 d11 o11} 1}
    {PO   17 5 12 5 0 {Bilago Lumen} {Psionicist Champion; can use psionic power cards. At the start of a battle, Bilago can employ his Mindwipe to subtract his adjusted level from the opposing champion's adjusted level. A champion reduced to level 0 is discarded.} UC (Off) {27 32 33} {1 2 d9 o9 d11 o11} 1}
    {PO   18 6 12 4 0 {Dawn d'Ereath} {Psionicist Champion; can use psionic power cards. Through psionic Ejection, Dawn is automatically immune to all psionic powers.} C (Def) {6 32 33} {1 2 d9 o9 d11 o11} 1}
    {PO   19 6 12 4 0 Phridge {Psionicist Champion; can use psionic power cards. Can also cast wizard and cleric spells.} C {} {32 33} {1 2 d4 o4 d9 o9 d11 o11 d19 o19} 1}
    {PO   20 5 12 4 0 {Seluna Darkenstar} {Psionicist Champion; can use psionic power cards. Seluna can employ her Appraise power, allowing her owner to look at the opponent's hand. She can then withdraw from combat (treat as a defeat), returning to the pool.} UC (Def) {6 32 33} {1 2 d9 o9 d11 o11} 1}
    {PO   21 5 12 4 0 {Kerm of Tyr} {Psionicist Champion; can use psionic power cards. Kerm can employ his Ultrablast to halve the opposing champion's level (round up) and discard all allies in play. If victorious, he returns to his pool at the end of his player's next turn.} C (Off) {27 32 33} {1 2 d9 o9 d11 o11} 1}
    {PO   22 5 12 4 0 {Havrum Riddle} {Psionicist Champion; can use psionic power cards. When in a battle, Havrum may employ his Stasis Field power to end the battle with no victory or spoils for either side. The opposing champion returns to his pool, and Havrum is discarded.} UC (Def) {6 32 33} {1 2 d9 o9 d11 o11} 1}
    {PO   23 5 12 2 0 {Lyr of the Mists} {Psionicist Champion; can use psionic power cards. When in battle, Lyr may employ her Banishment power to discard one champion in any pool.} C (Off) {27 32 33} {1 2 d9 o9 d11 o11} 1}
    {PO   24 5 12 4 0 {Colum Calder} {Psionicist Champion; can use psionic power cards. Colum may employ All-Round Vision, allowing his owner to examine the hands of all other players before deciding which realm to attack.} UC (Def) {6 32 33} {1 2 d9 o9 d11 o11} 1}
    {PO   25 4 12 4 0 {Kelasar Redbelt} {Psionicist Champion; can use psionic power cards. When defeated in battle, Kelasar may psionically Detonate an opponent's hand. The opponent must discard the cards and draw a new hand of five.} UC {(Off); May be used against ANY opponent.} {27 32 33} {1 2 d9 o9 d11 o11} 1}
    {PO   26 4 12 4 0 {Breshkll Logon} {Psionicist Champion; can use psionic power cards. In battle, Breshkll may be used as a champion or an ally. He may psionically Cannibalize, adding his opponent's level to his own, but then must be discarded after battle.} C (Def) {6 32 33} {1 2 d9 o9 d11 o11} 1}
    {PO   27 4 12 5 0 {Masara d'Will} {Psionicist Champion; can use psionic power cards. Masara can be used as an ally or a champion. She psionically projects Invisible Foes, adding +4 levels to each of her allies.} C (Def) {6 32 33} {1 2 d9 o9 d11 o11} 1}
    {PO   28 4 12 4 0 {Raydan Valers} {Psionicist Champion; can use psionic power cards. When involved in battle, Raydan can use Mindlink to use the level and power of a psionicist in another player's pool.} UC (Off) {27 32 33} {1 2 d9 o9 d11 o11} 1}
    {PO   29 {} 6 0 0 {Psychic Storm} {No psionic powers may be used and all psionicists are reduced in level by half (round up). The effects of this card last until another event card is played.} C (Harmful) {22 29 30 31 32 33 34} {} 1}
    {PO   30 {} 6 0 0 Sandstorm {All flyers are grounded and cannot attack or defend. All earth-walkers battle at half their normal levels (round up). These effects last until the end of this player's next turn.} C (Harmful) {22 29 30 31 32 33 34} {} 1}
    {PO   31 {} 6 0 0 {Necromantic Wave} {Offensive spells, magical items, and artifacts have no effect on undead champions and allies until the end of this player's next turn.} C (Helpful) {23 29 30 31 32 33 34} {} 1}
    {PO   32 {} 6 0 0 {Night of the Blue Moon} {All werebeasts triple their levels and are immune to offensive spells, magic items, and artifacts until the end of this player's next turn.} R {(Helpful)  Affects adjusted level.} {23 29 30 31 32 33 34} {} 1}
    {PO   33 {} 6 0 0 Zephyrwind {Play during step 2 of an opponent's turn. The Zephyrwind carries its victim forward in time, forcing the opponent to skip steps 3 and 4 of his current turn.} R (Harmful) {22 29 30 31 32 33 34} {} 1}
    {PO   34 +4 4 0 0 {Avangion's Protection} {Grants this player's champions immunity to psionic power cards and psionicist champion powers until the start of this players next turn. (Def/3/4)} C {} {6 32 33} {} 1}
    {PO   35 {} 6 0 0 Nullification {All spells in play must be discarded. No more can be cast until this player's next turn, including Limited Wish.} C (Harmful) {22 29 30 31 32 33 34} {} 1}
    {PO   36 {} 6 0 0 {Tuigan Invasion} {All holdings in play are destroyed (discarded).} R (Harmful) {22 29 30 31 32 33 34} {} 1}
    {PO   37 {} 6 0 0 {Dark Negation} {Negates the special power of one champion or one realm (this player's choice) until the end of this player's next turn.} R (Harmful) {22 29 30 31 32 33 34} {} 1}
    {PO   38 {} 6 0 0 {Caravan Raiders} {Play to cancel the Caravan event card just after it is played. This player may also randomly draw and discard one card from each opponent's hand.} C (Harmful) {22 29} {} 1}
    {PO   39 12 5 1 1 {Icedawn, Avatar of Auril} {Avatar. A cleric must be discarded to bring Icedawn into play. Icedawn is immune to events, walls, and offensive cleric spells. Limit one avatar per pool.} R {} 32 {1 2 d9 o9 d4 o4} 1}
    {PO   40 13 5 1 1 {Nightsinger, Avatar of Shar} {Avatar. A cleric must be discarded to bring Nightsinger into play. Nightsinger can create darkness, halving the levels of the opposing champion and his allies (round down). Limit one avatar per pool.} R {} 32 {1 2 d9 o9 d4 o4} 1}
    {PO   41 15 5 2 1 {Bonemaster, Avatar of Nerull} {Avatar. A cleric must be discarded to bring Bonemaster into play. Bonemaster makes this player's undead immune to offensive spells, magical items, artifacts, and events. Limit one avatar per pool.} R Undead. {32 40} {1 2 d9 o9 d4 o4 o102 d102} 1}
    {PO   42 16 5 2 1 {Lady of Fate, Avatar of Istus} {Avatar. A cleric must be discarded to bring Lady Fate into play. Before combat, her owner can examine an opponent's hand and discard any two cards. Limit one avatar per pool.} R {} 32 {1 2 d9 o9 d4 o4} 1}
    {PO   43 17 5 2 1 {Misfortune, Avatar of Ralishaz} {Avatar. A cleric must be discarded to bring Misfortune into play. Misfortune can replace this player's champion in combat at any time. But after that combat, the avatar must be discarded. Limit one avatar per pool.} R {} 32 {1 2 d9 o9 d4 o4} 1}
    {PO   44 18 5 5 1 {Tempest, Avatar of Zeboim} {Avatar. A cleric must be discarded to bring Tempest into play. Tempest makes this player's swimmers immune to offensive spells, magical items, and artifacts. If the Sea Queen is in play, Tempest cannot be. Limit one avatar per pool.} R Swimmer. {32 37} {1 2 d9 o9 d4 o4} 1}
    {PO   45 19 5 5 1 {Sirrion, Avatar} {Avatar. A cleric must be discarded to bring Sirrion into play. Immune to offensive spells. In battle, Sirrion forces the opposing champion's magic items and artifacts to be discarded. Limit one avatar per pool.} R {} 32 {1 2 d9 o9 d4 o4} 1}
    {PO   46 {} 4 0 0 {Mirror, Mirror} {This spell remains in effect until the end of this player's next turn. Mirror, mirror turns all spells against their casters. (Off/3/4)} C {} {27 32 33} {} 1}
    {PO   47 {} 4 0 0 {Rope Trick} {Enables this player to end his attack at any time, counting it as a loss, but returning his champion and allies to his hand. (Def/4)} C {} {6 33} {} 1}
    {PO   48 {} 4 0 0 Stasis {Play immediately after both champions have been chosen. No more cards can be played in this round of battle. (Off/4)} C {} {27 33} {} 1}
    {PO   49 +3 1 0 0 {Giant Space Hamster} {Every friendly ally played after this one gains 3 levels.} UC {} 33 {} 1}
    {PO   50 {} 19 0 0 {Polymorph Other} {Replace an opposing champion's power with the power of any other champion in play. Lasts until dispelled. (Off/3/4)} C {} {27 32 33} {} 1}
    {PO   51 {} 19 0 0 {Phase Out} {This player may not be attacked again until after his next turn. (Def/5)} C {} {6 34} {} 1}
    {PO   52 6 10 4 0 Gith {Earth-walker. Psionicist; may use psionic power cards.} UC {} {13 32 33} {1 2 d9 o9 d11 o11} 1}
    {PO   53 5 10 1 0 Crabman {Swimmer. In battle, the crabman can force one other player to contribute an ally to his side. If he has none, the power is wasted. After combat, the ally is discarded.} UC {} {37 32 33} {1 2 d9 o9} 1}
    {PO   54 4 10 1 0 {Aquatic Elf} {Swimmer. No elf champion or ally can oppose him in battle. Becomes level 8 if attacking a coastal realm.} UC {} {37 32 33} {1 2 d9 o9} 1}
    {PO   55 4 10 1 0 Ixitxachitl {Swimmer. Gains 4 levels when opposing another swimmer in battle. Can cast clerical spells. When attacking or defending a coastal realm, can cast wizard spells.} UC {} {37 32 33} {1 2 d4 o4 d9 o9 d19 o19} 1}
    {PO   56 5 10 4 0 Kirre {Psionicist; may use psionic power cards. If Kirre is defeated, his owner may draw one card and add it to his hand.} UC {} {32 33} {1 2 d9 o9 d11 o11} 1}
    {PO   57 4 10 1 0 {Locathah Champion} {Swimmer. All opposing allies lose their special powers.} UC {} {37 32 33} {1 2 d9 o9} 1}
    {PO   58 10 10 1 0 {Living Wall} {This monster absorbs (discards) all champions and allies of level 6 and higher. It is immune to artifacts and offensive spells and magical items. Champions, offensive psionic powers, and allies must be level 5 or less to attack it.} R {} {32 33} {1 2 d9 o9} 1}
    {PO   59 6 10 1 0 Tako {Swimmer. In combat, the Tako multiplies its level times the level of its lowest ally.} UC {} {37 32 33} {1 2 d9 o9} 1}
    {PO   60 4 10 4 0 {Earth Elemental} {Earth-walker. In battle, the earth elemental automatically defeats any champion whose card number has a last digit of 3 or less.} UC {} {13 32 33} {1 2 d9 o9} 1}
    {PO   61 8 10 1 0 {Skriaxit, Composite Elemental} {Earth-walker. In battle, Skriaxit forces the opposing champion and all his allies to fight at half their normal levels (round down).} R {} {13 32 33} {1 2 d9 o9} 1}
    {PO   62 5 10 1 0 {Mountain Giant} {Earth-walker. Reflects all psionic powers back to the projector.} UC {} {13 17 32 33} {1 2 d9 o9} 1}
    {PO   63 3 10 1 0 Grippli {Swimmer. The Grippli can use any magical item, with its highest level bonus.} UC {Level ? cards and draw and discard instructions grant highest possible level bonus.} {37 32 33} {1 2 d9 o9} 1}
    {PO   64 +1 11 0 0 {Chameleon Power} {Psionic power. Usable by psionicist champions. A psionicist with this power can be used as an ally. (Off/3/4)} C {} {27 32 33} {} 1}
    {PO   65 {} 15 7 0 {Brandobaris's Inversion} {Played at the beginning of the player's turn, this card is not discarded. It affects all players and remains in effect until any other rule card is played. All champions of base level 6 and above are reduced to level 2. The levels of all others are doubled.} R {New levels are considered base level.} 29 {} 1}
    {PO   66 +3 11 0 0 {Energy Containment} {Psionic power. Usable by psionicist champions. Until the end of the turn, the psionicist with this power is immune to all cards calling for a reduction of level(s). (Def/4)} C {} {6 33} {} 1}
    {PO   67 {} 11 0 0 {Complete Healing} {Psionic power. Usable by psionicist champions. The psionicist champion using this power may retrieve three allies from his discard pile and return them to his hand. (Def/3/4)} C {} {6 32 33} {} 1}
    {PO   68 {} 15 7 0 {Wheel of Fate} {Played at the beginning of the player's turn, this card is not discarded. It affects all players and remains in effect until any other rule card is played. At the start of this player's turns, all players draw a card and discard it, except for the card with the lowest first digit. Upon drawing his last card, each player shuffles his discards to form a new draw pile.} R {} 29 {} 1}
    {PO   69 +2 11 0 0 {Teleport Trigger} {Psionic power. Usable by psionicist champions. Place this card under one of your realms; it acts as a holding. When this realm is attacked, you may switch it with any other in your formation. Switched realms remain in their new places afterward. (Def/3)} C {} {6 32} {} 1}
    {PO   70 {} 11 0 0 {Molecular Rearrangement} {Psionic power. Usable by psionicist champions. Discard all magical items and artifacts in play. (Off/3/4)} C {} {27 32 33} {} 1}
    {PO   71 +4 11 0 0 Telekinesis {Psionic power. Usable by psionicist champions. The wielder may steal the use of one magical item or one artifact in play anywhere. The card returns to its owner's hand afterward. (Off/3/4)} C {} {27 32 33} {} 1}
    {PO   72 +3 11 0 0 {Mind Shield} {Psionic power. Usable by psionicist champions. When cast, it makes its player immune until the end of his next turn to all cards that look at his draw pile or hand. (Def/3/4/5)} C {} {6 32 33 34} {} 1}
    {PO   73 +3 11 0 0 {Molecular Agitation} {Psionic power. Usable by psionicist champions. All magical items and artifacts of the opposing champion are discarded. (Off/4)} C {} {27 33} {} 1}
    {PO   74 +4 11 0 0 {Control Wind} {Psionic power. Usable by psionicist champions. Negates for this player the effect of all spells, events, champion powers, and rule cards until the end of his next turn. (Def/3/4/5)} C {} {6 32 33 34} {} 1}
    {PO   75 +3 11 0 0 {Cause Decay} {Psionic power. Usable by psionicist champions. For this round of battle, change all of an opponent's magical item and artifact levels to +1 and negate all of their special powers. (Off/4)} C {} {27 33} {} 1}
    {PO   76 +4 11 0 0 Repugnance {Psionic power. Usable by psionicist champions. Used in battle, this power forces all allies of the opposing champion to join the user's side. (Off/4)} C {} {27 33} {} 1}
    {PO   77 +4 11 0 0 {Mind Thrust} {Psionic power. Usable by psionicist champions.} C (Off) {27 33} {} 1}
    {PO   78 11 5 5 1 {The Sea Queen, Avatar of Zeboim} {Avatar. Discard a cleric to bring the Sea Queen into play. She makes swimmers of all this player's champions and allies and may reclaim one magical item each turn as it is discarded. If Tempest is in play, the Sea Queen cannot be. Limit one avatar per pool.} R Swimmer. {32 37} {1 2 d9 o9 d4 o4} 1}
    {PO   79 14 5 5 1 {Kiri, Avatar of Kiri-Jolith} {Avatar. A cleric must be discarded to bring Kiri into play. In combat, Kiri negates all special powers of all champions in play. Limit one avatar per pool.} R {} 32 {1 2 d9 o9 d4 o4} 1}
    {PO   80 9 5 4 0 {Shadair Mesker} {Shadair can use wizard spells and psionic power cards.} UC {} {32 33} {1 2 d4 o4 d9 o9 d11 o11 d19 o19} 1}
    {PO   81 +1 11 0 0 {Mental Barrier} {Psionic power. Usable by psionicist champions. For the remainder of this battle, all offensive psionic powers used against this champion become +2 and have no extra abilities. (Def/4)} C {} {6 33} {} 1}
    {PO   82 +3 11 0 0 {Tower of Iron Will} {Psionic power. Usable by psionicist champions. User becomes immune to offensive psionic powers until the beginning of his next turn. (Def/3/4)} C {} {6 32 33} {} 1}
    {PO   83 +1 11 0 0 {Intellect Fortress} {Psionic power. Usable by psionicist champions. Until the end of his next turn, the user of this power is immune to all offensive spells, magical items, and psionic powers except those of avatars. (Def/3)} C {} {6 32} {} 1}
    {PO   84 +4 11 0 0 {Control Flames} {Psionic power. Usable by psionicist champions. This champion may force the discard of one non-champion card with the word flame or fire in its title. (Def/4)} C {} {6 33} {} 1}
    {PO   85 {} 15 7 0 {Psychic Storm} {Played at the beginning of the player's turn, this card is not discarded. It affects all players and remains in effect until any other rule card is played. No psionic power cards or artifacts may be played.} R {} 29 {} 1}
    {PO   86 {} 15 7 0 {Nullify Magic} {Played at the beginning of the player's turn, this card is not discarded. It affects all players and remains in effect until any other rule card is played. No wizard or clerical spells may be played.} R {} 29 {} 1}
    {PO   87 {} 15 7 0 {Mind of the Avatar} {Played at the beginning of the player's turn, this card is not discarded. It affects all players and remains in effect until any other rule card is played. All avatars can use psionic power cards.} R {} 29 {} 1}
    {PO   88 {} 15 7 0 {Gift of the Avatar} {Played at the beginning of the player's turn, this card is not discarded. It affects all players and remains in effect until any other rule card is played. Only clerics may use psionic power cards.} R {} 29 {} 1}
    {PO   89 +1 11 0 0 Intensify {Psionic power. Usable by psionicist champions. Doubles the levels of all allies played on this champion. (Def/4)} C {} {6 33} {} 1}
    {PO   90 +1 11 0 0 {Summon Planar Creature} {Psionic power. Usable by psionicist champions. The user may search his draw deck for one champion of level 6 or less to aid him in this battle. Reshuffle the draw deck afterward. (Def/4)} C {} {6 33} {} 1}
    {PO   91 +4 11 0 0 {Graft Weapon} {Psionic power. Usable by psionicist champions. In combat, the user of this power can use the level and effects of one magical item or artifact in another player's pool. (Def/4)} C {} {6 33} {} 1}
    {PO   92 +3 4 0 0 {Melt Stone} {The opposing champion is reduced in level to +3, and his allies to +1, for the duration of this combat. (Off/4)} C {} {27 33} {} 1}
    {PO   93 +8 11 0 0 {Psionic Blast} {Psionic power. Usable by psionicist champions.} C (Off) {27 33} {} 1}
    {PO   94 +1 11 0 0 Magnify {Psionic power. Usable by psionicist champions. A champion using this power doubles his level for the duration of this battle. (Def/4)} C {} {6 33} {} 1}
    {PO   95 +4 11 0 0 {Probability Travel} {Psionic power. Usable by psionicist champions. This power allows its user and his allies to attack any realm, regardless of its position. (Def/3)} C {} {6 32} {} 1}
    {PO   96 +2 11 0 0 Banishment {Psionic power. Usable by psionicist champions. No allies can be played against a psionicist champion using this power. (Off/3/4)} C {} {27 32 33} {} 1}
    {PO   97 +1 11 0 0 {Create Object} {Psionic power. Usable by psionicist champions. The user can look through his draw pile and select any single magical item or artifact to play immediately. Reshuffle the draw pile afterward. (Def/3/4)} C {} {6 32 33} {} 1}
    {PO   98 {} 11 0 0 {Psychic Lock} {Psionic power. Usable by psionicist champions. Ends combat. Both champions return to their pools; all other cards are discarded. The battle is a draw; there are no spoils. (Off/4)} C {} {27 33} {} 1}
    {PO   99 +2 11 0 0 {Life Draining} {Psionic power. Usable by psionicist champions. Automatically defeats undead champions and allies. (Off/4)} C {} {27 33} {} 1}
    {PO  100 {} 11 0 0 {Dimensional Door} {Psionic power. Usable by psionicist champions. Forces the attacker to redirect his attack to any other realm in play, ignoring its placement and special powers during the battle. (Off/4)} C {} {27 33} {} 1}
    {PO  101 {} 13 7 0 {Crystal Sphere} {Any psionicist champion defending the Crystal Sphere doubles his level.} VR {} 31 {} 1}
    {PO  102 {} 8 7 0 {Rock of Bral} {Can be attached to any realm. Any defender is considered a psionicist champion. If attached to the Crystal Sphere, it adds +6 to the defender's level.} VR {} 31 {d11 o11} 1}
    {PO  103 {} 2 7 0 Unipsi {Usable by any avatar. An avatar with this artifact attached can use any number of artifacts from any worlds.} VR {} {32 33} {} 1}
    {PO  104 {} 2 7 0 {The Inverter} {Usable by any wizard. This artifact enables wizards to use psionic power cards.} VR {} {32 33} {d11 o11} 1}
    {PO  105 {} 6 0 0 {Royal Conscription and Tax Levy} {All opponents of this player must skip step 3 of their turns until the beginning of this player's next turn.} VR (Harmful) {22 29 30 31 32 33 34} {} 1}
    {PO  106 +6 9 0 0 {Fate's Promise} {This sword negates all spells cast by the opposing champion. (Def)} VR {} {6 38 44 32 33} {} 1}
    {PO  107 {} 2 7 0 {Bando's Whitestone} {Usable by any psionicist champion. This artifact enables psionicists to cast wizard spells.} VR {} {32 33} {d19 o19} 1}
    {PO  108 +4 2 7 0 {Quill Pen of the Planes} {The attached champion may duplicate the effect of any one spell, psionic power card, or psionicist champion power in play.} VR {} {32 33} {} 1}
    {PO  109 {} 2 7 0 {The Tantelear} {Usable by any champion. This artifact generates a wild talent. It allows the attached champion to duplicate the power of any one psionicist champion currently in play.} VR {} {32 33} {} 1}
    {PO  110 +2 9 0 0 {Boragh's Ring} {Allows monsters to use psionic power cards, but the psionic card's level are all reduced to +2. (Def)} VR {} {6 32 33} {d11 o11} 1}
    {PO  111 +2 9 0 0 {Shawl of Mordenheim} {Any monster with this shawl is immune to all offensive spells, offensive magical items, and artifacts specifically directed at monsters. (Def)} VR {} {6 32 33} {} 1}
    {PO  112 +1 9 0 0 {Sirrion's Brooch} {Usable only by clerics. Grants immunity from all offensive spells, offensive magical items, and artifacts. (Def)} VR {} {6 32 33} {} 1}
    {PO  113 {} 9 0 0 {Psionicist Bracelet} {Usable only by a psionicist champion. No wizard spells may be cast during any battle with this champion. (Off)} VR {} {27 32 33} {} 1}
    {PO  114 {} 9 0 0 {Psionicist Anklet} {Usable only by a psionicist champion. No cleric spells may be cast during any battle with this champion. (Off)} VR {} {27 32 33} {} 1}
    {PO  115 {} 15 7 0 Psionatrix {Played at the beginning of the player's turn, this card is not discarded. It affects all players and remains in effect until any other rule card is played. The Psionatrix reduces all psionicists to half their normal levels (round down) and prevents the use of their powers and psionic power cards.} VR {} 29 {} 1}
    {PO  116 {} 15 7 0 {Antimagic Cloud} {Played at the beginning of the player's turn, this card is not discarded. It affects all players and remains in effect until any other rule card is played. While the antimagic cloud is in effect, all spells, magical items, artifacts, and champions abilities (except psionicists') are nullified.} VR {} 29 {} 1}
    {PO  117 {} 15 7 0 {Poisoned Water} {Played at the beginning of the player's turn, this card is not discarded. It affects all players and remains in effect until any other rule card is played. Discard all swimmers in pools; no new swimmers may be put into play.} VR {} 29 {} 1}
    {PO  118 {} 15 7 0 {The Ultimate Rule} {Played at the beginning of the player's turn, this card is not discarded. It affects all players and remains in effect until the end of the game. No new rule card can be played. Limit one per deck.} VR {} 29 {} 1}
    {PO  119 {} 15 7 0 {Cosmic Intervention} {Play at the beginning of your turn to cancel the Ultimate Rule Card. Both cards are sent to the Abyss (taken out of play). Limit one per deck.} VR {} 29 {} 1}
    {PO  120 {} 15 7 0 {Avatar's Edict} {Played at the beginning of the player's turn, this card is not discarded. It affects all players and remains in effect until any other rule card is played. Avatars can be played without discarding clerics.} VR {} 29 {} 1}
}
