set CrossFire::cardDataBase {
    {Runes & Ruins}
    {RR    1 9 13 2 0 {Isle of the Ape} {Can defend itself as a level 9 monster. Cannot be attacked by heroes or clerics. Defenders are immune to offensive spells and offensive psionic power cards.} R {} 31 1 1}
    {RR    2 {} 13 7 0 {The Forbidden City} {Cannot be attacked by earthwalkers. Allies defending this realm are doubled in base level.} C {} 31 {} 1}
    {RR    3 {} 13 7 0 {The Lost Caverns of Tsojcanth} {Cannot be attacked by flyers or swimmers. Defenders of this realm are immune to offensive spells.} C {} 31 {} 1}
    {RR    4 {} 13 7 0 {White Plume Mountain} {Players attacking this realm must discard a card from their hand during each round of battle.} UC {} 31 {} 1}
    {RR    5 {} 13 7 0 {Doc's Island} {Can only be attacked by swimmers or flyers. Magical items and artifacts of attackers lose their bonuses but not their powers.} C Coast. {5 31} {} 1}
    {RR    6 {} 13 1 0 {The City of Phlan} {Cannot be attacked by monsters unless Zhentil Keep is somewhere in play. Immune to offensive cleric spells.} R {Coast.  Attached holding is not immune.} {5 31} {} 1}
    {RR    7 {} 13 7 0 {The Barrier Peaks} {Can only be attacked by flyers or earthwalkers. Defending dwarves double their base levels and are immune to offensive psionics.} C {} 31 {} 1}
    {RR    8 {} 13 7 0 {Tomb of Horrors} {Cannot be attacked by flyers. Defending monsters are immune to offensive spells and the special powers of avatars.} C {} 31 {} 1}
    {RR    9 {} 13 7 0 {Demonweb Pits} {Any elf (drow) defending this realm is doubled in base level and is immune to offensive spells. Spells cast by defending drow during a round of battle cannot be dispelled.} C {} 31 {} 1}
    {RR   10 {} 13 7 0 {The Hidden Shrine of Tamoachan} {Clerics defending this realm are immune to offensive psionic power cards. Defending avatars are not discarded if defeated, but return to their pool at the end of his player's next turn.} UC {} 31 {} 1}
    {RR   11 {} 13 7 0 {The Depths of the Earth} {Cannot be attacked by flyers or swimmers. Defending swimmers are doubled in base level. If razed, the attacking champion must discard all attached magical items and artifacts.} C {} 31 {} 1}
    {RR   12 7 13 7 0 {Isle of Dread} {Can defend itself as a level 7 monster. Can only be attacked by flyers or swimmers.} C Coast. {5 31} 1 1}
    {RR   13 {} 13 7 0 {Desert of Desolation} {Cannot be attacked by swimmers. Defending undead gain 4 levels.} R {} 31 {} 1}
    {RR   14 {} 13 7 0 {The Glacial Rift} {Cannot be attacked by swimmers. Defending giants gain 2 levels and are immune to offensive spells and offensive magical items.} C {} 31 {} 1}
    {RR   15 {} 13 7 0 {The Lendore Isles} {Cannot be attacked by monsters or heroes. If this realm is razed, this player may return the bottom card from his discard pile to his hand.} C Coast. {5 31} {} 1}
    {RR   16 {} 13 7 0 {The Lost City} {Cannot be attacked by flyers or swimmers. Only AD&D champions can attack this realm; champions from other worlds cannot attack.} UC {} 31 {} 1}
    {RR   17 {} 13 7 0 {Village of Orlane} {Defending heroes double their base levels. Attacking monsters are at half their base levels (rounded down) and lose their special powers.} UC {} 31 {} 1}
    {RR   18 7 13 7 0 {Sunderhan, Isle of the Slave Lords} {Can defend itself as a level 7 hero. Champions (and any attached items) and their allies who are defeated while attacking this realm are sent to the Abyss.} R {} 31 {1 d18 o18} 1}
    {RR   19 {} 8 7 0 {Keep on the Borderlands} {When this holding is played, choose one type of champion that cannot attack the attached realm (hero, monster, etc).} R {} 31 {} 1}
    {RR   20 {} 8 7 0 {Palace of the Silver Princess} {Champions attacking this realm are halved (rounded down) in total levels and cannot use allies.} C {} 31 {} 1}
    {RR   21 {} 8 7 0 {Labyrinth of Madness} {Champions attacking the attached realm must draw and discard a card, noting the last digit of its number. If the number is higher than the attacker's base level, the champion is sent to Limbo. The attacker may continue.} C {} 31 {} 1}
    {RR   22 {} 8 7 0 {Village of Hommlet} {The attached realm must be razed twice during one player's turn to earn spoils of victory. The holding is not discarded until the realm is razed twice.} UC {} 31 {} 1}
    {RR   23 {} 8 7 0 {Oasis of White Palm} {Events cannot be played when attacking the attached realm.} C {} 31 {} 1}
    {RR   24 {} 8 7 0 {Ghost Tower of Iverness} {The attached realm cannot be attacked by a champion of base level 6 or less.} C {} 31 {} 1}
    {RR   25 {} 8 7 0 {Vault of the Drow} {Defending elf (drow) champions can cast spells and use psionic power cards.} C {} 31 {d4 o4 d11 o11 d19 o19} 1}
    {RR   26 {} 8 2 0 {Tenser's Castle} {The attached realm can only be attacked by heroes or wizards, and all attacking allies must be flyers or swimmers.} UC {} 31 {} 1}
    {RR   27 {} 8 7 0 {The Temple of Death} {The attached realm can only be attacked by clerics. Offensive spells cast in defense of the attached realm are doubled in level.} C {} 31 {} 1}
    {RR   28 9 20 2 0 {Bigby the Great} {Bigby can cast one spell turning spell during one other player's turn. He is immune to offensive spells and psionic power cards when defending a Greyhawk realm.} R {} {32 33} {1 2 d9 o9 d19 o19} 1}
    {RR   29 8 20 2 0 {Tenser the Arch Mage} {Tenser can elect to be a hero able to cast cleric spells during any one battle, chosen before combat begins. Tenser can cast wizard spells during another player's phase 4 to aid a player in battle.} UC {} {32 33} {1 2 d4 o4 d9 o9 d18 o18 d19 o19} 1}
    {RR   30 10 10 7 0 {Oonga the Ape} {Ignores the effects of any holding in play. The attached holding of any realm he attacks is discarded at the beginning of the battle.} R {} {32 33} {1 2 d9 o9} 1}
    {RR   31 6 10 7 0 {Falx the Silver Dragon} {Flyer. Can cast wizard spells. Any magical items attached to Falx cannot be discarded by any means. Gains 1 additional level for each attached magical item.} C {} {8 16 32 33} {1 2 d101 o101 d9 o9 d19 o19} 1}
    {RR   32 7 7 2 0 {Lord Robilar} {Robilar's mechanical steed grants him the ability to earthwalk. He is immune to offensive cleric spells and the special powers of avatars.} C {} {13 32 33} {1 2 d9 o9 d18 o18} 1}
    {RR   33 5 10 7 0 {Phoebus the Lizard Man} {Swimmer. If defeated in battle, Phoebus's allies return to the player's hand. Opposing champions' magical items are discarded at the end of battle, win or lose.} C {} {37 32 33} {1 2 d9 o9} 1}
    {RR   34 18 20 2 1 {Vecna the Arch Lich} {Avatar. A Greyhawk champion with the Eye and Hand of Vecna must be discarded to bring Vecna into play. Vecna is immune to offensive spells, psionics, and unarmed combat cards. All allies played with the lich are considered undead; they return to the player's hand after a victorious battle.} R Undead. {32 40} {1 2 d9 o9 d19 o19 o102 d102} 1}
    {RR   35 9 7 2 0 {Kas the Terrible} {Undead. Immune to the effects of harmful events while in combat. If opposing Vecna in battle with the Sword of Kas, Vecna's base level is 0.} UC {} {40 32 33} {1 2 d9 o9 d18 o18 o102 d102} 1}
    {RR   36 4 7 2 0 {Grimslade the Gray} {Can cast wizard spells. Whenever Grimslade attacks, his player draws and discards a card, noting the last digit. If it is 3 or less, the opponent can play no more cards during the battle.} C {} {32 33} {1 2 d9 o9 d18 o18 d19 o19} 1}
    {RR   37 7 7 1 0 {Ren o' the Blade} {Ren can be sent to the Abyss to retrieve a realm from the discard pile, placing it in the player's formation during phase 2 instead of playing a realm from his hand.} R {} {32 33} {1 2 d9 o9 d18 o18} 1}
    {RR   38 8 10 7 0 {Acererak the Eternal} {Undead. Can cast wizard spells and use psionic power cards. Can summon one undead ally from any discard pile to aid him in battle, which returns to its original discard pile afterward.} R {} {40 32 33} {1 2 d9 o9 d11 o11 d102 o102 d19 o19} 1}
    {RR   39 8 7 1 0 Wulfgar {Dwarves and halflings cannot stand against Wulfgar in battle. Because of his hammer, the Aegis-fang, Wulfgar's base level is doubled against giant and dragon champions.} C {} {32 33} {1 2 d9 o9 d18 o18} 1}
    {RR   40 7 10 7 0 {Jarl the Frost Giant} {Earthwalker. Jarl ignores the special powers of all realms. He gains 6 levels when defending the Glacial Rift.} C {} {13 17 32 33} {1 2 d9 o9} 1}
    {RR   41 7 10 7 0 {King Snurre the Fire Giant} {Earthwalker. If King Snurre doesn't attack on his turn, at the beginning of another player's turn he can order an opponent's champion not to attack that turn.} C {} {13 17 32 33} {1 2 d9 o9} 1}
    {RR   42 5 10 7 0 {Queen Frumpy the Fire Giant} {Can cast cleric spells. Queen Frumpy gains 2 levels when defending a realm. She is so repulsive, allies of +4 or less cannot be played against her.} C {} {17 32 33} {1 2 d4 o4 d9 o9} 1}
    {RR   43 5 10 7 0 {The Keeper} {Giant. This deformed hill giant is immune to offensive psionics. One artifact of any world can be attached to him; it is never discarded, returning instead to the player's hand.} UC {} {17 32 33} {1 2 d9 o9} 1}
    {RR   44 6 10 7 0 {Nosnra the Hill Giant} {Nosnra can attack any AD&D realm, regardless of position or powers. Nosnra is level 10 if no allies are played with him.} C {} {17 32 33} {1 2 d9 o9} 1}
    {RR   45 4 7 7 0 {Ombi the Renegade Dwarf} {Ombi gains earthwalking if any player has a giant in play. He can be used as an ally for any giant in battle, returning to his pool afterward unless discarded during battle.} C {} {12 32 33} {1 2 d9 o9 d18 o18} 1}
    {RR   46 {} 19 0 0 {Mordenkainen's Disjunction} {Destroys all magical items and artifacts in one pool unless the affected player can draw a card with a last digit of 2 or less (drawn card is discarded). (Off/3)} R {} {27 32} {} 1}
    {RR   47 {} 4 0 0 {Slay Living} {Kills any opposing champion or ally of base level 5 or less. Undead are immune to this spell. (Off/3/4)} C {} {27 32 33} {} 1}
    {RR   48 {} 4 0 0 Intercession {Can be cast at any time. This spell cancels the effects of any just-played event card. (Off)} UC (Def) {6 29 30 31 32 33 34} {} 1}
    {RR   49 +6 4 0 0 {Conjure Earth Elemental} {The +6 ally summoned with this spell stays with the casting champion until the beginning of this player's next turn. Opposing earthwalking allies are immediately discarded. (Off/4)} UC {} {27 33} {} 1}
    {RR   50 +5 4 0 0 {Conjure Fire Elemental} {The +5 ally summoned with this spell stays with the casting champion until the beginning of this player's next turn. Opposing allies of +2 or less are incinerated (discarded). (Off/4)} C {} {27 33} {} 1}
    {RR   51 +4 4 0 0 {Conjure Air Elemental} {The +4 ally summoned with this spell stays with the casting champion until the beginning of this player's next turn. Opposing flying allies are immediately discarded. (Off/4)} UC {} {27 33} {} 1}
    {RR   52 +3 4 0 0 {Conjure Water Elemental} {The +3 ally summoned with this spell stays with the casting champion until the beginning of this player's next turn. Opposing swimming allies are immediately discarded. (Off/4)} C {} {27 33} {} 1}
    {RR   53 {} 19 0 0 Crystalbrittle {Destroys one magical item anywhere in play. (Off/3/4)} C {} {27 32 33} {} 1}
    {RR   54 {} 19 0 0 {Energy Drain} {Draw and discard a card when this spell is cast, noting the last digit. Subtract that number from the target champion's level. If the level reaches 0, the champion is discarded. Undead are immune to this spell. (Off/3/4)} UC {} {27 32 33} {} 1}
    {RR   55 {} 6 0 0 {Tyranthraxus, the Possessing Spirit} {Play on an opponent's champion, who then becomes a monster able to cast wizard spells. The champion remains under control of the event player until canceled. (Harmful)} R {} {22 29 30 31 32 33 34} {1 2 d9 o9 d19 o19} 1}
    {RR   56 {} 6 0 0 {Coming of the Phoenix} {Retrieve one champion (excluding avatars) from the discard pile and put it into play. (Helpful)} C {} {23 29 30 31 32 33 34} {} 1}
    {RR   57 {} 6 0 0 {The Forgotten King} {If their first attack is successful, all heroes can make an additional attack until the end of this player's next turn. All heroes are considered earthwalkers during this event. (Helpful)} R {} {23 29 30 31 32 33 34} {} 1}
    {RR   58 {} 6 0 0 {Elixir of Life} {Play on a champion who is about to be defeated. He returns to his pool instead of being discarded. If the player was attacking, he can continue with another champion. No spoils of victory are drawn for the champion's defeat. (Helpful)} C {} {23 29 30 31 32 33 34} {} 1}
    {RR   59 {} 6 0 0 {Giant Raid!} {All giants in play double their total levels when attacking until this player's next turn. (Helpful)} UC {} {23 29 30 31 32 33 34} {} 1}
    {RR   60 {} 6 0 0 {The Vampire Attacks!} {All attacking undead are immune to opposing champions' special powers until this player's next turn. (Helpful)} UC {} {23 29 30 31 32 33 34} {} 1}
    {RR   61 {} 6 0 0 {Undead Guardian} {Creates an undead level 5 monster until the beginning of this player's next turn. It is the first to defend this player's realms during attacks by all other players. Any spoils obtained by it are doubled. (Helpful)} R {} {23 29 30 31 32 33 34} {1 2 d9 o9 d102 o102} 1}
    {RR   62 {} 6 0 0 {Barbarian Charge!} {Attacking champions who do not use spells or psionic power cards are doubled in base level until the beginning of this player's next turn. (Helpful)} C {} {23 29 30 31 32 33 34} {} 1}
    {RR   63 {} 6 0 0 {Psionic Shield} {This player's realms, champions, and allies are immune to offensive psionic power cards until the beginning of his next turn. (Helpful)} UC {} {23 29 30 31 32 33 34} {} 1}
    {RR   64 {} 6 0 0 {Volcanic Eruption} {This event razes all realms that can only be attacked by swimmers or earthwalkers. (Harmful)} UC {Attacked by EITHER swimmers or earthwalkers.} {22 29 30 31 32 33 34} {} 1}
    {RR   65 +2 2 7 0 {The Midas Orb} {Champions of base level 3 or less cannot defend against a champion with the Midas Orb. The Orb changes one opposing ally to gold, sending it to the Abyss.} C {} {32 33} {} 1}
    {RR   66 {} 2 7 0 {Invulnerable Coat of Arnd} {Can only be attached to heroes of any world. Heroes wearing this artifact ignore the levels and powers of all magical items, and opposing allies' levels are halved (rounded down).} UC {} {32 33} {} 1}
    {RR   67 +2 2 7 0 {Ipsissimo's Black Goose} {Can only be attached to clerics of any world. When the attached cleric is in this player's pool, it and all other clerics in the pool are immune to harmful events.} C {} {32 33} {} 1}
    {RR   68 {} 2 7 0 {Tenser's Crystal Ball} {Can only be attached to wizards of any world. At the beginning of this player's turn, inspect the draw deck of an opposing player. At any time, the player can discard the Crystal Ball to shuffle an opponent's draw pile.} C {} {32 33} {} 1}
    {RR   69 +5 2 1 0 Albruin {Cannot be attached to clerics or wizards. Any monster opposing the attached champion is at half its base level (rounded down). Opponents cannot use psionic power cards.} C Sword {38 44 32 33} {} 1}
    {RR   70 +4 2 7 0 Blackrazor {The attached champion must attack during his turn or discard one champion from his pool. Allies attached to this champion during battle are immune to offensive spells, psionics, and the special powers of champions and allies.} R Weapon {44 32 33} {} 1}
    {RR   71 +5 2 7 0 Wave {Can only be attached to swimming champions of any world. Nonswimming allies played with the attached champion are considered swimmers. Allies who are already swimmers are doubled in level.} UC Weapon {44 32 33} {} 1}
    {RR   72 +6 2 7 0 Whelm {Can only be attached to dwarf champions of any world. This weapon automatically defeats giants. Whelm returns to the player's hand if the attached champion is discarded.} R Weapon {44 32 33} {} 1}
    {RR   73 {} 9 0 0 {Girdle of Dwarvenkind} {The attached champion is considered a dwarf for the purposes of card play, gaining earthwalking ability. (Def)} R {} {6 32 33} {} 1}
    {RR   74 +2 9 0 0 {Star Gem of Martek: Opal} {The attached champion can use psionic power cards. If joined with another Star Gem, the attached champion is immune to offensive psionics. (Def)} C {} {6 32 33} {d11 o11} 1}
    {RR   75 +3 9 0 0 {Star Gem of Martek: Sapphire} {Allies played with the attached champion cannot be removed by any means. If joined with another Star Gem, the attached champion gains an additional 5 levels. (Def)} UC {} {6 32 33} {} 1}
    {RR   76 +2 9 0 0 {Star Gem of Martek: Ruby} {Undead cannot use their special powers when opposing the attached champion. If joined with another Star Gem, the attached champion is immune to harmful events. (Def)} C {} {6 32 33} {} 1}
    {RR   77 +1 9 0 0 {Star Gem of Martek: Clear Crystal} {Spells cast by the attached champion cannot be dispelled. If all five Star Gems are joined, the attached champion can choose to win any battle, automatically razing the realm. If this power is used, the Star Gems are discarded. (Def)} R {} {6 32 33} {} 1}
    {RR   78 +4 9 0 0 {Star Gem of Martek: Amethyst} {If the attached champion is discarded as a result of combat, the opposing champion is sent to the Abyss. If joined with another Star Gem, the attached champion can cast any spell. (Off)} UC {} {27 32 33} {d4 o4 d19 o19} 1}
    {RR   79 +3 9 0 0 {Big Giant's Rock} {Usable only by giants. Opposing champions must discard one ally of level 4 or less if this item is played during a battle. (Off)} C {Rock owner's choice.} {27 32 33} {} 1}
    {RR   80 +6 9 0 0 {Huge Giant's Rock} {Usable only by giants. Opposing champions must discard one ally of level 7 or less if this item is played during battle. Opponents cannot add magical items in battle. (Off)} C {Rock owner's choice.} {27 32 33} {} 1}
    {RR   81 +9 9 0 0 {Enormous Giant's Rock} {Usable only by giants. Destroys one opposing ally and artifact when played in battle, and no further allies can be played by the opponent. (Off)} R {Rock owner's choice.} {27 32 33} {} 1}
    {RR   82 +3 1 0 0 Hypnosnake {This ally hypnotizes one opposing ally chosen at any time during the battle, causing that ally to switch sides.} C {} 33 {} 1}
    {RR   83 +2 1 0 0 {The Rahasia} {If the attached champion is defeated in battle, the opposing player must discard all champions and events in his hand.} R {} 33 {} 1}
    {RR   84 +6 1 0 0 Remorhaz {This ally is +8 if played with a giant. Any additional allies played by this player are immune to offensive psionics for this round of battle.} UC {} 33 {} 1}
    {RR   85 +3 1 0 0 {The Incantrix} {Immune to offensive spells. When this ally is played, all spells in play are dispelled.} R {} 33 {} 1}
    {RR   86 +4 1 0 0 {Winter Wolf Pack} {Increases to +8 when allied with giants. Doubles the base level of any champion defending the Glacier Rift.} C {} 33 {} 1}
    {RR   87 +4 1 0 0 Hydra {Gains 2 levels for each additional ally played by this player during a round of battle. Immune to the powers of opposing allies.} C {} 33 {} 1}
    {RR   88 +5 1 0 0 {Red Dragon} {Flyer. This ally's level increases to +7 if played with a dragon champion. All allies played after the red dragon may be considered flyers (player's choice).} UC {} {8 16 33} {o101 d101} 1}
    {RR   89 +4 1 0 0 {Rampaging Oni} {When played, all psionic power cards in play are canceled and no more can be played during this round of battle. Oni becomes +7 if played with a Forgotten Realms Champion.} C {} 33 {} 1}
    {RR   90 +4 1 0 0 {The Live Ones} {Playing this ally cancels the special powers of any opposing wizard for one round of combat. This ally returns to the player's hand at the conclusion of a victorious battle.} R {} 33 {} 1}
    {RR   91 {} 18 0 0 {Flying Kick} {Unarmed combat card; usable only by heroes. This maneuver can either count as +5 in any battle or it can destroy (discard) an ally or maigcal item of +5 or less (this player's choice). (Off/4)} C {} {27 33} {} 1}
    {RR   92 +7 18 0 0 Haymaker {Unarmed combat card; usable only by heroes. Opponent must draw and discard a card, noting the last digit. If the opposing champion's base level is equal to or less than the digit, the opponent is defeated. Undead are immune to this maneuver. (Off/4)} R {} {27 33} {} 1}
    {RR   93 +4 18 0 0 Uppercut {Unarmed combat card; usable only by heroes. Victims of this maneuver cannot cast spells or use psionic power cards during this round of battle. (Off/4)} UC {} {27 33} {} 1}
    {RR   94 +2 18 0 0 Disarm {Unarmed combat card; usable only by heroes. This maneuver strips away (discards) one magical item or artifact of an opposing champion (this player's choice). (Off/4)} C {} {27 33} {} 1}
    {RR   95 +3 18 0 0 {Kidney Punch} {Unarmed combat card; usable only by heroes. The opposing player must discard a card from his hand before he can play any more cards in battle. Undead are immune to this maneuver. (Off/4)} R {} {27 33} {} 1}
    {RR   96 +5 18 0 0 {Bear Hug} {Unarmed combat card; usable only by heroes. This maneuver halves the levels (rounded down) of an opposing champion and one ally chosen by this player. Undead are immune to this effect. (Off/4)} C {} {27 33} {} 1}
    {RR   97 +3 18 0 0 Knockdown {Unarmed combat card; usable only by defending heroes. When this card is played, the opposing champion must draw and discard a card, noting the last digit. If the number is 4 or less, the opponent returns to his pool defeated. (Def/4)} C {} {6 33} {} 1}
    {RR   98 +3 18 0 0 Headlock {Unarmed combat card; usable only by heroes. Any unarmed combat cards played by this champion after this one are doubled in level. (Def/4)} UC {} {6 33} {} 1}
    {RR   99 {} 18 0 0 Block {Unarmed combat card; usable only by heroes. This maneuver counters any just-played offensive unarmed combat card, negating its effect and sending it to the discard pile. (Def/4)} C {} {6 33} {} 1}
    {RR  100 {} 15 7 0 {The Monty Haul Campaign} {Played at the beginning of this player's turn, this card is not discarded. It affects all players and remains in effect until any other rule card is played. All champions in play can cast any type of spell, use psionic power cards, and attach artifacts from any world. Only legally allowable artifacts remain if this rule card is removed from play.} R {} 29 {2 d4 o4 d11 o11 d19 o19} 1}
    {RR  101 +10 1 0 0 {The Dream Team} {Playing this ally during a round of battle discards all other allies in play. Further allies played by opponents cannot use their special powers.} VR {} 33 {} 1}
    {RR  102 {} 6 0 0 {Brain Drain} {Play this event to cancel a just-used psionic card or psionic ability or play on an opponent's pool to prevent the use of psionics by champions until the end of this player's next turn. (Harmful)} VR {} {22 29 30 31 32 33 34} {} 1}
    {RR  103 +2 9 0 0 {The Toad} {Play this magical item during a round of battle to reduce an opposing wizard's or cleric's base level to 0. If attached to a monster, the champion gains an additional 4 levels. (Off)} VR {} {27 32 33} {} 1}
    {RR  104 {} 6 0 0 {Lost Treasure} {Play this event to retrieve a magical item or artifact from the discard pile or to send a magical item or artifact to the Abyss. (Helpful/Harmful)} VR {} {22 23 29 30 31 32 33 34} {} 1}
    {RR  105 +6 2 7 0 {Holy Sword Chrysomer} {Can only be attached to heroes of any world (excluding undead). Destroys up to 10 levels of opposing undead allies. Undead champions of level 8 or less cannot enter battle against the attached champion.} VR Sword {38 44 32 33} {} 1}
    {RR  106 8 20 1 0 {Manshoon of the Zhentarim} {If Manshoon is about to be discarded for any reason (including through combat but excluding being sent to the Abyss), his player can discard a card from his hand instead. Manshoon returns to his pool; he cannot be used again until his player's next turn.} VR {} {32 33} {1 2 d9 o9 d19 o19} 1}
    {RR  107 {} 6 0 0 {Undead Regeneration} {Retrieve all undead from the event player's discard pile. Champions go directly to the pool, and allies to his hand. (Helpful)} VR {} {23 29 30 31 32 33 34} {} 1}
    {RR  108 {} 2 4 0 {The Dark Lens} {Can only be attached to psionicists. Adds 3 levels to any psionic power card bonus. Can be discarded to use a psionic power card that cannot be canceled or countered by any means. Opposing champions cannot use psionic power cards.} VR {} {32 33} {} 1}
    {RR  109 {} 9 0 0 {Book of the Damned} {Can only be attached to wizards. If successful during a round of combat, one friendly ally remains with the wizard, becoming undead; its level and powers are unchanged. (Def)} VR {} {6 32 33} {} 1}
    {RR  110 {} 9 0 0 {Horn of Change} {Can only be attached to monsters. Once per round of battle this item forces an opponent to discard a just-played card and replace it with another. If he cannot legally play another card, he automatically loses the battle. (Off)} VR {} {27 32 33} {} 1}
    {RR  111 {} 2 2 0 {Kuroth's Quill} {Once per round of combat the attached champion can choose to ignore the level bonus or power of any card or double the level bonus of a just-cast spell.} VR {} {32 33} {} 1}
    {RR  112 {} 6 0 0 Dodge {Play to instantly counter one unarmed combat card or ignore one opposing ally's special power. If played to counter an unarmed combat card, this player draws two cards. (Helpful)} VR {} {23 29 30 31 32 33 34} {} 1}
    {RR  113 +2 9 0 0 {Runes of the Future} {The attached champion can be discarded at the end of his player's turn to search his draw deck for any one card. Place this card so it is the first or second card drawn on the next turn. (Def)} VR {} {6 32 33} {} 1}
    {RR  114 +1 9 0 0 {Cursed Idol} {If the attached champion is discarded as a result of combat, the idol transfers to the opposing champion and inflicts a terrible curse. The cursed champion must attack every round. If he cannot, his player must raze his foremost realm. (Off)} VR {} {27 32 33} {} 1}
    {RR  115 {} 8 3 0 {Tower of Spirits} {Only undead may attack the attached realm.} VR {} 31 {} 1}
    {RR  116 5 7 7 0 {Gib Kcir} {Immune to harmful events. Discard this champion from her pool to the Abyss to send any nonrealm card in play to the Abyss as well.} VR {} {32 33} {1 2 d9 o9 d18 o18} 1}
    {RR  117 {} 4 0 0 {Dispel Psionics} {This spell can be cast at any time to negate the effects of a psionic power card or a psionicist's special power. Negated special powers cannot be used again until the end of that player's next turn. (Def)} VR {} {6 29 30 31 32 33 34} {} 1}
    {RR  118 {} 4 0 0 {Psionic Reflection} {This spell can be cast at any time to reflect back the effects of a just-played offensive psionic power card upon the original user. (Def)} VR {} {6 29 30 31 32 33 34} {} 1}
    {RR  119 {} 2 7 0 {Icon of Magic} {All champions in play must ask this player's permission to use offensive wizard spells.} VR {} {32 33} {} 1}
    {RR  120 {} 2 7 0 {Nectar of the Gods} {All champions in play must ask this player's permission to use offensive cleric spells.} VR {} {32 33} {} 1}
    {RR  121 {} 9 0 0 {Boots of Fharlanghn} {The champion wearing these boots gains earthwalking and swimming abilities as needed. A cleric wearing these boots can make unlimited attacks upon an opponent's realm until it is razed or the cleric is defeated. (Off)} VR {} {27 32 33} {} 1}
    {RR  122 {} 13 7 0 {The Crystal Cave} {Only spells can be used when attacking this realm by combat. Allies, magical items, and artifacts have no effect.} VR {} 31 {} 1}
    {RR  123 4 7 7 0 {The Fair Princess} {In combat, this champion banishes opposing dragons to Limbo until the end of their owner's next turn. Dragon allies cannot be played against her.} VR {} {32 33} {1 2 d9 o9 d18 o18} 1}
    {RR  124 {} 9 0 0 {The Phylactery} {Can only be attached to a spellcasting undead champion. If this champion is defeated as a result of combat, send this item to the Abyss to return him to his pool instead.} VR (Def) {6 32 33} {} 1}
    {RR  125 {} 6 0 0 {Portal to Limbo} {Play this event on an opponent's champion, who must draw and discard a card noting the last digit. The affected champion is sent to Limbo for a number of turns equal to the digit. (Harmful)} VR {} {22 29 30 31 32 33 34} {} 1}
}
