set CrossFire::cardDataBase {
    {The Underdark}
    {UD    1 {} 13 4 0 UnderAthas {This realm extends under opponent's Dark Sun realms, allowing them to be attacked by this player's champions and allies, regardless of position or restrictions.} C {} {42 31} {} 1}
    {UD    2 {} 13 7 0 {The Unipolar Triumvirate} {Adds a +3 Underdark ally to all champions of this player when attacking. The ally is negated by any other Triumvirate realm in play unless in the same player's formation.} C {} {42 31} {} 1}
    {UD    3 {} 13 5 0 UnderKrynn {This realm extends under opponent's Dragonlance realms, allowing them to be attacked by this player's champions and allies, regardless of position or restrictions.} C {} {42 31} {} 1}
    {UD    4 {} 13 7 0 {The Bipolar Triumvirate} {Adds a +6 Underdark ally to all champions of this player when attacking and negates the ally gained from the Unipolar Triumvirate. This ally is negated by the Tripolar and Ultimate Triumvirates unless in the same player's formation.} UC {} {42 31} {} 1}
    {UD    5 {} 13 7 0 {The Underdark} {This realm extends under all opponent's realms that have attached holdings, allowing the realms to be attacked by this player's champions and allies, regardless of position or restrictions.} R {} {42 31} {} 1}
    {UD    6 {} 13 7 0 {The Tripolar Triumvirate} {Adds a +9 Underdark ally to all champions of this player when attacking and negates the ally gained from the Unipolar and Bipolar Triumvirates. This ally is negated by the Ultimate Triumvirate unless in the same player's formation.} R {} {42 31} {} 1}
    {UD    7 {} 13 1 0 UnderToril {This realm extends under opponents' Forgotten Realms realms, allowing them to be attacked by this player's champions and allies, regardless of position or restrictions.} C {} {42 31} {} 1}
    {UD    8 {} 13 2 0 UnderOerth {This realm extends under opponent's Greyhawk realms, allowing them to be attacked by this player's champions and allies, regardless of position or restrictions.} C {} {42 31} {} 1}
    {UD    9 {} 13 3 0 UnderDread {This realm extends under opponent's Ravenloft realms, allowing them to be attacked by this player's champions and allies, regardless of position or restrictions.} C {} {42 31} {} 1}
    {UD   10 {} 8 4 0 {The Burning Cavern} {Ancient magic from Athas's Blue Age decrees that this player's allies are immune to psionic power cards.} UC {} 31 {} 1}
    {UD   11 {} 8 7 0 {The Unipolar Cavern} {If attached to any Triumvirate realm, the Underdark ally gained from the realm is immune to offensive spells.} C {} 31 {} 1}
    {UD   12 {} 8 5 0 {Subterranean Seas} {The stormy underdark of Krynn grants player's allies the ability to become swimmers.} UC {} 31 {} 1}
    {UD   13 {} 8 7 0 {The Bipolar Cavern} {If attached to any Triumvirate realm, the Underdark ally gained from the realm can be dwarves, elves, earthwalkers, flyers, swimmers, or undead, as needed.} UC {} 31 {} 1}
    {UD   14 {} 2 7 0 {The North Wind} {Usable only by an AD&D avatar. The attached champion and its allies can attack any realm, regardless of position or restrictions. If victorious, the realm is automatically razed.} C {} {32 33} {} 1}
    {UD   15 {} 8 7 0 {The Tripolar Cavern} {If attached to any Triumvirate realm, this player's Underdark allies gained from Triumvirate realms can also be used to defend.} UC {} 31 {} 1}
    {UD   16 {} 8 1 0 {Echoes from the Deep} {The magic of the Deep seeps upward, rendering this player's allies immune to psionic power cards.} R {} 31 {} 1}
    {UD   17 {} 8 2 0 {Cavern of the Gods} {The ancient power of the gods bestows immunity to this player's defending allies against the special powers of champions.} UC {} 31 {} 1}
    {UD   18 {} 8 3 0 {The Dread Chamber} {The dark powers, in a twist of fate, decree that this player's attacking champions are immune to the powers of all Ravenloft allies.} UC {} 31 {} 1}
    {UD   19 {} 6 0 0 {Gods' Plague} {All avatars in pools are destroyed. Immune to Limited Wish. (Harmful)} R {} {22 29 30 31 32 33 34} {} 1}
    {UD   20 {} 6 0 0 {When Gods Walk} {All avatars must attack until this player's next turn; avatars must be used first in defense. If unable to attack they are discarded. (Harmful)} R {} {22 29 30 31 32 33 34} {} 1}
    {UD   21 {} 6 0 0 {Drow Justice} {Played during combat, all champions and allies in battle who are not elves (including drow) or dragons are discarded. If both champions are slain, the battle is over with no victors. (Harmful)} R {} {22 29 30 31 32 33 34} {} 1}
    {UD   22 {} 6 0 0 {Memory Moss} {This creeping fungus purges a spellcaster of its spells. All spells currently held by the targeted player are discarded, and the affected champion cannot cast spells until the event is removed. (Harmful)} R {} {22 29 30 31 32 33 34} {} 1}
    {UD   23 {} 2 5 0 {The East Wind} {Usable only by a Dragonlance avatar. The attached champion and its allies can attack any 'eastern' realm (to this player's right), regardless of position or restrictions.} C {} {32 33} {} 1}
    {UD   24 {} 6 0 0 {The Forest Oracle} {This player's realms that show trees are protected from being razed or destroyed by spells and events until the end of his next turn. (Helpful)} UC {} {23 29 30 31 32 33 34} {} 1}
    {UD   25 {} 6 0 0 {Mika's Magic Ban} {All spellcasting champions (except Mika the Wolf Nomad) cannot cast spells until the end of this player's next turn. (Harmful)} UC {} {22 29 30 31 32 33 34} {} 1}
    {UD   26 {} 6 0 0 {Mika's Dragon Charm} {Until the end of his next turn, only this player may attack or defend with dragons. (Harmful)} C {} {22 29 30 31 32 33 34} {} 1}
    {UD   27 {} 6 0 0 {Mika's Undead Ward} {This player's undead champions and allies are protected until the end of this player's next turn. Cards that specifically harm the undead have no effect. (Harmful)} C (Helpful) {23 29 30 31 32 33 34} {} 1}
    {UD   28 +2 9 0 0 {Amulet of Protection from Artifacts} {The attached champion is immune to the effects of all artifacts. (Def)} R {} {6 32 33} {} 1}
    {UD   29 +3 9 0 0 {Armor of Dispel Magic} {Once per turn, the attached champion can dispel one spell against another player. The champion must then attack on its turn or be discarded. (Def)} C {} {6 32 33} {} 1}
    {UD   30 +3 9 0 0 {Cloak of the Gargoyle} {The attached champion is immune to wizard spells. If defeated in battle, the champion returns to its pool, stripped of all attachments. (Def)} C {} {6 32 33} {} 1}
    {UD   31 +4 9 0 0 {Dori's Obsidian Steed of Wondrous Power} {Created by Dori's friend Drawmij, this item lets the attached champion and its allies attack any realm. (Def)} UC {} {6 32 33} {} 1}
    {UD   32 {} 9 0 0 {Goibhniu's Warhammer} {Usable only by champions of level 12 or higher, the hammer automatically kills any wizard or psionicist. If the champion's level falls below 12, the hammer is discarded. (Off)} R Weapon {27 44 32 33} {} 1}
    {UD   33 {} 9 0 0 {Helmet of Selnor} {Once per turn, may charm a hero or cleric into acting as an ally to the attached champion. Regardless of outcome, the charmed champion returns to its pool stripped of attachments. (Off)} R {} {27 32 33} {} 1}
    {UD   34 +2 9 0 0 {Necklace of Protection} {The attached champion (but not its allies) is immune to the special powers of all avatars. (Def)} R {} {6 32 33} {} 1}
    {UD   35 {} 9 0 0 {Black Sail of Schnai} {Cannot be played on an undead champion. If the attached champion is killed in battle, it returns at the end of the player's next turn as an undead champion. Powers and abilities remain unchanged. (Def)} UC {} {6 32 33} {} 1}
    {UD   36 +2 9 0 0 {Shovel of Gravedigging} {If used by an undead champion, its allies gain an additional +2. If the allies are also undead, they gain +4. (Def)} C {} {6 32 33} {} 1}
    {UD   37 {} 19 0 0 {Hornung's Guess} {The might of Hornung is such that this spell can be cast at any time. This player can look at one other player's hand and discard one realm. (Off)} UC {} {27 29 30 31 32 33 34} {} 1}
    {UD   38 {} 19 0 0 {Hornung's Baneful Deflector} {This player's champion and its allies are immune to the special powers of allies for this round of combat. (Def/3/4)} C {} {6 32 33} {} 1}
    {UD   39 {} 19 0 0 {Maximillian's Earthen Grasp} {Cast only on a hero. The affected champion cannot attack or defend until the end of its owner's next turn. (Off/3)} C {} {27 32} {} 1}
    {UD   40 {} 19 0 0 {Shattered Glass} {Opponent cannot play one specified type of card (cleric or wizard spells, psionic power cards, allies, magical items, artifacts, or events) for this round of battle. Any already in play are discarded. (Off/4)} R {} {27 33} {} 1}
    {UD   41 {} 19 0 0 {Lorloveim's Creeping Shadow} {The caster's shadow creeps around the table, letting him see all cards concealed under realms or face down in pools. (Off/3)} C {} {27 32} {} 1}
    {UD   42 {} 19 0 0 {Locate Creature} {Allows the caster to see all allies of a specific type (earthwalkers, flyers, swimmers, or undead) held in player's hands. Discard one card of that type from each opponent. (Off/3)} UC {} {27 32} {} 1}
    {UD   43 {} 19 0 0 {Summon Lycanthrope} {All cards in players' hands that specify werebeasts or lycanthropes (except realms and holdings) must be played to aid the caster. Discard summoned cards after use. (Off/4)} C {Champions are summoned and used as allies.} {27 33} {} 1}
    {UD   44 {} 19 0 0 {Mind Fog} {Cast on one player's pool. All spellcasters and psionic power card users in that pool cannot cast spells or use psionic power cards until the end of that player's next turn. (Off/3)} UC {} {27 32} {} 1}
    {UD   45 {} 19 0 0 {Bloodstone's Spectral Steed} {Only monsters can enter combat with this champion. The champion and its allies become flyers for one round of combat. (Off/3)} C {} {27 32} {} 1}
    {UD   46 {} 4 0 0 {Summon Undead} {Cast only by champions of level 13+. All undead champions and allies from players' pools and hands come to the aid of the caster. Allies are discarded; champions return to pools. (Off/4)} UC {Undead come with attachments.} {27 33} {} 1}
    {UD   47 {} 4 0 0 {Warband Quest} {Cast only by champions of level 13+. Each champion in one pool gains 4 levels until the player's next turn. The spell may be continued each turn by discarding a realm. (Def/3)} C {} {6 32} {} 1}
    {UD   48 {} 4 0 0 {Wolf Spirits} {Cast only by champions of level 13+, this spell creates an ally equal to the base level of the caster. The wolf spirits devour an equal number of points of opposing allies. (Def/3/4)} UC {} {6 32 33} {} 1}
    {UD   49 {} 4 0 0 Stalker {Cast only by champions of level 13+, this spell creates a permanent ally to guard one realm. The stalker's level is equal to the number of champions in the caster's pool. If the player's pool is discarded, the ally is lost. (Def/3/4)} R {} {6 32 33} {} 1}
    {UD   50 {} 2 1 0 {The South Wind} {Usable only by a Forgotten Realms avatar. The attached champion and its allies can attack any 'southern' realm (opposite this player), regardless of position or restrictions.} C {} {32 33} {} 1}
    {UD   51 {} 4 0 0 {Animal Horde} {Cast only by champions of level 13+. All allies in an opponent's hand come to the aid of this spellcaster. Discard allies after use. (Off/4)} R {} {27 33} {} 1}
    {UD   52 {} 4 0 0 {Elemental Swarm} {Cast only by champions of level 13+. This spell creates a swarm that sweeps through one player's pool. The swarm discards any cards equal in icon points to half the level of the caster (rounded down). (Off/3)} UC {} {27 32} {} 1}
    {UD   53 {} 4 0 0 Preservation {Cast only by champions of level 13+ on a realm, this spell remains in effect until dispelled or negated. The realm is immune to offensive spells. (Def/3/5)} C {} {6 32 34} {} 1}
    {UD   54 {} 4 0 0 {Ward Matrix} {Cast only by champions of level 13+, this spell connects the first realm of each player in a matrix, allowing each to be attacked (regardless of restrictions) until the end of this player's next turn. (Off/3)} C {} {27 32} {} 1}
    {UD   55 {} 4 0 0 {Age Dragon} {Cast only on dragons, the spellcaster can double the age (base level) of a dragon or halve the age (base level, rounded down) and take away its special powers. This spell lasts until dispelled. (Def/3/4) or (Off/3/4)} R {} {6 27 32 33} {} 1}
    {UD   56 {} 4 0 0 Mindkiller {The caster can send one champion to the Abyss or send one avatar to Limbo. The avatar remains in Limbo until the end of its owner's next turn. (Off/3/4)} R {} {27 32 33} {} 1}
    {UD   57 {} 4 0 0 Spacewarp {All attacks until the end of this player's next turn must be made against one realm chosen by the caster; if the realm is razed, a successful attack by the next player discards it. No further attacks can be made. (Off/3/5)} R {No effect if Spell Turned or Reflected.} {27 32 34} {} 1}
    {UD   58 {} 4 0 0 {Spirit of Power} {Any 4 clerics (excluding avatars) may band together to send an avatar to the Abyss. Each player who participates must discard a magical item, either from his hand or pool. (Off/3/4/5)} C {} {27 32 33 34} {} 1}
    {UD   59 {} 2 2 0 {The West Wind} {Usable only by a Greyhawk avatar. The attached champion and its allies can attack any 'western' realm (to this player's left), regardless of position or restrictions.} C {} {32 33} {} 1}
    {UD   60 {} 4 0 0 {Tentacle Walls} {Cast on a realm, this spell creates a permanent ally that devours all nonflying allies. The spell remains in effect until negated or dispelled. (Def/5)} C {} {6 34} {} 1}
    {UD   61 {} 4 0 0 Timelessness {Discard cards equaling in icon points to the level of the targeted champion, who is sent to the Abyss. (Off/3/4/5)} UC {} {27 32 33 34} {} 1}
    {UD   62 {} 4 0 0 {Hovering Road} {Creates a permanent one-way path to a chosen realm until dispelled. Regardless of the realm's restrictions, this player's champions and allies can attack that realm. (Off/3)} C {No effect if Spell Turned or Reflected.} {27 32} {} 1}
    {UD   63 {} 4 0 0 {Breath of Death} {Cast only by level 13+ champions. Kills all champions of level 6 or less in one pool and prevents survivors from attacking until after that player's next turn. (Off/3)} C {} {27 32} {} 1}
    {UD   64 19 5 7 1 {The Unnamed, Avatar of Gruumsh} {Avatar; a cleric of level 8 or higher must be discarded to bring the Unnamed into play. All players must ask Gruumsh each battle for the number of allies they can use. Limit one avatar per pool.} R {} {32 42} {1 2 d9 o9 d4 o4} 1}
    {UD   65 20 5 7 1 {The Faceless One, Avatar of Juiblex} {Avatar; two clerics equaling 12 points or more must be discarded to bring the Faceless One into play. It and any AD&D champions in the player's pool are immune to magical items of less than +3 enchantment and offensive spells. Limit one avatar per pool.} UC {} {32 42} {1 2 d9 o9 d4 o4} 1}
    {UD   66 21 5 7 1 {Moradin's Avatar} {Avatar; two dwarf champions or the Reorxcrown Mountains realm must be discarded to bring Moradin's Avatar into play. All realms held by this player can be attacked only by flyers or earthwalkers (or via Underdark realms). Limit one avatar per pool.} C Dwarf. {12 32 42} {1 2 d9 o9 d4 o4} 1}
    {UD   67 {} 15 2 0 {Invasion of the Undead} {Played at the beginning of the player's turn, this card is not discarded. It affects all players and remains in effect until any other rule card is played. The undead rise up in wrath! Any undead champions killed in battle are not discarded, but are sent to Limbo. They return to their pool at the end of their next turn, without attachments. Any undead allies lost in battle remain with them. This rule card is immune to Wish.} UC {} 29 {} 1}
    {UD   68 19 5 3 1 {The Red Death} {Avatar; Ravenloft champions totaling 10+ must be discarded to bring the Red Death into play. On its turn, it can corrupt a champion of base level 5 or less. The player can allow his champion to be the avatar's ally, or he can discard the champion instead. If used, the champion returns to its pool, minus attached cards. Limit one avatar per pool.} R Undead. {32 40 42} {1 2 d9 o9 d4 o4} 1}
    {UD   69 {} 15 7 0 {Things That Go Bump in the Night} {Played at the beginning of the player's turn, this card is not discarded. It affects all players and remains in effect until any other rule card is played. All champions and allies native to the Underdark (designated by D&D TU on each card) have infravision. All other champions and allies do not; they cannot see and their special powers don't work.} UC {} 29 {} 1}
    {UD   70 16 5 5 1 Sargonnas {Avatar; a cleric of level 8 or higher must be discarded to bring Sargonnas into play. All cards with the word 'fire' or 'red' in their title are doubled in level when played with Sargonnas. Limit one avatar per pool.} C {} {32 42} {1 2 d9 o9 d4 o4} 1}
    {UD   71 21 5 2 1 {The Uncaring, Avatar of Boccob} {Avatar; can cast wizard spells; a Greyhawk wizard and one Greyhawk realm must be discarded to bring the Uncaring into play. At the beginning of this player's turn, the Uncaring can discard one razed Greyhawk realm in play. Limit one avatar per pool.} R {} {32 42} {1 2 d4 o4 d9 o9 d19 o19} 1}
    {UD   72 17 5 1 1 {The Avatar Shar} {Avatar; a cleric and one Forgotten Realms holding must be discarded to bring Shar into play. She absorbs all offensive spells cast against this player's Forgotten Realms champions and realms, dispelling or deflecting them as she wishes. Limit one avatar per pool.} UC {} {32 42} {1 2 d9 o9 d4 o4} 1}
    {UD   73 +5 1 0 0 Baelnorn {Undead. If used in the successful defense of a realm, they remain with the realm until it is razed.} C Elf. {14 33 40 42} {o102 d102} 1}
    {UD   74 +4 1 0 0 Chitine {If played against a drow champion, it is +8. If played with Lolth, the Spider Queen, it remains with her and is shuffled back into the deck if Lolth is defeated.} C {} {33 42} {} 1}
    {UD   75 +6 1 0 0 {Crypt Servant} {Undead. Can be attached to any Underdark holding, where it becomes a permanent defending ally until the holding is discarded.} C {} {32 33 40 42} {o102 d102} 1}
    {UD   76 +6 1 0 0 Foulwing {Flyer. Devours (discards) all opposing flying allies. Can be played during another player's combat to devour one flying ally, returning to its player's hand after battle instead of being discarded.} C {} {16 33 42} {} 1}
    {UD   77 +4 1 0 0 Gnasher {Flyer. When played, devours one psionicist champion in any pool.} R {} {16 33 42} {} 1}
    {UD   78 +1 1 0 0 Magebane {If defeated by a wizard, this ally remains with the winning champion. Whenever he casts a spell, draw a card. The spell is only successful if the card's last digit is 8 or 9.} R Flyer. {16 33 42} {} 1}
    {UD   79 +5 1 0 0 {Sword Slug} {Reduces the level of all magical items played against it to 0, though it does not negate any special powers.} C {} {33 42} {} 1}
    {UD   80 +3 1 0 0 Skum {Cancels all psionic power cards played against the attached champion in combat; additional power cards cannot be played.} R {} {33 42} {} 1}
    {UD   81 +7 1 0 0 {Fey Dwarf} {Undead. If played in the successful defense of a realm, this ally stays with the champion. If defeated when attacking, it returns to the player's hand.} C {} {12 33 40 42} {o102 d102} 1}
    {UD   82 9 10 7 0 {Corpse Dragon} {Flyer. Can cast wizard spells. Undead champions and allies will not face this horrid creature.} UC {} {8 16 32 33 42} {1 2 d101 o101 d9 o9 d19 o19} 1}
    {UD   83 5 10 7 0 {Earth Weird} {Immune to offensive magical items. If defeated in combat, it regenerates and returns to its pool at the end of the player's next turn. Attached cards are discarded.} C Earthwalker. {13 32 33 42} {1 2 d9 o9} 1}
    {UD   84 7 10 7 0 Gorynych {Flyer. Can attack twice per turn if it wins its first round. On its second attack, it can wishbone, automatically razing the realm if it wins the battle, but must then be discarded.} R {} {16 32 33 42} {1 2 d9 o9} 1}
    {UD   85 5/9 10 7 0 Noran {When defending, its level is 5. When attacking, its level rises to 9 and it can spit rocks, instantly destroying all allies of level 3 or less.} C {Attack power can be used at any time in battle.} {32 33 42} {1 2 d9 o9} 1}
    {UD   86 3 10 7 0 {Gibbering Mouther} {This foul minion of Juiblex becomes level 10 and can cast cleric spells if the Faceless One is in play anywhere.} C {} {32 33 42} {1 2 d4 o4 d9 o9} 1}
    {UD   87 6 10 7 0 {Umber Hulk} {This monster and its allies can attack any Underdark realm, regardless of position.} C {} {32 33 42} {1 2 d9 o9} 1}
    {UD   88 7 10 7 0 {Mind Flayer} {Can use psionic power cards and can cast wizard spells. This monster and its allies can attack any Underdark realm, regardless of position.} C {} {32 33 42} {1 2 d9 o9 d11 o11 d19 o19} 1}
    {UD   89 2 10 7 0 Myconid {If attacking an Underdark realm, its level rises to 7. If defending an Underdark realm, it can defend twice before being discarded.} C {} {32 33 42} {1 2 d9 o9} 1}
    {UD   90 10 10 7 0 {Monster of the Lake} {Undead; swimmer. Can cast cleric spells; immune to offensive cleric spells. Its bite is poisonous to avatars, negating special powers and halving their levels (round down) in battle. If used to defend, the realm must show water.} R {} {32 33 37 40 42} {1 2 d4 o4 d9 o9 d102 o102} 1}
    {UD   91 4 7 1 0 {Belwar Dissengulp} {Gnome (svirfneblin). This hero's magical items are doubled in level, as are all dwarf and gnome allies played with him.} C {} {18 32 33 39 42} {1 2 d9 o9 d18 o18} 1}
    {UD   92 5 7 1 0 Jarlaxle {Elf (drow). When defending Menzoberranzan or any Underdark realm, Jarlaxle's level is doubled.} C {} {10 14 32 33 42} {1 2 d9 o9 d18 o18} 1}
    {UD   93 9 20 2 0 Ellorelloran {Can cast cleric spells and is immune to psionics. When Ellorelloran is first played, she can discard any rule card in play. She may be discarded to remove a subsequent rule card from play.} C {Elf (drow).} {10 14 32 33 42} {1 2 d4 o4 d9 o9 d19 o19} 1}
    {UD   94 9 7 1 0 {Zaknafein the Weapons Master} {Elf (drow). Zaknafein can attack up to 3 times per turn. On the second attack, he is level 6; on the third he is level 3.} C {} {10 14 32 33 42} {1 2 d9 o9 d18 o18} 1}
    {UD   95 8 5 1 0 {Baldar Dwellardon} {Dwarf (duergar). Immune to offensive spells. Baldar and his allies can attack any Underdark realm, regardless of position.} C {} {11 12 32 33 42} {1 2 d9 o9 d4 o4} 1}
    {UD   96 3 10 2 0 {Fowron, the Giant} {Fowron gains one level for each giant in play. Once per turn, he can duplicate the special ability of any other giant in play. (This player's use is secondary.)} C {} {17 32 33 42} {1 2 d9 o9} 1}
    {UD   97 7 10 3 0 {Chantal the Banshee} {Undead; can cast cleric spells and is immune to psionics. Because of the fear this banshee instills, any allies played with or against her are at -1.} C {} {32 33 40 42} {1 2 d4 o4 d9 o9 d102 o102} 1}
    {UD   98 4 20 5 0 Aquilla {Swimmer. Aquilla poisons all swimmers played against her, causing these champions and allies to be discarded.} UC Elf. {14 32 33 37 42} {1 2 d9 o9 d19 o19} 1}
    {UD   99 7 5 3 0 Iseult {Iseult may have two artifacts attached to her. When attacking, her opponent must hold out all spells and psionic power cards; Iseult randomly draws one to be discarded.} UC {} {32 33 42} {1 2 d9 o9 d4 o4} 1}
    {UD  100 6 12 4 0 Xontra {Psionicist; can us psionic power cards. If held by a player who has no Dark Sun realms in his formation, Xontra and her allies can attack any Dark Sun realm, regardless of position; otherwise, she must attack normally.} C {} {32 33 42} {1 2 d9 o9 d11 o11} 1}
    {UD  101 4 12 1 0 {Lazarus the Drow} {Elf (drow). All psionic power cards used by Lazarus are doubled in level. His allies are immune to psionics.} VR {} {10 14 32 33 42} {1 2 d9 o9 d11 o11} 1}
    {UD  102 {} 11 0 0 {Inflict Pain} {Playable only on an avatar or psionicist, this power inflicts pain on a champion, stripping away its powers and reducing its level to 1 until the end of this player's next turn. (Off/3)} VR {} {27 32} {} 1}
    {UD  103 +5 2 2 0 {The Hoof of Auroch} {This player's champions are immune to psionics.} VR {} {32 33} {} 1}
    {UD  104 +3 2 2 0 {The Ring of Gaxx} {The attached champion can only be discarded as a result of battle.} VR {} {32 33} {} 1}
    {UD  105 7 13 7 0 {The Deep} {This realm can defend itself as a level 7 hero who can cast wizard and cleric spells in phase 4 only. The Deep is immune to offensive spells and psionics.} VR {} {42 31} {1 d4 o4 d19 o19} 1}
    {UD  106 {} 13 7 0 {The Ultimate Triumvirate} {Adds a +12 ally to all champions of this player when attacking and negates the ally gained from all the other triumvirates unless in the same player's formation. At the start of this player's turn, he may discard this realm from the formation to send one avatar to the abyss.} VR {} {42 31} {} 1}
    {UD  107 {} 13 7 0 {The Dispossessed} {If an Underdark realm is played adjacent to this realm in the player's formation, he may discard an ally from his hand at any time to cancel any spell or psionic power card.} VR {} {42 31} {} 1}
    {UD  108 ? 13 7 0 {The Cavernous Hall} {This realm can defend itself by duplicating the level and powers of one psionicist in play. This player's use is secondary.} VR {} {42 31} {} 1}
    {UD  109 {} 6 0 0 {Underground River} {This mighty river rushes through each player's pool, sweeping away all psionicists into the discard pile. (Harmful)} VR {} {22 29 30 31 32 33 34} {} 1}
    {UD  110 {} 6 0 0 {The Way Out} {Played after an opponent has chosen an Underdark realm to attack, the event player can change the attack to any other unrazed realm in play, regardless of position or restrictions. (Harmful)} VR {} {22 29 30 31 32 33 34} {} 1}
    {UD  111 {} 6 0 0 {The Triumphant Barbarian} {All psionicists and clerics in play may not use power cards or cast spells until the end of this player's next turn. (Harmful)} VR {} {22 29 30 31 32 33 34} {} 1}
    {UD  112 {} 6 0 0 {The Minotaur Attacks!} {This player's monsters that attack from Underdark realms are doubled in base level until the end of this player's next turn. (Helpful)} VR {} {23 29 30 31 32 33 34} {} 1}
    {UD  113 {} 6 0 0 Cave-in! {Forces one player to discard an Underdark champion or holding from his pool or formation. If he has none, the event player may choose one of the player's Underdark realms to raze. (Harmful)} VR {} {22 29 30 31 32 33 34} {} 1}
    {UD  114 {} 6 0 0 {The Mandate of Dori the Barbarian} {All champions whose card number is '# of 25' (chase cards) gain 6 levels and become earthwalkers until the end of this player's next turn. (Helpful)} VR {Does not affect 401-440, 501-520, AR or PO chase.} {23 29 30 31 32 33 34} {} 1}
    {UD  115 8 10 7 0 {The Demi-Lich Zyenj} {Undead. Only magical items and artifacts of +4 or higher enchantment have any effect against the Demi-Lich. Allies cannot be played against it.} VR {Offensive magical items only.} {32 33 40 42} {1 2 d9 o9 o102 d102} 1}
    {UD  116 6 10 7 0 {The Minotaur} {Gains 3 levels when attacking an Underdark realm, and/or gains 3 levels when attacking from an Underdark realm. All magical items attached to the Minotaur gain +1.} VR {} {32 33 42} {1 2 d9 o9} 1}
    {UD  117 2 10 7 0 Piercer {Gains 1 additional level for every Underdark realm in play. If used to defend an Underdark realm, automatically defeats a champion of base level 6 or less.} VR {} {32 33 42} {1 2 d9 o9} 1}
    {UD  118 5 10 7 0 {Lurker in the Deep} {Can only be used to defend an Underdark realm. Engulfs all psionicists, magical items, and nonswimming allies, causing them to be discarded.} VR Swimmer. {32 33 37 42} {1 2 d9 o9} 1}
    {UD  119 6 7 2 0 {Oogly the Half-Orc} {Oogly is so ferocious he scares away all opposing allies of less than +6 (+5 and lower allies cannot be played against him).} VR {} {32 33 42} {1 2 d9 o9 d18 o18} 1}
    {UD  120 +3 9 0 0 {The Marble Orb} {If used by a monster, the attached champion is immune to harmful events. (Def)} VR {} {6 32 33} {} 1}
    {UD  121 +5 9 0 0 {The Sword and Helm of Garion} {If the attached champion is attacking, only psionicists, clerics, and heroes can defend against it. (Off)} VR {} {27 38 44 32 33} {} 1}
    {UD  122 +3 9 0 0 {Scourge of Mika} {If the attached champion is undead and is defeated in battle, this item goes with the winning champion until dispelled. The scourge becomes a -4 and that champion cannot cast spells or use psionic powers. (Off)} VR {} {27 44 32 33} {} 1}
    {UD  123 +3 1 0 0 {Drow Assassin} {When played in battle, this ally can also instantly kill one champion of base level 5 or less anywhere in play if this player has an unrazed Underdark realm in his formation.} VR {Elf (drow).} {10 14 33 42} {} 1}
    {UD  124 {} 6 0 0 {Broken Arrow} {Play only during combat where this player is not involved. Peace is declared and the champions return to their pools; combat is over. The event player is victorious and draws spoils. (Harmful)} VR {} {22 29 30 31 32 33 34} {} 1}
    {UD  125 {} 4 0 0 Mindshatter {Attach to any enemy champion in a pool; the champion becomes catatonic and cannot take any action until the card is dispelled. (Off/3/4)} VR {} {27 32 33} {} 1}
}
