set CrossFire::cardDataBase {
    {The Abby}
    {AB    1 {} 21 2 0 {Blind and Deaf} {All opponents that have hidden pools may not attach cards to their pools themselves. This player attaches them blindly instead. Cards not legally attached are discarded at the end of the current turn.} V {} {{Phase 0}} {} 1}
    {AB    2 {} 13 7 0 Æther {Only clerics may cast dual spells. Flyers are blessed by their gods and may look at the opponent's hand at the start of battle.} V {} {{Phase 2}} {} 1}
    {AB    3 {} 13 7 0 Aqua {Only clerics may cast dual spells. Swimmers are blessed by their gods and may triple their base level at the start of battle. Win or lose, they are discarded afterwards.} V {} {{Phase 2}} {} 1}
    {AB    4 {} 13 7 0 Harena {Only clerics may cast dual spells. Heros are blessed by their gods and may aid another player in battle as an ally, playing additional cards if necessary. These cards are doubled in level and cannot be forced to switch side.} V {} {{Phase 2}} {} 1}
    {AB    5 {} 13 7 0 Incendium {Only clerics may cast dual spells. Dragons are blessed by their gods and may keep an ally or defensive spell with them until the champion is discarded.} V {} {{Phase 2}} {} 1}
    {AB    6 {} 13 7 0 Terra {Only clerics may cast dual spells. Earthwalkers are blessed by their gods and may attack a champion in another player's pool instead of a realm.} V {} {{Phase 2}} {} 1}
    {AB    7 {} 13 7 0 {Dream Sphere} {When first played, all other player's must choose a champion from their pool who cannot act or use his special power until the end of this player's next turn.} V {} {{Phase 2}} {} 1}
    {AB    8 3 13 7 0 {Realm of Lions} {Can defend itself as a level 3 monster. Cannot be attacked by swimmers. All animals are tripled in base level when in combat.} V {} {{Phase 2}} {} 1}
    {AB    9 ? 13 1 0 {Ruins of Sugna} {When played or rebuilt, attach any number of champions (level bonus only) from your discard pile to this realm. They act as realm champions and have to be defeated one after another.} V {} {{Phase 2}} {} 1}
    {AB   10 {} 13 1 0 {Snow Castle} {Can only be attacked by flyers and earthwalkers. This player may attach two holdings to the Snow Castle. The first one played, is always affected first by other cards.} V {} {{Phase 2}} {} 1}
    {AB   11 {} 13 1 0 {The Monk's Home} {Defending champions may use any card usable in phase 4. Once per game, in phase 0, this player can force a thief to be discarded, or send one other champion to Limbo. He returns to his pool at the end of this player's next turn.} V {} {{Phase 2}} {} 1}
    {AB   12 {} 13 1 0 {The Sea Giant's Lair} {Can only be attacked by giants or swimmers. To raze this realm, its defender must be defeated by one giant and one swimmer. The victor may then draw one card extra per turn, as long as the razed realm is in play.} V {} {{Phase 2}} {} 1}
    {AB   13 {} 13 7 0 {The Sewers} {Cannot be attacked by flyers. All of this player's champions may attack any realm regardless of position of movement restrictions.} V {} {{Phase 2}} {} 1}
    {AB   14 {} 8 7 0 {Fountain of Lost Souls} {Playable on any realm. Must be in play for one real turn. Discard it to retrieve one avatar from the Abyss or the discard pile to the pool (without paying the initial costs), forcing another avatar in play to the Abyss.} V {} {{Phase 2}} {} 1}
    {AB   15 {} 8 1 0 {Karsus City} {Negates all temporary realms in play. No more may be played as long as this holding is in play.} V {} {{Phase 2}} {} 1}
    {AB   16 {} 6 7 0 Avalanche! {Play on an opponents realm. The affected realm loses all it's special powers until this event is negated or the realm is discarded. (Harmful)} V {} {Harmful {Phase 0} {Phase 1} {Phase 2} {Phase 3} {Phase 4} {Phase 5}} {} 1}
    {AB   17 {} 6 7 0 {Banish Them} {Forces one demon champion and one demonic ally to the Abyss. May not be deflected. (Harmful)} V {} {Harmful {Phase 0} {Phase 1} {Phase 2} {Phase 3} {Phase 4} {Phase 5}} {} 1}
    {AB   18 {} 6 7 0 {Cause Havoc} {One demon in play may teleport into another player's pool and enter battle with one champion of his choice at once. Both champions may only use unarmed combat cards, if legal. No other cards may be played. (Harmful)} V {} {Harmful {Phase 0} {Phase 1} {Phase 2} {Phase 3} {Phase 4} {Phase 5}} {} 1}
    {AB   19 {} 6 7 0 Chained! {Play on another player's pool. All dragons are chained and cannot act. May not be copied. (Harmful)} V {} {Harmful {Phase 0} {Phase 1} {Phase 2} {Phase 3} {Phase 4} {Phase 5}} {} 1}
    {AB   20 {} 6 7 0 {Come and Get Me!} {Shuffle this card into another player's draw pile. When this card is drawn, it must be shown at once. The original card owner immediately draws 3 cards. (Helpful)} V {} {Helpful {Phase 0} {Phase 1} {Phase 2} {Phase 3} {Phase 4} {Phase 5}} {} 1}
    {AB   21 {} 6 7 0 {Desert Cave} {Play only between two players turns. The event player can take a turn at once when you can spot two unrazed realms showing sand. Afterward, play continues where it left off. Cannot be in a deck containing Caravan or Sea Caravan. (Helpful)} V {} {Helpful {Phase 0}} {} 1}
    {AB   22 {} 6 7 0 {Dispel All} {Play to cancel any just played spell, psionic power, blood ablility, unarmed combat card and thief skill. May not be copied. (Harmful)} V Counter {Harmful {Phase 0} {Phase 1} {Phase 2} {Phase 3} {Phase 4} {Phase 5}} {} 1}
    {AB   23 {} 6 7 0 {Godless Place} {All clerics in play cannot cast spells and have no special powers until the end of the event player's next turn. (Harmful)} V {} {Harmful {Phase 0} {Phase 1} {Phase 2} {Phase 3} {Phase 4} {Phase 5}} {} 1}
    {AB   24 {} 6 7 0 Gold! {Play just after a player draws spoils of victory. This player can draw twice as many cards. The extras may only be held or discarded. (Helpful)} V {} {Helpful {Phase 0} {Phase 1} {Phase 2} {Phase 3} {Phase 4} {Phase 5}} {} 1}
    {AB   25 {} 6 7 0 {Hold that Thief!} {Playable only when ten or more champions are in play. All special powers are stripped away regardless of immunities. The event player deals the powers out anew as he wishes. Every champion must get one. Last until a realm is razed. (Harmful)} V {} {Harmful {Phase 0} {Phase 1} {Phase 2} {Phase 3} {Phase 4} {Phase 5}} {} 1}
    {AB   26 {} 6 7 0 Memory {Play on an opponents draw pile. Shuffle the cards and lay them out face down. Flip over one card noting its card type, then pick another one. If it's of the same type nothing happens. If not, discard both cards and resume playing. (Harmful)} V {} {Harmful {Phase 0} {Phase 1} {Phase 2} {Phase 3} {Phase 4} {Phase 5}} {} 1}
    {AB   27 {} 6 7 0 {No Trespassing!} {Play to prevent an attack on any realm. The attacker must choose another realm if he wants to continue to attack. This player selects which type of supporting cards the opponent may use. (Harmful)} V {} {Harmful {Phase 0} {Phase 1} {Phase 2} {Phase 3} {Phase 4} {Phase 5}} {} 1}
    {AB   28 {} 6 7 0 {Pool of Wraiths} {Play on any player's pool. All champions become undead until the end of this player's next turn. (Harmful)} V {} {Harmful {Phase 0} {Phase 1} {Phase 2} {Phase 3} {Phase 4} {Phase 5}} {} 1}
    {AB   29 {} 6 7 0 {Riders of the Apocalypse} {Play this event into your pool. If the event Apocalypse is played when this event is in play, this player may optionally keep two of one card type, discarding one of the other card types completely instead. Cannot be copied. (Helpful)} V {} {Helpful {Phase 0} {Phase 1} {Phase 2} {Phase 3} {Phase 4} {Phase 5}} {} 1}
    {AB   30 {} 6 7 0 {Sea Caravan} {Play only between two players turns. The event player can take a turn at once when you can spot two unrazed realms showing water. Afterward, play continues where it left off. Cannot be in a deck containing Caravan or Desert Cave. (Helpful)} V {} {Helpful {Phase 0}} {} 1}
    {AB   31 {} 6 7 0 {Stare Contest} {Play on your opponent before battle begins. Both players must look into each others eyes. The first who twinkles or laughs immediately loses the battle. The winner may draw a card and play it at once. (Helpful)} V {} {Helpful {Phase 0} {Phase 1} {Phase 2} {Phase 3} {Phase 4} {Phase 5}} {} 1}
    {AB   32 {} 6 7 0 Timeout! {Play to cancel any just played card. Play stops immediately. This player chooses one player to get the refreshments for all. Play continues afterwards where it left off. When copied, the next player must serve the food. (Helpful)} V {} {Helpful {Phase 0} {Phase 1} {Phase 2} {Phase 3} {Phase 4} {Phase 5}} {} 1}
    {AB   33 {} 6 7 0 Twister! {Razes one realm showing water, or discards one realm showing only trees. (Harmful)} V {} {Harmful {Phase 0} {Phase 1} {Phase 2} {Phase 3} {Phase 4} {Phase 5}} {} 1}
    {AB   34 {} 6 7 0 {Waiting Horror} {Play to prevent an attack on any realm in play. Also, this realm cannot be attacked by earthwalkers or via Underdark realms until the end of the event player's next two turns. (Helpful)} V {} {Helpful {Phase 0} {Phase 1} {Phase 2} {Phase 3} {Phase 4} {Phase 5}} {} 1}
    {AB   35 +1 9 7 0 {Brew of Idleness} {When this card is in play, all players may only play one card during each phase. (Off)} V {} {Offensive {Phase 3} {Phase 4}} {} 1}
    {AB   36 +2 9 7 0 {Mask of Concealment} {Hides the true nature of the attached champion. If targeted by another card's instant defeat power, the wearer can choose to appear as another type of champion or gender than his real one. The champion cannot be used again until it's owner's next turn. (Def)} V {} {Defensive {Phase 3} {Phase 4}} {} 1}
    {AB   37 +3 9 7 0 {Moddi's Staff} {Cannot be removed by any means if it's attached to Moddi. It enables this player to stop time and search any other player's draw pile. Discard the first card that allows the drawing of extra cards or the taking of extra turns. The Staff is then sent to the Abbys. (Off/3)} V {In phase 3 only} {Offensive {Phase 3} {Phase 4}} {} 1}
    {AB   38 {} 1 7 0 Agnar'Tam {Undead; Flyer. If on the losing side of battle, must be attached to the victorious champion. Rips away all of his immunities until this ally is discarded.} V {} {Flyer {Phase 4} Undead} {} 1}
    {AB   39 +4 1 7 0 {Hell Wyvern} {Demon; Flyer; Swimmer. Only undead allies may be played against the attached champion in battle. Fear strikes all opposing non-undead champions. They lose their special powers for this round of combat.} V Demon {Flyer {Phase 4} Swimmer} {} 1}
    {AB   40 +6 1 7 0 {My Left Horse} {May also be played as a replacement for a discarded dungeon card in phase 0. If played as a dungeon, it negates the immunities of all other player's cards for this player. Can only be removed by attacking it directly. Immune to cards that discard or instantly defeat allies.} V Animal {{Phase 0} {Phase 4}} {} 1}
    {AB   41 30 7 7 1 {Ao the Overgod} {Avatar. Discard three of your unrazed realms to bring Ao into play. Nothing else can bring him into play. No offensive spell, psionic power card, thief skill or event affects him. He may play any card useable in phase 3 or 4. All champions must ask his permission to use their special powers.} V {} {{Phase 3} {Phase 4}} {Ally Artifact {Magical Item, Def} {Magical Item, Off} {Unarmed Combat, Def} {Unarmed Combat, Off}} 1}
    {AB   42 6 7 1 0 Catti-brie {In battle, she may use her bow Taulmaril to cancel a just-played spell or thief skill. Allies of level 3 or less can't be played against her. If in the same pool as Drizzt she gains 3 levels and must be defeated twice.} V {} {{Phase 3} {Phase 4}} {} 1}
    {AB   43 6 7 1 0 {Chaldra of Tyr} {Paladin. Can use cleric spells. As long as the god of justice's faithful servant is in play, combatants are both discarded win or lose. Immune to harmul events and offensive thief skills.} V Paladin {{Phase 3} {Phase 4}} {Ally Artifact {Cleric Spell, Def} {Cleric Spell, Off} {Magical Item, Def} {Magical Item, Off} {Unarmed Combat, Def} {Unarmed Combat, Off}} 1}
    {AB   44 4 7 7 0 {Ogre Diplomat} {May only defend. Loves to negotiate. At the start of battle the opponent draws and discards a card noting the last digit. If it's 5 or less, the Ogre convinces the opposing champion to forget about the attack and return to his pool. No spoils are drawn.} V {} {{Phase 3} {Phase 4}} {Ally Artifact {Magical Item, Def} {Magical Item, Off} {Unarmed Combat, Def} {Unarmed Combat, Off}} 1}
    {AB   45 3 10 4 0 Graahl {Demon. When he is first played, teleports into every other player's unhidden pool randomly sending one card to the Abyss. When done, returns to his pool. This player must skip phases 2, 3 and 4 on his next turn.} V Demon {{Phase 3} {Phase 4}} {Ally Artifact {Magical Item, Def} {Magical Item, Off}} 1}
    {AB   46 6 10 3 0 Mariannah {Undead. Can cast wizard and cleric spells. Immune to offensive psionics. May choose to ignore the effects of one dungeon card in play for this player.} V {} {{Phase 3} {Phase 4} Undead} {Ally Artifact {Cleric Spell, Def} {Cleric Spell, Off} {Magical Item, Def} {Magical Item, Off} {Undead Unarmed Combat, Def} {Undead Unarmed Combat, Off} {Wizard Spell, Def} {Wizard Spell, Off}} 1}
    {AB   47 0 10 2 0 Sarg {All events targeted at a specific champion or champion type are redirected automatically to Sarg. They are attached to him, their effects dormant. The have not happened yet. He gains one level for each attached event. If he's sent out of play the events take place.} V {} {{Phase 3} {Phase 4}} {Ally Artifact {Magical Item, Def} {Magical Item, Off}} 1}
    {AB   48 5 10 1 0 Succubus {Demon; Flyer. Can cast wizard spells and use psionic power cards. In phase 3 may copy the power of any female champion in play for one turn.} V Demon {Flyer {Phase 3} {Phase 4}} {Ally Artifact {Magical Item, Def} {Magical Item, Off} {Psionic Power, Def} {Psionic Power, Off} {Wizard Spell, Def} {Wizard Spell, Off}} 1}
    {AB   49 15 10 1 0 {Thauglor, King of the Forest Country} {Dragon; Flyer. Can cast cleric and wizard spells. Oldest of all Faerunian dragons. No dragon may enter battle without his permission. In battle, may use any dragon champion in play as an ally. If he loses, discard the ally instead.} V {} {Dragon Flyer {Phase 3} {Phase 4}} {Ally Artifact {Cleric Spell, Def} {Cleric Spell, Off} {Dragon Unarmed Combat, Def} {Dragon Unarmed Combat, Off} {Magical Item, Def} {Magical Item, Off} {Wizard Spell, Def} {Wizard Spell, Off}} 1}
    {AB   50 4 20 1 0 {Charon's Apprentice} {Demon. Can use all cards usable in phase 4. While he is in play all cards must ask his permission to enter the Abyss. If he refuses, the card goes to the discard pile. Immune to harmful events.} V Demon {{Phase 3} {Phase 4}} {Ally Artifact {Blood Ability, Def} {Blood Ability, Off} {Cleric Spell, Def} {Cleric Spell, Off} {Dragon Unarmed Combat, Def} {Dragon Unarmed Combat, Off} {Magical Item, Def} {Magical Item, Off} {Psionic Power, Def} {Psionic Power, Off} {Thief Ability, Def} {Thief Ability, Off} {Unarmed Combat, Def} {Unarmed Combat, Off} {Undead Unarmed Combat, Def} {Undead Unarmed Combat, Off} {Wizard Spell, Def} {Wizard Spell, Off}} 1}
    {AB   51 7 20 2 0 Marsalla {Can cast cleric spells. Once per game, he can cast any one spell twice. Spells are cast at the same time. If he does so, he is sent to the Abyss at once, along with this player's foremost realm.} V {} {{Phase 3} {Phase 4}} {Ally Artifact {Cleric Spell, Def} {Cleric Spell, Off} {Magical Item, Def} {Magical Item, Off} {Wizard Spell, Def} {Wizard Spell, Off}} 1}
    {AB   52 4 20 1 0 Satanica {Demon; Flyer. Can use psionic power cards and blood abilities. Her features are so charming that all opposing male thieves, regents and psionicists are instantly defeated. Satanica is defeated automatically by any female champion.} V Demon {Flyer {Phase 3} {Phase 4}} {Ally Artifact {Blood Ability, Def} {Blood Ability, Off} {Magical Item, Def} {Magical Item, Off} {Psionic Power, Def} {Psionic Power, Off} {Wizard Spell, Def} {Wizard Spell, Off}} 1}
    {AB   53 9 5 1 0 {Moddi the Monk} {This mad man is immune to offensive spells. At the start of battle draw and discard a card from another player's draw pile noting the last digit. 0-3: hits himself - no battle, returns to his pool. 4: re-draw. 5-7: may fight. 8-9: lucky punch -  instantly wins. Draw again. Uneven: no spoils. Even: gets spoils.} V {} {{Phase 3} {Phase 4}} {Ally Artifact {Cleric Spell, Def} {Cleric Spell, Off} {Magical Item, Def} {Magical Item, Off}} 1}
    {AB   54 4 12 4 0 Mindbird {In battle, gains the icon level of all champions of level 1 or 2 in play. If defeated, may use its Brainblast to force all these champions to be discarded with it. (Off/4)} V Flyer {Flyer Offensive {Phase 3} {Phase 4}} {Ally Artifact {Magical Item, Def} {Magical Item, Off} {Psionic Power, Def} {Psionic Power, Off}} 1}
    {AB   55 7 12 1 0 {Relagor Fangoin} {Can cast cleric spells. When he first enters play, can psionically destroy one champion with the ability to discard another card in another player's pool. That champion is discarded. (Off)} V {} {Offensive {Phase 3} {Phase 4}} {Ally Artifact {Cleric Spell, Def} {Cleric Spell, Off} {Magical Item, Def} {Magical Item, Off} {Psionic Power, Def} {Psionic Power, Off}} 1}
    {AB   56 3 12 1 0 {Xytril Ottrul} {Can use thief skills. Immune to the special powers of thieves and psionicists. When he's first played, all players draw a card for each thief in play. Opposing players cannot use offensive thief skills in battle against him.} V {} {{Phase 3} {Phase 4}} {Ally Artifact {Magical Item, Def} {Magical Item, Off} {Psionic Power, Def} {Psionic Power, Off} {Thief Ability, Def} {Thief Ability, Off}} 1}
    {AB   57 8 12 1 0 {Zoran L'ltoras} {Elf. This master of the mind can cast wizard spells and use blood abilities. Cannot be defeated by a champion using psionics. May copy any psionic ability or power in play. Immune to unarmed combat cards.} V {} {Elf {Phase 3} {Phase 4}} {Ally Artifact {Blood Ability, Def} {Blood Ability, Off} {Magical Item, Def} {Magical Item, Off} {Psionic Power, Def} {Psionic Power, Off} {Wizard Spell, Def} {Wizard Spell, Off}} 1}
    {AB   58 5 16 3 0 Doombringer {Undead. Each player with four or more unrazed realms in play must attack and raze another player's realm. If not, he must raze one of his own realms in phase 5 and all other players may retrieve one realm from their discards to their hands.} V {} {{Phase 3} {Phase 4} Undead} {Ally Artifact {Magical Item, Def} {Magical Item, Off} {Thief Ability, Def} {Thief Ability, Off}} 1}
    {AB   59 6 16 1 0 {Lerold, Night Mask} {Assassin. Can use unarmed combat cards. If Lerold wins a battle, he may backstab (discard) another champion in play. He must then be discarded himself.} V Assassin {{Phase 3} {Phase 4}} {Ally Artifact {Magical Item, Def} {Magical Item, Off} {Thief Ability, Def} {Thief Ability, Off} {Unarmed Combat, Def} {Unarmed Combat, Off}} 1}
    {AB   60 {} 19 7 0 {Power Word, Shield} {Cast on a champion in any pool. Creates a impermeable shield that surrounds him. Nothing can harm him from without. No card affects him. He can't use special powers, attack or defend, but may cast defensive spells. Lasts until the end of this turn. (Def/3)} V {} {Defensive {Phase 3}} {} 1}
    {AB   61 {} 4 7 0 Conclave {Up to three clerics (no avatars) in one pool choose a leader among themselves (this player's choice). The leader has to defend first. He adds the other two's special powers to his own during battle. The other two cannot act again this turn. (Def/3)} V {} {Defensive {Phase 3}} {} 1}
    {AB   62 {} 4 7 0 {Call Blizzard} {Caster must be level 12+; only one type (Off OR Def) may be cast. All cards of level 2 - 4 of the opposing player are sent to Limbo, returning to their pool at the end of this player's turn. (Off/4) Attacker must immediately sent his hand to Limbo until the end of this player's turn. (Def/4)} V {} {Defensive Offensive {Phase 4}} {} 1}
    {AB   63 {} 4 7 0 {Call Earthquake} {Caster must be level 12+; only one type (Off OR Def) may be cast. Defending earthwalker's special powers don't work in battle. (Off/4) An attacking earthwalker is instantly defeated and returns to his pool. (Def/4)} V {} {Defensive Offensive {Phase 4}} {} 1}
    {AB   64 {} 4 7 0 {Call Sandstorm} {Caster must be level 12+; only one type (Off OR Def) may be cast. One ally (this player's choice) is discarded at once. (Off/4) An attacker's base level is reduced by 3 during combat. Any reduced below 0 are discarded. (Def/4)} V {} {Defensive Offensive {Phase 4}} {} 1}
    {AB   65 {} 4 7 0 {Call Thunderstorm} {Caster must be level 12+; only one type (Off OR Def) may be cast. Adds a +9 lightning bolt spell to your adjusted level. (Off/4) Attacking flyers are grounded, returning to their pools if not attacking an exposed realm. (Def/4)} V {} {Defensive Offensive {Phase 4}} {} 1}
    {AB   66 {} 4 7 0 {Call Tsunami} {Caster must be level 12+; only one type (Off OR Def) may be cast. Non-swimming champions and allies lose 6 base levels. (Off/4) Attacking swimmers must discard all attachments at once. (Def/4)} V {} {Defensive Offensive {Phase 4}} {} 1}
    {AB   67 {} 4 7 0 {Invoke Air} {Caster must be level 12+; only one type (Off OR Def) may be cast. Flyers gain 6 base levels and may attack twice if victorious. (Off/4) Cut your draw pile noting the last digit on the card you cut to. Opponent's base level is reduced by that number. (Def/4)} V {} {Defensive Offensive {Phase 4}} {} 1}
    {AB   68 {} 4 7 0 {Invoke Earth} {Caster must be level 12+; only one type (Off OR Def) may be cast. Earthwalkers are immune to all cards designed as offensive for this round. (Off/4) Opposing champion is automatically defeated unless he is an earthwalker or can play an ally that is one. (Def/4)} V {} {Defensive Offensive {Phase 4}} {} 1}
    {AB   69 {} 4 7 0 {Invoke Fire} {Caster must be level 12+; only one type (Off OR Def) may be cast. Adds a +9 Fireball spell to your adjusted level. (Off/4) Attacking wizards cannot cast spells, use offensive magical items and artifacts during this round. (Def/4)} V {} {Defensive Offensive {Phase 4}} {} 1}
    {AB   70 {} 4 7 0 {Invoke Light} {Caster must be level 12+; only one type (Off OR Def) may be cast. Discard either an opponents magical item or artifact. (Off/4) Attacking monster's special powers are reflected onto another champion in play (this player's choice). (Def/4)} V {} {Defensive Offensive {Phase 4}} {} 1}
    {AB   71 {} 4 7 0 {Invoke Water} {Caster must be level 12+; only one type (Off OR Def) may be cast. Opposing undead battle at half their adjusted levels. Any who drop below 3 are instantly discarded. (Off/4) A swimmer's adjusted level is doubled for this round. (Def/4)} V {} {Defensive Offensive {Phase 4}} {} 1}
    {AB   72 {} 4 7 0 {Summon Dirt} {Caster must be level 12+; only one type (Off OR Def) may be cast. All dwarves gain 5 levels for one round. (Off/4) Attacking drow and Underdark champions must discard a card from hand or pool immediately. (Def/4)} V {} {Defensive Offensive {Phase 4}} {} 1}
    {AB   73 {} 4 7 0 {Summon Dust} {Caster must be level 12+; only one type (Off OR Def) may be cast. Opposing non-flyers cannot see, and are reduced to a base level of 1 for this round of combat. (Off/4) A flyer may retrieve two allies from the discard pile. (Def/4)} V {} {Defensive Offensive {Phase 4}} {} 1}
    {AB   74 {} 4 7 0 {Summon Glare} {Caster must be level 12+; only one type (Off OR Def) may be cast. Adds a +9 sunray spell to your adjusted level. (Off/4) A monster champion's attachments are instantly sent to Limbo until the end of this player's turn. (Def/4)} V {} {Defensive Offensive {Phase 4}} {} 1}
    {AB   75 {} 4 7 0 {Summon Heat} {Caster must be level 12+; only one type (Off OR Def) may be cast. Dragons may draw two spoils of victory (Off/4) Attacking dragons get no spoils of victory. (Def/4)} V {} {Defensive Offensive {Phase 4}} {} 1}
    {AB   76 {} 4 7 0 {Summon Moisture} {Caster must be level 12+; only one type (Off OR Def) may be cast. An avatar's adjusted level is reduced by 10 for this round. (Off/4) Swimmers may retrieve one ally or spell from the discard pile. (Def/4)} V {} {Defensive Offensive {Phase 4}} {} 1}
    {AB   77 {} 11 7 0 {Refresh Memory} {All psionic power cards in this player's discard pile
are returned to his deck and reshuffled. (Def/3/5)} V {} {Defensive {Phase 3} {Phase 5}} {} 1}
    {AB   78 {} 18 7 0 {Sixth Sense} {Playable during any phase 4. Search the draw piles of all players currently involved in battle. Select two cards from each to be placed on top and bottom of the draw pile. (Off/4)} V {} {Offensive {Phase 4}} {} 1}
    {AB   79 {} 17 7 0 Duel {Play on a champion in another player's pool. The victim must immediately fight against one of this player's champions (chosen by this player). The loser (even Chernevik) is sent to the Abyss. (Off/3)} V {} {Offensive {Phase 3}} {} 1}
    {AB   80 {} 17 7 0 {Greater Death Trap} {Hide this card under a realm. If the realm is attacked reveal this card. A champion of level 10 or less is immediately discarded. All other champions return to their pool defeated. Battle ends, no spoils are drawn. (Off/3)} V {} {Offensive {Phase 3}} {} 1}
    {AB   81 {} 17 7 0 {Lesser Death Trap} {Hide this card under a realm. If the realm is attacked reveal this card. A champion of level 6 or less is immediately discarded. All other champions return to their pool defeated. Battle ends, no spoils are drawn. (Off/3)} V {} {Offensive {Phase 3}} {} 1}
    {AB   82 +6 2 2 0 {Holy Runes} {Cannot be attached to an undead or monster champion. This champion is immune to the special powers of one champion type (chosen by this player in phase 3).} V {} {{Phase 3} {Phase 4}} {} 1}
    {AB   83 +4 2 1 0 {Staff of Tempus} {Wielder is immune to the special powers of thieves and offensive thief skills. Against giants, orcs and dragons this champion activates his special powers and those of his attached cards in battle first.} V {} {{Phase 3} {Phase 4}} {} 1}
    {AB   84 +10 2 8 0 {The Loser's Cap} {All of this player's champions are immune to offensive spells (including Wish) and the attached champion is also immune to harmful events. This artifact can be used by any champion. When the cap is played all capes in play have to be discarded immediately.} V {} {{Phase 3} {Phase 4}} {} 1}
    {AB   85 +3 2 1 0 {The Monk's Glasses} {May also be attached to a champion from any world under another player's control. Enables him to and tell friend from foe, bringing him instantly back to his own pool. As long as the glasses are in play, other player's may not use this player's champions.} V {} {{Phase 3} {Phase 4}} {} 1}
    {AB   86 +4 2 7 0 {The Warden's Shield} {As long as this card is in play, all attachments and allies of this player's champions are never discarded. If they have to be discarded for any reason, they return to the player's hand instead.} V {} {{Phase 3} {Phase 4}} {} 1}
    {AB   87 -3 2 1 0 {Book of Lost Souls} {Cannot be attached to a thief. The owner of the book is immune to an opposing cleric's special powers. One other player's thief champion is stripped of his powers. If the book is removed from play, that champion's attachments are discarded.} V {} {{Phase 3} {Phase 4}} {} 1}
    {AB   88 -6 2 7 0 {Box of Pretensarius} {Cannot be attached to an undead champion. The warden of the box is immune to an opposing dragon's special powers. One other player's dungeon is stripped of his powers. If the box is removed from play, that player's highest level champion is discarded.} V {} {{Phase 3} {Phase 4}} {} 1}
    {AB   89 -4 2 2 0 {Figurine of the Lion King} {Cannot be attached to a wizard. The holder of the figurine is immune to an opposing monster's special powers. One other player's wizard champion is stripped of his powers. If the Lion figurine is removed from play, that champion's attachments are discarded.} V {} {{Phase 3} {Phase 4}} {} 1}
    {AB   90 -7 2 5 0 {Hands of Lazarus} {Cannot be attached to a swimming champion. The Hands' bearer is immune to an opposing flyer's special powers. One other player's realm is stripped of his powers. If the Hands are removed from play, that player's foremost realm is razed.} V {} {{Phase 3} {Phase 4}} {} 1}
    {AB   91 -2 2 6 0 {Skull of the Minotaur} {Cannot be attached to a cleric. The owner of the skull is immune to an opposing undead champion's special powers. One other player's regent champion is stripped of his powers. If the skull is removed from play, that champion's attachments are discarded.} V {} {{Phase 3} {Phase 4}} {} 1}
    {AB   92 -5 2 4 0 {Statue of Ulrik} {Cannot be attached to a hero. The keeper of the statue is immune to an opposing avatar's special powers. One other player's psionicist is stripped of his powers. If the statue is removed from play, that champion's attachments are discarded.} V {} {{Phase 3} {Phase 4}} {} 1}
    {AB   93 -8 2 3 0 {Totem of Mbogo} {Cannot be attached to a vampire. The owner of this unholy totem is immune to an opposing ally's special powers. Once per turn may copy an other player's event for all players. If the totem is removed from play, all players must discard all events from their hands.} V {} {{Phase 3} {Phase 4}} {} 1}
    {AB   94 {} 15 7 0 {Alea iacta est} {Played at the beginning of the player's turn, this card is not discarded. It affects all players and remains in effect until any other rule card is played. No dice may be used as long as this rule is in play. Player's must draw and discard a card instead. When this player has to draw and discard a card, he may choose to take it from any other player's draw pile.} V {} {{Phase 0}} {} 1}
    {AB   95 {} 15 7 0 {Balance and Justice} {Played at the beginning of the player's turn, this card is not discarded. It affects all players and remains in effect until any other rule card is played. This rule always affects all players. It is immune to the rule "Rules Lawyer's Delight". Every time a player gains extra cards (excluding spoils of victory) or extra turns, all other players gain them too.} V {} {{Phase 0}} {} 1}
    {AB   96 {} 15 7 0 {Deadly Adventures} {Played at the beginning of the player's turn, this card is not discarded. It affects all players and remains in effect until any other rule card is played. Every time a player has four or more adventurers in his pool, he must attack with an adventurer on his turn. Since adventuring is very dangerous, he must discard the first attacking champion win or lose.} V {} {{Phase 0}} {} 1}
    {AB   97 {} 15 7 0 {Demon's Bane} {Played at the beginning of the player's turn, this card is not discarded. It affects all players and remains in effect until any other rule card is played. All demons discarded in combat return to their pools at the end of this player's current turn.} V {} {{Phase 0}} {} 1}
    {AB   98 {} 15 7 0 {Earned Hard} {Played at the beginning of the player's turn, this card is not discarded. It affects all players and remains in effect until any other rule card is played. If three or more champions make attacks on a realm during phase 4 and win, it is automatically razed.} V {} {{Phase 0}} {} 1}
    {AB   99 {} 15 7 0 Phalanx {Played at the beginning of the player's turn, this card is not discarded. It affects all players and remains in effect until any other rule card is played. When defending, this player may form a phalanx of three champions. The attacker must defeat all three champions one after another. The lowest level champion has to defend first, the highest level champion last. Each gains the level bonus of the others in the phalanx (champions and attachments), but not their special powers.} V {} {{Phase 0}} {} 1}
    {AB  100 {} 15 7 0 {Together We are Strong} {Played at the beginning of the player's turn, this card is not discarded. It affects all players and remains in effect until any other rule card is played. All players, except the opponent, may help the current player in battle playing cards for him if possible. Cards have to be champion type legal though. If victorious, the attacked realm is razed and spoils of victory are drawn by this player and his aides.} V {} {{Phase 0}} {} 1}
}
